PC-26761 freezegun to timemachine
pass-culture/pass-culture-main pull request #10071
Opened 2024-01-08 14:12 UTC by thconte

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26761

## Vérifications

- [X] J'ai écrit les tests nécessaires
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-01-11 10:35 UTC, Vencespass approved these changes

2024-01-11 12:15 UTC, ogeber requested changes
Juste un test à changer et c'est bon pour moi

2024-01-11 12:15 UTC, ogeber commented on api/tests/connectors/api_demarches_simplifiees_test.py
> +import time_machine
(détail) Est-ce qu'on en profiterait pas pour tout normaliser et utiliser soit 
`import time_machine`
soit
`from time_machine import travel` partout ?

2024-01-11 13:34 UTC, dbaty reviewed
Détail : on devrait fusionner les commits lors du merge, car les 2 commits ne vont pas l'un sans l'autre.

2024-01-11 13:34 UTC, dbaty commented on api/tests/connectors/api_demarches_simplifiees_test.py
> +import time_machine
Je suis dans l'équipe `import time_machine`. :) Ça nécessite d'écrire explicitement `time_machine.travel()`, ce qui est un peu plus long mais reste raisonnable, et ça me semble plus clair (explicite) que juste `travel()`.

2024-01-11 13:34 UTC, dbaty commented on api/tests/core/bookings/test_api.py
> +    @travel("2032-11-17 15:00:00", tick=False)
J'ai l'impression qu'un collègue a supprimé certaines décorations avec `freeze_time()` (probablement en adaptant le test). On ne devrait donc pas avoir besoin de décorer `time_machine.travel()` pour ces cas-là. (Cf. aussi plus bas dans ce fichier, et peut-être ailleurs.)

2024-03-04 14:58 UTC, dbaty approved these changes
Beau boulot ! J'ai juste noté des fonctions où l'on ajoutait `timemachine` alors qu'on n'utilisait pas `freezegun`. Peut-être qu'on a supprimé des usages de `freezegun` sur la branche "master", et que le rebase de ta branche s'est "mal" passé  ?

2024-03-04 14:58 UTC, dbaty commented on api/tests/core/bookings/test_api.py
> +    @time_machine.travel("2032-11-17 15:00:00", tick=False)
On ajoute ici, est-ce voulu ? C'est peut-être un "mauvais merge" suite à la suppression de l'usage de `freezegun` ici ?

2024-03-04 14:58 UTC, dbaty commented on api/tests/core/bookings/test_api.py
> +    @time_machine.travel("2032-11-17 15:00:00", tick=False)
idem, ajout non nécessaire ?

2024-03-04 14:58 UTC, dbaty commented on api/tests/core/offerers/test_api.py
> +    @time_machine.travel("2020-10-15 00:00:00", tick=False)
Idem ici, a-t-on vraiment besoin de cette ligne ?

2024-03-04 14:58 UTC, dbaty commented on api/tests/core/users/test_api.py
> +    @time_machine.travel("2021-05-27", tick=False)
idem, a-t-on besoin de cette ligne ?

2024-03-04 14:58 UTC, dbaty commented on api/tests/routes/native/v1/account_test.py
> +            # `now()` function, which is NOT overriden by
Mon [dictionnaire](https://www.merriam-webster.com/dictionary/override) me dit qu'il y a bien 2 "d" à overridden.

2024-03-04 14:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    @time_machine.travel("2020-11-17 15:00:00")
ajout non nécessaire ?

2024-03-04 15:15 UTC, thconte commented on api/tests/core/bookings/test_api.py
> +    @time_machine.travel("2032-11-17 15:00:00", tick=False)
Effectivement, on dirait que certains ont échappé à ma vigilance. C'est corrigé.

2024-03-04 15:43 UTC, ogeber commented on api/tests/core/mails/transactional/educational/eac_sending_offerer_activation_test.py
> +    @time_machine.travel("2019-11-26 18:29:20.891028")
on peut supprimer celui là

2024-03-04 15:43 UTC, ogeber commented on api/tests/routes/native/v1/banner_test.py
>          a_year_ago = datetime.datetime.utcnow() - relativedelta(years=1, months=1)
(détail) on peut sans doute écrire ça  plus proprement
```suggestion
        with time_machine.travel(datetime.datetime.utcnow() - relativedelta(years=1, months=1))
```

2024-03-04 15:48 UTC, thconte commented on api/tests/routes/native/v1/banner_test.py
>          a_year_ago = datetime.datetime.utcnow() - relativedelta(years=1, months=1)
Tu trouves plus propre de ne pas mettre le delta dans une variable ?

2024-03-04 15:54 UTC, ogeber approved these changes

2024-03-04 15:54 UTC, ogeber commented on api/tests/routes/native/v1/subscription_test.py
> +    @time_machine.travel("2022-09-08 12:01:12.343025")
pas besoin des microsecondes

2024-03-04 15:54 UTC, ogeber commented on api/tests/routes/native/v1/subscription_test.py
> +    @time_machine.travel("2022-09-08 12:39:04.289878")
idem, pas besoin des secondes / microsecondes

2024-03-04 15:54 UTC, ogeber commented on api/tests/routes/native/v1/subscription_test.py
> +    @time_machine.travel("2022-09-08T12:45:13.534068")
idem, pas besoin es secondes / microsecondes

2024-03-04 15:54 UTC, ogeber commented on api/tests/routes/public/collective/endpoints/get_collective_offers_test.py
> +import time_machine
on est sur d'en avoir besoin ? les tests de tout ce fichier passent sans time_machine chez moi

2024-03-04 16:36 UTC, merged