(PC-26612)[API] feat: add OpeningHours table
pass-culture/pass-culture-main pull request #10302
Opened 2024-01-18 13:15 UTC by ogeber

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-26612

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [x] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-01-18 14:05 UTC, damien-ramelet commented on api/src/pcapi/core/offerers/models.py
> +    weekday: Weekday = Column(sa.Enum(Weekday, create_constraint=False), nullable=False, default=Weekday.MONDAY)
Tu peux utiliser un `MagicEnum`, il y a pas mal d'exemples dans le repo

2024-01-18 17:02 UTC, ghaliela commented on api/src/pcapi/core/offerers/models.py
> +    weekday: Weekday = Column(sa.Enum(Weekday, create_constraint=False), nullable=False, default=Weekday.MONDAY)
@damien-ramelet Tu peux expliquer l'intérêt :pray:

2024-01-18 17:24 UTC, damien-ramelet commented on api/src/pcapi/core/offerers/models.py
> +    weekday: Weekday = Column(sa.Enum(Weekday, create_constraint=False), nullable=False, default=Weekday.MONDAY)
La docstring de MagicEnum est plutôt self explanatory je trouve 

```
class MagicEnum(sqla_types.TypeDecorator):
    """A column type that stores an instance of a Python Enum object as a
    string or integer (depending on the type of the enum).

    It automatically converts from/to the raw value (string or
    integer), which means that you always handle enums and never have
    to specify access to the ``value`` attribute.

    Usage:

         class Color(enum.Enum):
             RED = "red"
             BLUE = "blue"

         class Wall(Base, Model):
             color = sqla.Column(MagicEnum(Color))

         wall = Wall(color=Color.RED)  # not `Color.RED.value`
         wall = Wall.query.first()
         assert wall.color == Color.RED  # again, not `Color.RED.value`
    """
```

2024-01-23 10:14 UTC, damien-ramelet commented on api/src/pcapi/core/offerers/models.py
> +    timespan: list[psycopg2.extras.DateTimeRange] = Column(sa_psql.ARRAY(sa_psql.TSRANGE), nullable=True)
Ça pourrait valoir le coup d'avoir une petite contrainte pour vérifier que les range ne se recouvre pas pour un même lieu, comme `8:00-12:00` `11:00-15:00` qui n'a aucun sens, tu peux regarder la table `VenueBankAccountLink` pour avoir un exemple

2024-01-23 16:42 UTC, ogeber commented on api/src/pcapi/core/offerers/models.py
> +    timespan: list[psycopg2.extras.DateTimeRange] = Column(sa_psql.ARRAY(sa_psql.TSRANGE), nullable=True)
Yes bien vu. J'ai tenté un truc, dis moi ce que tu en penses (et j'ai ajouté une contrainte sur le nombre de timespan en DB)

2024-01-25 10:28 UTC, damien-ramelet commented on api/src/pcapi/core/offerers/models.py
> +    timespan: list[psycopg2.extras.DateTimeRange] = Column(sa_psql.ARRAY(sa_psql.TSRANGE), nullable=True)
J'ai tout de même un gros doute sur le type de la colonne, on cherche à stocker les horaires d'ouvertures, mais on se retrouve à stocker des datetime non ? Et la partie date n'aura aucun sens non ? Est-ce qu'on final ça ne serait pas plus simple d'avoir deux colonnes `TIME` `beginning` & `end` par exemple ?

2024-01-25 13:04 UTC, dbaty commented on api/src/pcapi/core/offerers/models.py
> +    timespan: list[psycopg2.extras.DateTimeRange] = Column(sa_psql.ARRAY(sa_psql.TSRANGE), nullable=True)
J'ai suggéré ça, moi ? Je ne sais plus. :) C'est vrai que ça n'est peut-être pas tout à fait adapté. On pourrait stocker un array de `numrange`, en calculant `HH * 60 + MM`. Par exemple : 9h00-12h30 serait représenté par le range `[540, 21600]`.

Mais c'est toujours le problème avec l'ajout d'un modèle seul dans une pull request : on ne voit pas (encore) son utilisation. ;)

2024-01-29 09:03 UTC, Aliochka commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    openingHours: list[OpeningHoursResponseModel] | None
je demande l'avis des front demain, 
mais je pense que ce serait bien de rajouter la timezone du lieu aussi !

2024-01-30 11:19 UTC, ogeber commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    openingHours: list[OpeningHoursResponseModel] | None
C'est ajouté

2024-01-31 08:54 UTC, mageoffray approved these changes

2024-01-31 08:54 UTC, mageoffray commented on api/src/pcapi/core/offerers/factories.py
> +class PermanentVenueFactory(VenueFactory):
Tu peux modifier la VenueFactory pour utiliser le décorateur `@factory.post_generation`. Après la création du lieu tu peux vérifier si il est permanent et dans ce cas là appeler une fonction qui créé les openingHours. 
Ca te permettra d'éviter d'avoir à faire un ticket pour ajouter des données à la sandbox ensuite.

2024-01-31 08:54 UTC, mageoffray commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    openingHours: list[OpeningHoursResponseModel] | None
Tu modifies le serializer de la GetVenueResponse, mais aucune requêtes, est-ce qu'il n'y aurait pas de requêtes n+1 de créées ?

2024-01-31 10:55 UTC, mageoffray requested changes
Au final après tests et discusssion, utilisation de numrange[]

2024-02-06 13:06 UTC, mageoffray approved these changes
(Question) Est-ce que tu as pu voir avec les fronts si ce format de réponse est ok pour eux ?

2024-02-06 13:06 UTC, mageoffray commented on api/src/pcapi/core/offerers/models.py
> +    def opening_hours_as_dict(self) -> list[dict]:
Je m'attends à avoir un dict retourné par opening_hours_as_dict. Tu peux la nommer `opening_days`

2024-02-07 08:33 UTC, merged