Ghaliela/bsr create min sandbox for ci
pass-culture/pass-culture-main pull request #10400
Opened 2024-01-24 16:42 UTC by ghaliela

2024-01-25 15:04 UTC, mariedestandau commented
hello @ghaliela ! 

On a évoqué récemment cette piste avec @kopax et @mageoffray et on y a renoncé parce que @mageoffray nous a alerté sur le fait que le back n'avait pas la bande passante nécessaire pour remplir une sandbox dédiée avec les données complexes qui vont être nécessaires à tous les tests E2E. 

Est-ce que tu as prévu de remplir la sandbox ? 

Si ce n'est pas le cas je ne suis pas trop favorable à ce qu'on merge cet essai, qui dans les faits ne sera pas utilisable. À ce moment-là on peut garder la référence à ta PR comme POC pour quand quelqu'un pourra remplir cette sandbox.

2024-01-25 16:35 UTC, ghaliela commented
> hello @ghaliela !
> 
> On a évoqué récemment cette piste avec @kopax et @mageoffray et on y a renoncé parce que @mageoffray nous a alerté sur le fait que le back n'avait pas la bande passante nécessaire pour remplir une sandbox dédiée avec les données complexes qui vont être nécessaires à tous les tests E2E.
> 
> Est-ce que tu as prévu de remplir la sandbox ?
> 
> Si ce n'est pas le cas je ne suis pas trop favorable à ce qu'on merge cet essai, qui dans les faits ne sera pas utilisable. À ce moment-là on peut garder la référence à ta PR comme POC pour quand quelqu'un pourra remplir cette sandbox.

Dans cette PR je compte avoir une sandbox fonctionnelle pour les tests E2E actuelle, ensuite il faudra ajouter des données au fur et à mesure de rajout de tests

2024-01-26 08:48 UTC, mariedestandau requested changes
@ghaliela ce sont les dev front qui écrivent les E2E et ils ne sont pas en mesure d'ajouter des données complexes dans la sandbox. La conclusion de la réunion qu'on a fait récemment avec @mageoffray et @kopax est que back n'a pas la bande passante pour le faire, donc cette option n'est pas viable pour le moment, sauf si quelqu'un prend le sujet et ajoute toutes ces données. Si cela t'intéresse on peut en discuter pour voir comment rassembler la description de toutes les données nécessaires. En attendant il ne me semble pas souhaitable de merger ce mécanisme qui n'est pas en phase avec le workflow.

2024-01-26 09:33 UTC, kopax-polyconseil commented
@mariedestandau j'ai justement proposé à @ghaliela qui voulais passer une pr qui amélioré la façon dont c'est fait actuellement de utiliser les 2 hook cypress pour corriger 2 problèmes :

1. Les tests e2e doivent tourner sur n'importe quelle base de donnée du moment que la bdd match avec la version des tests 
2. La tests e2e doivent pouvoir être relancé n fois.

Côté ops on m'a demandé de ne pas faire du code comme nous sommes 3. Le fait de laisser les front end écrire leur donnée est un autre ticket et rajoute à celui ci qui resoud un autre problème et ne résoudre pas l'existant. 

Je ne vois aucune raison de bloquer la pr comme elle n'engendre pas de régression à priori et apporte que des améliorations qui seront utiles pour l'homologation rgs et nous permette déjà à nous de tester nos backups.

2024-01-26 10:19 UTC, mariedestandau commented
@kopax-polyconseil  On a fait une réu il y a 15 jours et on s'est mis d'accord que ce n'était pas le moment, ça me semble normal qu'on soit dans la boucle si tu relances le sujet avec @ghaliela 

Pour reprendre ce qu'on a dit, côté front cette approche nous convient très bien si on a des données utilisables dedans. Si vous voulez la mettre en place il faut prévoir les données aussi et on sera ravis de l'utiliser. 

Sinon je ne suis pas d'accord pour qu'on ajoute du code inutile, on passe déjà beaucoup trop de temps à nettoyer du code qui ne sert à rien. En l'état on va être obligés de continuer à utiliser la sandbox actuelle puisqu'on ne peut pas remplir la nouvelle - donc on va avoir deux systèmes parallèles impossibles à démêler sans les avantages ni de l'un ni de l'autre.

2024-01-26 12:53 UTC, kopax-polyconseil commented
> ça me semble normal qu'on soit dans la boucle si tu relances le sujet avec @ghaliela

C'est mon erreur et je m'excuse, il m'a ping en privé, cela aurait du être sur le channel créé pour l'occasion.

> Pour reprendre ce qu'on a dit, côté front cette approche nous convient très bien si on a des données utilisables dedans. Si vous voulez la mettre en place il faut prévoir les données aussi et on sera ravis de l'utiliser.

Oui, c'est ce que je disais, si les tests e2e passent avant un merge pour moi cela remplis ce point non ?

> Sinon je ne suis pas d'accord pour qu'on ajoute du code inutile, on passe déjà beaucoup trop de temps à nettoyer du code qui ne sert à rien. En l'état on va être obligés de continuer à utiliser la sandbox actuelle puisqu'on ne peut pas remplir la nouvelle - donc on va avoir deux systèmes parallèles impossibles à démêler sans les avantages ni de l'un ni de l'autre.

Je ne comprends pas ce point. Pour moi on deprecie l'ancien pour une fonction dédié au tests e2e

2024-05-23 12:51 UTC, closed without merging