(PC-27712)[API] feat: [WIP][BO] auto rejected offerer if siren-caduc and pending
pass-culture/pass-culture-main pull request #10530
Opened 2024-01-31 10:31 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-27712

WIP WIP WIP

2024-02-01 16:24 UTC, prouzet commented on api/src/pcapi/core/offerers/tasks.py
> +            if offerer.validationStatus == offerer.validationStatus.PENDING:
On doit rejeter les `PENDING` mais aussi les `NEW`, ces deux états sont en attente de validation
```suggestion
            if offerer.isWaitingForValidation:
```

2024-02-01 16:24 UTC, prouzet commented on api/src/pcapi/core/offerers/tasks.py
> +                offerer.tags = [tag]
NON, tu supprimes tout tag éventuellement déjà présent sur la structure !
Pourquoi ne pas garder `db.session.add(offerers_models.OffererTagMapping(offererId=offerer.id, tagId=tag.id))` ??

2024-02-01 16:24 UTC, prouzet commented on api/src/pcapi/core/offerers/tasks.py
> +                )
J'ai précisé dans le ticket : «  voir Notion : https[...] paragraphe Rejet automatique de structure », dans lequel il est écrit : « rejeter la structure, en appelant la même fonction que celle appelée par l’action BO : pcapi.core.offerers.api.reject_offerer() : »
Pourquoi réécrire différemment plutôt qu'utiliser le code existant, avec le même commentaire ?

2024-02-01 16:24 UTC, prouzet commented on api/src/pcapi/core/offerers/tasks.py
> +            else:
Pourquoi ne pas mettre l'ajout du tag dans l'historique lorsqu'on rejette ?

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_commands.py
> +        )  # not checked because already tagged
Je préfère le code initial plutôt qu'avec un nom de constante qui induit en erreur... On ne teste pas tous les 24 jours mais une fois par mois.

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +    def test_offerer_if_tag_inactif(self, mock_get_siren, client, siren_caduc_tag):
```suggestion
    def test_tag_inactive_offerer(self, mock_get_siren, client, siren_caduc_tag):
```

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +        )
```suggestion
        offerer = offerers_factories.PendingOffererFactory()
```

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +    def test_offerer_with_pending_status_should_be_rejected_if_tag_inactif(
On ne rejette pas s'il y a un tag inactif, mais si la structure est inactive.

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +    def test_do_not_tag_the_offerer_if_tag_is_actif(self, mock_get_siren, client, siren_caduc_tag):
Pourquoi changer le nom pour quelque chose mi-anglais mi-français qui ne correspond pas au cas ?
```suggestion
    def test_do_not_tag_inactive_offerer(self, mock_get_siren, client, siren_caduc_tag):
```

2024-02-01 16:24 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +        assert offerer.validationStatus == ValidationStatus.REJECTED
```suggestion
        assert offerer.isRejected
```

2024-02-02 15:24 UTC, Vencespass commented on api/src/pcapi/core/offerers/tasks.py
> +                    comment="La structure en attente avec siren caduc est rejeté",
```suggestion
                    comment="La structure en attente est rejetée car son SIREN est caduc",
```

2024-02-06 17:06 UTC, prouzet requested changes

2024-02-06 17:06 UTC, prouzet commented on api/tests/core/offerers/test_tasks.py
> +
Il manque des vérifications, celles que je t'ai citées à nouveau ce matin : 
- vérifier que le mail est bien envoyé
- vérifier que l'action est bien enregistrée dans l'historique (structure rejetée, avec ajout du tag)

Des idées en vrac, NON TESTÉES : 
```
        action = history_models.ActionHistory.query.filter_by(
            actionType=history_models.ActionType.OFFERER_REJECTED
        ).one()
        assert action.actionDate is not None
        assert action.authorUserId is None
        assert action.offererId == offerer.id

        assert len(mails_testing.outbox) == 1 
        assert mails_testing.outbox[0]["To"] == user_offerer.user.email
        assert mails_testing.outbox[0]["template"] == asdict(TransactionalEmail.NEW_OFFERER_REJECTION.value)

```

2024-02-07 12:28 UTC, prouzet approved these changes
Avec accord d' @elizoturner  et en l'absence de @borisLeBonPro j'ai fait les corrections nécessaires afin de faire passer ce ticket avant la MES demain.

2024-02-07 13:11 UTC, Vencespass approved these changes

2024-02-07 14:35 UTC, merged