[PC-12877]: Ping slack au changement de feature flip
pass-culture/pass-culture-main pull request #1064
Opened 2022-01-18 15:37 UTC by apibrac

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12877

## But de la pull request

(Ajout de fonctionnalités, Problèmes résolus, etc)

##  Implémentation

- (Ajouts de modèles, Changements significatifs)
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-01-24 11:53 UTC, francois-seguin commented on api/requirements.txt
> +slack-sdk==3.13.0
Notifier via POST sur un nouveau webhook serait effectivement tout aussi efficace et bien plus léger qu’ajouter le SDK Slack pour cet usage.
Envisage-t-on d'autres usages pour ce SDK ?

2022-01-24 14:20 UTC, jeremieb-pass commented on api/src/pcapi/notifications/internal/transactional/change_feature_flip.py
> +    links = (
à quoi sert le second lien ?

2022-01-24 14:23 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        data = dict(isActive="true" if isActive else "false")
(détail / style) `data = {"isActive": "true" if isActive else "false"}`

2022-01-24 14:24 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={feature.id}", form=data)
Je ne comprends pas bien pourquoi on fait exactement la même requête ici =/

2022-01-24 16:31 UTC, apibrac commented on api/requirements.txt
> +slack-sdk==3.13.0
> Envisage-t-on d'autres usages pour ce SDK ?

Non pour le coup je nous verrais bien ajouter d'autres messages dans d'autres channel mais certainement que du POST webhook

> tout aussi efficace et bien plus léger

Est ce que tu pense que le "poid" est à prendre en compte ? Côté serveur ces problématiques sont pas vraiment déterminantes non ? En tout cas pas autant que côté front

Pour moi l'important c'est surtout la clareté et la maintenance. Si on fait le POST nous même c'est pas énorme mais on va certainement refaire une fonction explicite avec la même interface que le sdk, rajouter une gestion d'erreur et quelques tests, pour moi ça revient à recoder une partie du sdk d'où l'idée de l'utiliser plutôt

Donc je suis plutôt pro sdk mais je veux bien être requestionner encore

2022-01-24 17:12 UTC, francois-seguin commented on api/requirements.txt
> +slack-sdk==3.13.0
Je n'étais pas clair en parlant de poids.

Ce n'est pas tant la taille du paquet téléchargé/installé par `pip` – qui ne me semble pas problématique en soi pour ce paquet en particulier – que l'ajout d'une dépendance à une librairie externe dont on va utiliser une fonctionnalité très limitée et sur laquelle on n'aura pas la maîtrise de la maintenance et de la sécurité.

Cet équilibre entre réinventer la route vs. accomplir des tâches avec des outils externes n'est pas universel, on peut lancer la question sur notre Slack.

2022-01-25 11:42 UTC, apibrac commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={feature.id}", form=data)
J'ai changé le commentaire tu me dis si c'est plus clair ?

2022-01-25 13:19 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={feature.id}", form=data)
Ok au temps pour moi.

(détail) est-ce que ça ne serait pas plus simple d'utiliser explicitement `True` et `False` ?

2022-01-25 13:29 UTC, apibrac commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={feature.id}", form=data)
En fait je connais pas la valeur de cette feature au début de test
Ce que je peux faire : 
- filtrer sur une valeur au moment de query une feature pour utiliser explicitement True et False
- créer des feature spécialement pour le test, avec des factories

J'ai pas fait l'option 2 parce que je sentais que les features avaient pas le même cycle de vie que les autres modèles, mais il y a peut être pas plus de raisons que ça c'est peut être le plus clair ?

2022-01-25 13:46 UTC, cgaunet commented on api/requirements.txt
> +slack-sdk==3.13.0
Slack-ception

2022-01-26 16:41 UTC, apibrac commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={feature.id}", form=data)
@jeremieb-pass  j'ai corrigé avec Factories, est ce que c'est plus clair comme ça ?

2022-01-27 11:46 UTC, francois-seguin commented on api/tests/admin/custom_views/feature_view_test.py
> +        inactive_feature = FeatureFactory(isActive=False)
J'ai l'impression qu'ajouter une _Factory_ pour le modèle `Feature` est piégeux car la cible est de ne plus ajouter des objets manuellement en DB; pourquoi ne pas continuer de récupérer dans les tests celles définies dans  l'enum `FeatureToggle` ?

2022-01-27 11:46 UTC, francois-seguin commented on api/src/pcapi/notifications/internal/backends/slack.py
> +    def send_internal_message(self, channel: str, blocks, icon_emoji: str):
Est-ce que l'on peut ajouter une docstring expliquant comment formater `blocks`, et quels `channel` et `icon_emoji` sont disponibles et/ou le lien vers la doc ?

2022-01-27 13:24 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        inactive_feature = FeatureFactory(isActive=False)
Comment tu vois le test avec `FeatureToggle` dans ce cas ?

2022-01-27 13:29 UTC, jeremieb-pass approved these changes
Juste : ajout de la _docstring_ de `send_internal_message` (cf. commentaire de François) ; ça serait cool.

2022-01-27 13:44 UTC, francois-seguin commented on api/tests/admin/custom_views/feature_view_test.py
> +        inactive_feature = FeatureFactory(isActive=False)
En laissant comme avant: récupérer une feature via l'ORM en filtrant sur `isActive` si besoin.

2022-01-27 15:02 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        inactive_feature = FeatureFactory(isActive=False)
`feature = Feature.query.filter_by(isActive=False).first()` donc ?
Si oui, je comprends mieux. Tu as raison, mieux vaut récupérer la _feature_ comme ça.

2022-02-02 08:29 UTC, apibrac commented
@jeremieb-pass @francois-seguin  je peux vous demander une dernière relecture plz ? 🙏
Notamment pour : 
- le cleanup du test je sais pas si c'est très propre
- je suis pas très fluent en docstring si vous avez des retours je suis preneur

Merci !!

2022-02-02 16:56 UTC, jeremieb-pass requested changes

2022-02-02 16:56 UTC, jeremieb-pass commented on api/src/pcapi/notifications/internal/__init__.py
> +def send_internal_message(channel: str, blocks, icon_emoji: str):
blocks est un dict si j'ai bien suivi ? Est-ce qu'il est possible de préciser son type ?
Et préciser la type du retour au passage (None) : 

```python
def send_internal_message(channel: str, blocks: dict, icon_emoji: str) -> None:
```

2022-02-02 16:56 UTC, jeremieb-pass commented on api/src/pcapi/notifications/internal/__init__.py
> +        icon_emoji: emoji name as a string. Can be used to easily identify the origin of the message. Beware that messages from the same bot are sometimes aggregated in a way that a chage of emoji is
Qu'est-ce qu'un nom d'emoji ? Si on veut utiliser 😓 on utilise quoi : `:sweat:` ? `sweat` ? autre ?

2022-02-02 16:56 UTC, jeremieb-pass commented on api/src/pcapi/notifications/internal/__init__.py
> +        Nothing
`None` ;)

Ceci dit, ce dernier bloc (Returns) est un peu superflu si tu précise la valeur de retour plus haut (voir commentaire précédent), vu qu'il n'y a rien de particulier à dire.

2022-02-02 16:59 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        response = client.post(f"/pc/back-office/feature/edit?id={inactive_feature.id}", form=data)
utilise directement la _fixture_ `client` :

```python
def test_feature_edition(self, mocked_validate_csrf_token, client):
    [...]
    response = client.with_session_auth("admin@example.com").post(f"/pc/back-office/feature/edit?id={inactive_feature.id}", form=data)
```

Ou un peu différemment, comme tu préfères, mais mieux vaut généraliser l'emploi de cette _fixture_.

2022-02-02 17:00 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        assert Feature.query.get(inactive_feature.id).isActive is True
```python
assert Feature.query.get(inactive_feature.id).isActive
```

2022-02-02 17:00 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +        assert Feature.query.get(active_feature.id).isActive is False
```python
assert not Feature.query.get(active_feature.id).isActive
```

2022-02-02 17:03 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +    @clean_database
C'est un peu bourrin, non ?

Ajouter cette ligne

```python
pytestmark = pytest.mark.usefixtures("db_session")
```

en dehors de cette classe/méthode, par exemple juste au-dessus de la ligne 12, devrait être ok il me semble. Et ça évite l'étape de clean up à la fin du test.

2022-02-02 17:22 UTC, apibrac commented on api/src/pcapi/notifications/internal/__init__.py
> +def send_internal_message(channel: str, blocks, icon_emoji: str):
Non c'est une list 
Je rajoute du coup ^^

2022-02-02 17:28 UTC, apibrac commented on api/tests/admin/custom_views/feature_view_test.py
> +    @clean_database
> C'est un peu bourrin, non ?

No se pour moi c'était dans tous les tests

Je tente le pytestmark, même si je ne comprends pas grand chose à cette suggestion ^^

2022-02-02 18:41 UTC, jeremieb-pass commented on api/tests/admin/custom_views/feature_view_test.py
> +    @clean_database
Ca permet d'appliquer la fixture db_session sur tous les tests.
Et surtout `db_session` permet de :

> perform direct updates that will be rolled back when the test exits. It exposes the same API as SQLAlchemy's scoped_session object.

https://github.com/jeancochrane/pytest-flask-sqlalchemy#db_session

2022-02-02 18:41 UTC, jeremieb-pass commented on api/src/pcapi/notifications/internal/__init__.py
> +def send_internal_message(channel: str, blocks, icon_emoji: str):
mince, raté 😅

2022-02-03 18:33 UTC, jeremieb-pass approved these changes

2022-02-03 18:55 UTC, merged