BSR: owners dev team on ci
pass-culture/pass-culture-main pull request #10702
Opened 2024-02-12 15:46 UTC by sliabat-pass

## But de la pull request

Permettre à la team github `ci-owners` de maintenir et améliorer la CI.

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-02-13 15:15 UTC, sliabat-pass commented
@francois-seguin @mageoffray Un ptit approve ?

2024-02-13 15:28 UTC, francois-seguin approved these changes

2024-02-13 15:29 UTC, francois-seguin requested changes
Ah il semble qu'il faille que le groupe soit visible publiquement + write permissions

> CODEOWNERS errors
> Unknown owner on line 4: make sure the team @pass-culture/ci-owners exists, is publicly visible, and has write access to the repository

2024-02-16 09:28 UTC, sliabat-pass commented
Bien vu Francois ! j'avais oublié.
C'est fait.

2024-02-16 10:12 UTC, dbaty approved these changes

2024-02-16 10:12 UTC, dbaty commented on .github/CODEOWNERS
> +### DevOps team is notified to garantee consistency ansd security good pratices
```suggestion
### DevOps team is notified to guarantee consistency and security good practices
```

2024-02-22 16:55 UTC, sliabat-pass commented on .github/CODEOWNERS
> +### DevOps team is notified to garantee consistency ansd security good pratices
ok

2024-02-22 16:58 UTC, sliabat-pass commented
> Ah il semble qu'il faille que le groupe soit
> 
> * visible publiquement: ça m'a l'air bon
> * ait une write permission sur le repo: je ne le vois pas
> 
> > CODEOWNERS errors
> > Unknown owner on line 4: make sure the team @pass-culture/ci-owners exists, is publicly visible, and has write access to the repository

@francois-seguin ton request changed bloque le merge.
Si ok pour vous, j'ai créé deux groupes en mettant les personnes comme j'ai pu, avec les infos que j'avais. On peut ajuster en fonction après.

2024-02-26 08:25 UTC, francois-seguin approved these changes

2024-02-26 13:51 UTC, merged