(PC-28179)[API] feat: enable new user to new nav according to id parity
pass-culture/pass-culture-main pull request #11384
Opened 2024-03-21 14:04 UTC by AleksDPass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-28179
Activer la nouvelle navigation lors de la création des utilisateur selon la parité de leur id.
## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-03-22 13:38 UTC, damien-ramelet approved these changes

2024-03-22 13:38 UTC, damien-ramelet commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            .filter(User.email.in_(emails), User.pro_new_nav_state.has())
Tu vérifie qu'il y a bien une ligne dans la table `ProNewNavState` qui fait référence à notre utilisateur, mais ce qui nous intéresse surtout c'est de tester que le champ `Nouvelle navigation` (NewNavDate donc) soit bien rempli à l'inscription (cf le ticket), or ça n'est pas le cas. idem pour l'utilisateur invité

2024-03-22 13:38 UTC, damien-ramelet commented on api/src/pcapi/core/users/api.py
> +        db.session.rollback()
C'est un peu confus et assez peu lisible. On peut déléguer la responsabilité à l'appelant de commit ou rollback, ça nous permet déjà de désindenté d'un block. Je te propose une réécriture:

```python

    db.session.add(new_pro_user)
    db.session.flush()
    if new_pro_user.is_invited and new_pro_user.should_have_new_nav:
        # do some stuff
    elif new_pro_user.should_have_new_nav:
        # do some other stuff
```

2024-03-22 13:38 UTC, damien-ramelet commented on api/tests/routes/pro/signup_pro_V2_test.py
> +
Je te propose du réécriture du test, qui est plus complet:

```python
    @override_features(WIP_ENABLE_NEW_NAV_AB_TEST=True)
    def test_user_pro_new_nav_bar_ab_(self, client):
        data = BASE_DATA_PRO.copy()
        for _ in range(10):
            data["email"] = "".join(random.choices(string.ascii_letters, k=12)).lower() + "@test.com"
            response = client.post("/v2/users/signup/pro", json=data)
            assert response.status_code == 204
            user = User.query.filter_by(email=data["email"]).one()

            invited_email = f"""{data["email"].split("@")[0]}_invite_titi@test.com"""
            user_inviter = user
            OffererInvitationFactory(user=user_inviter, email=invited_email)
            data["email"] = invited_email
            response = client.post("/v2/users/signup/pro", json=data)
            assert response.status_code == 204

            if user.id % 2:
                assert user.pro_new_nav_state is None
                invited_user = User.query.filter_by(email=data["email"]).one()
                assert invited_user.pro_new_nav_state is None
            else:
                assert user.pro_new_nav_state.eligibilityDate
                assert user.pro_new_nav_state.eligibilityDate

```

2024-03-22 13:39 UTC, damien-ramelet reviewed
Je ne voulais approve ! :)

2024-03-22 13:39 UTC, damien-ramelet requested changes
Je ne voulais pas approve, bien évidemment

2024-03-22 13:51 UTC, AleksDPass commented on api/src/pcapi/core/users/api.py
> +        db.session.rollback()
les deux propriétés n'existent pas et je suppose que tu n'impliques pas de les créer du coup je comprend que c'est des conditions que matérialise. 

- si j'écris les conditions différemment ça revient a faire deux requêtes qui sont liées à l'utilisateur que je peux coupler en une.
 Savoir s'il est invité et savoir s'il doit avoir une nouvelle nav. Ce qui est différent pour lui car ça ne dépend que de l'état de la navigation de l'utilisateur qui l'a appelé.
 - Pour l'utilisateur non invité c'est la condition sur le ff et id paire. 
 Est ce qu'écrire comme tu préconise ca ne rendrait pas la lecture encore plus complexe ?

2024-03-22 13:52 UTC, AleksDPass commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            .filter(User.email.in_(emails), User.pro_new_nav_state.has())
Ah effectivement. j'ai mal compris cette contrainte. je pensais que la nav était activé une fois la ligne dans la table est créée.

2024-03-22 14:20 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            User.query.options(joinedload(User.pro_new_nav_state))
[détail] Il ne me semble pas qu'on ait besoin de `joinedload`. Un `join(User.pro_new_nav_state)` suffira, je pense ?

2024-03-22 14:20 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            emails.append(data["email"])
[détail] J'ai l'impression qu'on s'embête un peu pour rien. :)

```suggestion
        emails = ["user1@example.com", "user2@example.com"]
        for email in emails:
            client.post("/v2/users/signup/pro", json=data | {"email": email})
```

2024-03-22 14:20 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +        pro_new_nav_state = User.query.filter_by(email=invited_email).first().pro_new_nav_state
[détail] Il n'y a qu'un seul utilisateur avec cet e-mail. `first()` fonctionne aussi, évidemment, mais le lecteur pourrait se demander pourquoi on n'utilise pas `one()` : 

```suggestion
        pro_new_nav_state = User.query.filter_by(email=invited_email).one().pro_new_nav_state
```

2024-03-22 14:20 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +        assert pro_new_nav_state is not None
Ici on teste juste qu'on a un objet `UserProNewNavState`, mais on ne teste pas du tout la valeur de `eligibilityDate`. Ça manque un peu, je pense, car c'est précisément le but de cette pull request.

2024-03-25 11:15 UTC, damien-ramelet commented on api/tests/routes/pro/signup_pro_V2_test.py
> +        assert invited_user.pro_new_nav_state is None
Ça pourrait avoir sa place dans un test à part plutôt `test_that_if_inviter_user_dont_activate_new_nav_invited_user_dont_have_it` par exemple

2024-03-25 11:17 UTC, AleksDPass commented on api/tests/routes/pro/signup_pro_V2_test.py
> +        assert invited_user.pro_new_nav_state is None
ok

2024-03-25 12:13 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            user_inviter = user
[question] J'ai du mal à lire ce test. Si on cherche simplement à créer un utilisateur invit**ant**, pourquoi ne pas utiliser `UserFactory` ? Là on créé un utilisateur via un POST, on renomme une variable, etc. ça me semble compliqué à lire et je ne suis pas sûr de comprendre l'objet du test.

Je verrais plutôt 2 tests distincts : 

```python
def test_invitee_inherits_from_inviter():
    inviter_with_new_nav = UserProNewNavStateFactory(newNavDate=datetime.datetime.utcnow()).user
    invitation_with_new_nav = OffererInvitationFactory(user=inviter_with_new_nav)
    inviter_with_old_nav = UserProNewNavStateFactory(newNavDate=None).user
    invitation_with_old_nav = ...

    client.post(".../signup/pro", data | {"email": invitation_with_new_nav.email})
    invitee = User.query.filter_by(email=invitation_with_new_nav.email)
    assert invitee.pro_new_nav_state.newNavState

    client.post(".../signup/pro", data | {"email": invitation_with_new_old.email})
    invitee = User.query.filter_by(email=invitation_with_old_nav.email)
    assert invitee.pro_new_nav_state.newNavState is None


@override_features(WIP_....=True)
def test_uninvited_user_has_50_50_chance_of_old_nav():  # le nom n'est pas formidable, mais c'est l'idée ! :)
    client.post(".../signup/pro", data | {"email": "test1@example.com"})
    user1 = User.query.filter_by(...)
    assert user.pro_new_nav_state.newNavState is (user1.id % 2 == 0)

    client.post(".../signup/pro", data | {"email": "test2@example.com"})
    user2 = ...
    assert user.pro_new_nav_state.newNavState is (user2.id % 2 == 0)
```

Qu'en penses-tu ?

2024-03-25 12:27 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            user_inviter = user
Un autre piste, ce serait de déléguer toute la logique dans une fonction distincte `_create_user_pro_new_nav_state(user)`. Elle serait plus facile à unit-tester, puisqu'on pourrait simplement passer un objet `User` dont on contrôle l'identifiant.

Après réflexion, je pense que c'est la meilleure piste (et ça allégerait un peu la fonction `create_pro_user`).

2024-03-25 13:01 UTC, AleksDPass commented on api/src/pcapi/core/users/api.py
> +                return new_pro_user
effectivement il y'a peut surement une manière de mieux écrire les conditions. Mais je veux éviter d'avoir des lignes dans la table UserProNewNavState avec des colonnes eligibilityDate et NewNavDate en None ce qui ne serait pas cohérent avec l'utilisation qu'on a déjà de cette table.

2024-03-25 13:53 UTC, AleksDPass commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            user_inviter = user
je pense effectivement que c'est mieux de séparer les deux cas de test pour rendre ça plus lisible

2024-03-25 14:16 UTC, AleksDPass commented on api/src/pcapi/core/users/api.py
> +        db.session.rollback()
on a un souci sur l'existence de l'email. J'ai fait un check pour eviter de flush dans ce cas au lieu de rattraper l'erreur.  ça rajoute une requête sur la bd mais ça évite de gérer l'exception

2024-03-25 14:20 UTC, AleksDPass commented
J'ai scindé les test pour la création des utilisateurs et des tests et fait une vérification sur l'user pour eviter le rattrapage des exceptions. J'évite également l'insertion des lignes dans ProNewNavState. Concernant le faite que ce sont des modifs temporaire à la sortie du FF on aura qu'à supprimer le block en dessous de la vérification de l'utilisateur et ça sera bon puisque je front ne demandera même pas si l'utilisateur a cette navigation, tout sera dans la nouvelle.

2024-03-25 16:39 UTC, dbaty commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            .filter(User.email.in_(emails))
[détail] cette ligne est inutile, il n'y a pas d'autre utilisateur en base de données, à ce moment-là du test.

2024-03-25 16:39 UTC, dbaty commented on api/src/pcapi/core/users/api.py
> +    if not user_by_email:
[discussion] Je trouve ça bizarre. On vérifie... mais on continue quand même en traitant **partiellement** la demande, en espérant que la suite du code va lever une erreur. Je trouverais plus propre de faire la vérification avant de créer un nouvel objet `User` (avant la ligne 830) et de lever une erreur spécifique.

2024-03-26 00:48 UTC, AleksDPass commented on api/src/pcapi/core/users/api.py
> +    if not user_by_email:
Oui, j'ai trouvé ça curieux au début. Cependant, ça casse le test test_when_email_is_already_used qui vu comment il est fait voudrais un gestion "silencieuse" de cette erreur.

2024-03-26 00:50 UTC, AleksDPass commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            .filter(User.email.in_(emails))
Surement. Mais c'est préférable de le faire ainsi pour garder une "homogénéïté" du test. On requête vraiment que ce qu'on crée. C'est plus robuste au cas où un autre test "polu" la base

2024-03-26 08:04 UTC, AleksDPass commented on api/tests/routes/pro/signup_pro_V2_test.py
> +            .filter(User.email.in_(emails))
ok

2024-03-26 08:16 UTC, mageoffray commented on api/src/pcapi/core/users/api.py
> +    if not user_by_email:
Tu peux t'inspirer de ce qui est fait dans le fonction `create_account` : 
```
if users_repository.find_user_by_email(email):
    raise exceptions.UserAlreadyExistsException()
```
Tu lèves une erreur spécifique qui est ensuite catch au niveau de la route

2024-03-26 13:14 UTC, mageoffray commented on api/src/pcapi/core/users/api.py
> +        print("User already exists")
Tu peux supprimer ce print

2024-03-26 13:36 UTC, mageoffray approved these changes

2024-03-26 13:36 UTC, mageoffray commented on api/src/pcapi/core/users/api.py
> +        )
Ici j'ai l'impression que veux juste récupérer le UserProNewNavState, on a une raison de chercher la userInvitation qu'on viens de récupérer ? 

Je pense que tu peux simplifier en 
```
inviter_nav_state = users_models.UserProNewNavState.query.filter_by(user_id=is_invited.userId).one_or_none() 
```

2024-03-26 13:36 UTC, mageoffray commented on api/src/pcapi/core/users/api.py
> +            if inviter_pro_new_nav_state.newNavDate is not None:
(détail) 
Je trouve ça plus lisible de l'avoir en une ligne et désindenter la suite : 
```
if inviter_pro_new_nav_state and inviter_pro_new_nav_state.newNavDate is not None:
```

2024-03-26 13:39 UTC, mageoffray reviewed
J'approve la partie technique, le laisse damien r valider le fonctionnel

2024-03-28 09:30 UTC, damien-ramelet approved these changes

2024-03-28 11:49 UTC, merged