(PC-10632) api: Sendinblue Pro Attributes [WIP]
pass-culture/pass-culture-main pull request #1154
Opened 2022-01-25 10:40 UTC by prouzet

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10632

## But de la pull request

Envoi des attributs PRO vers Sendinblue de la même manière que les attributs des jeunes.
Les attributs à envoyer pour les adresses email des pros ont été définis par l'équipe marketing :
https://www.notion.so/passcultureapp/Remont-e-des-attributs-pros-249c68e861f64658845768deb0c161a7

##  Implémentation

Cette PR contient actuellement la première partie de l'implémentation du ticket : la récupération des attributs jusqu'à leur envoi vers Sendinblue.
Pour l'instant la mise à jour n'est faite que lorsque `update_external_user` est appelé ; ces appels ont été placés en fonction de la mise à jour des attributs USER, mais seront à compléter par un appel spécifique pour la mise à jour des attributs PRO (pas forcément à partir d'un `User`, ce peut être à partir d'un lieu `Venue`, pour mettre à jour à partir d'un `bookingEmail`.

##  Informations supplémentaires

Les nouveaux attributs ont été créés dans le compte de test Sendinblue.

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
    - Branche : `pc-XXX-whatever-describe-the-branch`
    - PR : `(PC-XXX) Description rapide de l' US`
    - Commit(s) : `[PC-XXX] description rapide du ticket`
- [x] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-01-26 10:01 UTC, dupush requested changes
La construction de l'objet ProAttributes pourrait être optimisée pour gagner en lisibilité.
D'une manière générale, essayer de limiter le code dans le __init__.py

2022-01-26 10:01 UTC, dupush commented on api/src/pcapi/core/users/external/__init__.py
> +        and db.session.query(
On pourrait extraire ces requêtes dans les repository dédiés aux models.
Ca allègerait le code ici et ça rajouterai de la lisbilité avec une fonction bien nommée.

2022-01-26 15:06 UTC, prouzet commented on api/tests/core/users/external/external_pro_test.py
> +def test_update_external_pro_user_attributes(
Après discussion, on garde tel quel

2022-02-02 14:44 UTC, dupush reviewed
Ok pour tout ce qui est l'asynchronisme.

2022-02-02 14:44 UTC, dupush commented on api/src/pcapi/tasks/cloud_task.py
> +def enqueue_internal_task(queue, path, payload, deduplicate: bool = False, delayed_seconds: int = 0):
praise: vu l'ajout de la dé-duplication et du délai. Merci Monsieur 🎓

2022-02-02 15:50 UTC, dupush approved these changes

2022-02-03 14:22 UTC, merged