(PC-29208)[BO] feat: Pro Support - status pro account suspended
pass-culture/pass-culture-main pull request #11771
Opened 2024-04-15 08:20 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29208

EN COURS DE VERIFICATION WIP

2024-04-15 08:42 UTC, prouzet requested changes
Pourquoi un nouvel état de validation ?
Je ne vois même pas à quel moment tu l'affectes...

Ce n'est pas du tout ma compréhension du ticket.

Il est bien précisé : « Lorsqu’un compte pro rattaché a une structure a été suspendu ». C'est une action déjà possible par le bouton « Suspendre le compte », depuis la page de détails de l'utilisateur. Ensuite, le tag existe déjà, il suffit de reprendre la même condition pour afficher le tag...

2024-04-15 08:47 UTC, Vencespass reviewed
Pas fonctionnel pour l'instant...

2024-04-15 08:47 UTC, Vencespass commented on api/src/pcapi/alembic/versions/sql/schema_init.sql
>  );
Ce n'est pas à toi d'éditer le schema_init.sql, ta modification de l'enum concernée se chargera de le faire toute seule. D'ailleurs un dev n'a jamais à toucher à ce fichier

2024-04-15 08:47 UTC, Vencespass commented on api/src/pcapi/models/validation_status_mixin.py
> +    SUSPENDED = "SUSPENDED"
Un nouvel état n'était pas demandé, cf le ticket + ce que dit Patrick

2024-04-15 12:25 UTC, borisLeBonPro commented
EN COURS DE VERIFICATION

2024-04-15 12:43 UTC, borisLeBonPro commented
EN COURS DE VERIFICATION...

2024-04-15 14:42 UTC, borisLeBonPro commented
test

2024-04-15 16:05 UTC, Vencespass approved these changes

2024-04-16 06:40 UTC, prouzet approved these changes

2024-04-16 07:47 UTC, merged