(PC-29404)[BO] feat: feature flag are now visible in read only for authenticate user without permission
pass-culture/pass-culture-main pull request #12068
Opened 2024-05-02 08:21 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29404

2024-05-03 09:42 UTC, prouzet requested changes
En testant je vois deux problèmes majeurs si on n'a pas de droits : 
- le lien n'apparaît pas dans le menu, donc la page n'est accessible qu'en connaissant l'URL ;
- les _switches_ sont tous désactivés, or le but du ticket est justement de visualiser l'état (actif ou non) des _feature flags_ !

2024-05-06 07:02 UTC, borisLeBonPro commented
<img width="1512" alt="Capture d’écran 2024-05-06 à 09 02 45" src="https://github.com/pass-culture/pass-culture-main/assets/114911174/12d786ac-8d9c-48cc-afc0-6f0d37d0f587">

correction

2024-05-07 14:30 UTC, borisLeBonPro commented
<img width="1512" alt="Capture d’écran 2024-05-07 à 16 30 22" src="https://github.com/pass-culture/pass-culture-main/assets/114911174/a35b3abf-6587-47e1-8319-08b3a59b5818">

2024-05-13 12:17 UTC, prouzet approved these changes
Je valide pour retirer l'état « Changes requested  », mais avec des commentaires ci-dessous

2024-05-13 12:17 UTC, prouzet commented on api/tests/routes/backoffice/helpers/get.py
>  from .unauthorized import UnauthorizedHelperBase
On se retrouve avec deux classes importées du même fichier mais pas de la même manière, ce n'est pas cohérent

2024-05-13 12:17 UTC, prouzet commented on api/tests/routes/backoffice/helpers/unauthorized.py
> +class UnauthorizedHelperWithoutPermission(base.BaseHelper, metaclass=abc.ABCMeta):
Le nom complique la compréhension, je serais pour simplifier, par exemple `AuthenticatedHelperBase` ou `UnauthenticatedHelperBase`. Je préfère la première, mais la seconde est plus cohérente avec `UnauthorizedHelper` (même si je préférerais `AuthorizedHelper`).

2024-05-13 12:29 UTC, borisLeBonPro commented
J'ai modifié @prouzet , 
Comme j'imagine que tu ne peux validé ce qui est validé, je te laisserai me dire en commentaire si c'est bon. :)

2024-05-13 13:53 UTC, prouzet approved these changes

2024-05-14 14:01 UTC, merged