(PC-29485)[API] feat: adage iframe: fill two new playlists' code
pass-culture/pass-culture-main pull request #12085
Opened 2024-05-02 14:56 UTC by jeremieb-pass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-29485

Ajout du code (complet) pour les deux nouvelles routes d'API (iframe adage).
Pour rappel : une précédente PR avait ajouté ces fonctions dans le seul but d'exposer rapidement une interface API.

2024-05-13 13:50 UTC, xordoquy commented on api/src/pcapi/routes/adage_iframe/playlists.py
> +    )
Est-ce que l'on peut aussi prévoir le cas d'augmentation du rayon en cas de playlist à moins de 10 éléments ?

2024-05-13 13:50 UTC, xordoquy commented on api/src/pcapi/connectors/big_query/queries/adage_playlists.py
> +            `{settings.BIG_QUERY_TABLE_BASENAME}.adage_home_playlist_any_new_offers`
J'ai contacté la data pour avoir le nom définitif

2024-05-13 13:52 UTC, xordoquy requested changes

2024-05-13 13:52 UTC, xordoquy commented on api/src/pcapi/routes/adage_iframe/playlists.py
>  @blueprint.adage_iframe.route("/playlists/local-offerers", methods=["GET"])
Il était question d'ajouter une autre route, pas de modifier les local offerers non ?

2024-05-14 08:17 UTC, jeremieb-pass commented
Désolé, j'ai embarqué des changements d'une autre branche ici. Je nettoie tout ça.

2024-05-16 16:22 UTC, xordoquy approved these changes

2024-05-16 17:08 UTC, merged