(BSR)[PRO] test: add cookie banner tests that were not yet migrated t…
pass-culture/pass-culture-main pull request #12765
Opened 2024-06-17 13:28 UTC by scolson-pass

…o cucumber/testing-library

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-XXXXX

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-06-17 15:23 UTC, ncanseco-pass requested changes
deux scénarios à merger (ou le premier à supprimer?) et deux typos

2024-06-17 15:23 UTC, ncanseco-pass commented on pro/cypress/e2e/features/cookieBanner.feature
> +    Then The cookie banner should be displayed
Un scénario pour tester ça c'est overkill pour moi, je le mettrais au début du scénario 3 par exemple ("The user can accept all"), puisque de fait c'est un prérequis pour valider les choix proposés

2024-06-17 15:23 UTC, ncanseco-pass commented on pro/cypress/e2e/features/cookieBanner.feature
> +  Scenario: The user can accept all
doublon avec le suivant?

2024-06-17 15:23 UTC, ncanseco-pass commented on pro/cypress/e2e/step-definitions/cookieBanner.cy.ts
> +When('I open the chose cookies option', () => {
```suggestion
When('I open the choose cookies option', () => {
```

2024-06-17 15:23 UTC, ncanseco-pass commented on pro/cypress/e2e/step-definitions/cookieBanner.cy.ts
> +When('I save my choice', () => {
```suggestion
When('I save my choices', () => {
```

2024-06-17 15:55 UTC, ncanseco-pass approved these changes

2024-06-18 07:49 UTC, AmineLouveau commented on pro/cypress/e2e/features/cookieBanner.feature
> +  Scenario: The cookie banner should be displayed on cookie deletion
Je ne sais pas comment se comporte `visit`, mais si la page est complètement rechargé, ça voudrait dire que le test n'est pas "utile", vu que c'est le comportement de tous les tests.

Il faudrait faire un test en cliquant sur un lien interne, pour que la navigation passe par le router react. On doit tester l'affichage de la banière si l'utilisateur navigue dans l'app, sans recharcher sa page.

2024-06-18 08:52 UTC, AmineLouveau approved these changes

2024-06-18 09:50 UTC, merged