[PC-12524](API) Add Pre and Post Deployment Branches for migrations
pass-culture/pass-culture-main pull request #1302
Opened 2022-02-07 16:01 UTC by akarki16

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

Besoin
(Le besoin avait déjà été repéré lors de l'audit réalisé en septembre-octobre 2020, cf. [Stratégie de migrations](https://www.notion.so/Strat-gie-de-migration-1a137f4eb18a4b589079eb1d6740e939). La présente page reprend et complète le document écrit à l'époque.)

Actuellement, les migrations sont jouées exclusivement en début de déploiement, *avant* le déploiement du code. Pour ajouter une colonne pour laquelle on souhaite une contrainte NOT NULL, il faut donc faire 2 déploiements :

Le premier déploiement ajoute la colonne sans la contrainte.

Le second déploiement ajoute la contrainte.

Il est donc nécessaire de faire le suivi de ces ajouts de colonne sur 2 déploiements à suivre. Il est probable que l’ajout de contrainte NOT NULL est souvent oublié à cause de cette complication.

Nous suggérons de mettre en place un système de migrations en plusieurs phases :

application des migrations “pré-déploiement” (en l’occurrence ajout des colonnes sans contrainte NOT NULL) ;

déploiement du code ;

application des migrations “post-déploiement” (en l’occurrence remplissage des colonnes ajoutées, si nécessaire, et ajout des contraintes NOT NULL).

En bonus, on peut même prévoir un 3ème type de migration : les migrations "irréversibles" car destructives : suppression d'une colonne ou suppression d'une table. Une migration "irréversible" embarquée dans la version 10 du backend ne serait jouée que lors du déploiement de la version 11.

Un peu d’outillage est nécessaire pour mettre en place ce système, mais il facilite grandement le travail de développement.

Etapes d'implémentation
Trouver un moyen de marquer les migrations comme "pré", "post" ou "irréversible".

Trouver une commande (ou écrire un utilitaire) permettant de lancer les migrations par type : soit les "pré", soit les "post", soit les irréversibles.

Adapter le déroulement global du déploiement pour :
    1. Appliquer les migrations irréversibles de la version N-1.
    2. Appliquer les migrations pré-déploiement de la version N.
    3. Déployer le code de la version N.
    4. Appliquer les migrations post-déploiement de la version N.

 

Cf Chantier tech  https://www.notion.so/passcultureapp/S-paration-des-migrations-en-pr-et-post-d-ploiement-5a6760f405d643e78f3799c7803a98c0

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
- [x] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)

2022-02-09 10:19 UTC, xordoquy reviewed
Est-ce qu'il n'y a pas un bout de doc à mettre à jour également ?

2022-02-09 10:20 UTC, xordoquy commented
Manifestement, il faut aussi modifier le fichier CircleCI pour correctement jouer les migrations

2022-02-09 10:21 UTC, xordoquy requested changes
Manifestement, il faut aussi modifier le fichier CircleCI pour correctement jouer les migrations lors des tests

2022-02-09 10:32 UTC, akarki16 commented
> Manifestement, il faut aussi modifier le fichier CircleCI pour correctement jouer les migrations lors des tests

@xordoquy  : du coup je supprime la commande de vérification des heads multiples ?

2022-02-09 10:33 UTC, akarki16 commented
> Est-ce qu'il n'y a pas un bout de doc à mettre à jour également ?

Ah oui ! Je m'en charge.

2022-02-09 11:00 UTC, xordoquy commented
> @xordoquy : du coup je supprime la commande de vérification des heads multiples ?

il faudrait surtout regarder si on a moyen de s'assurer que chaque branche n'a bien qu'une seule head

2022-02-09 11:31 UTC, akarki16 commented
> > @xordoquy : du coup je supprime la commande de vérification des heads multiples ?
> 
> il faudrait surtout regarder si on a moyen de s'assurer que chaque branche n'a bien qu'une seule head

```bash 
LINE_COUNT=$(wc -l <<< "$(alembic heads)")
if [${LINE_COUNT} -ne 2 ]; then echo "There must be two heads";exit 1;fi
```

Ce qui permets de compter les `heads` (on devrait en avoir deux : pre & post) et ensuite de faire un `exit 1` si jamais c'est différent de 2.

2022-02-18 08:42 UTC, xordoquy approved these changes

2022-02-18 09:02 UTC, merged