(PC-30509)[BO] feat: Cancellation reason for booking and collective booking display user informations if done by BOuser or pro
pass-culture/pass-culture-main pull request #13088
Opened 2024-07-03 16:08 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30509

2024-07-04 08:54 UTC, Vencespass requested changes

2024-07-04 08:54 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
> -{% import "components/links.html" as links %}
Pas nécessaire de le bouger, en plus ça ne respect plus l'ordre alphabétique

2024-07-04 08:54 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> -
Pas nécessaire

2024-07-04 08:54 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
> +        author=current_user,
Donc l'auteur, c'est toujours celui qui est en train de lire la page.
Donc ça veut dire qu'on affiche toujours l'utilisateur actuel comme l'auteur de l'annulation.
Et du coup, c'est une information fausse. Pareil pour le collectif.

2024-07-04 08:56 UTC, Vencespass commented
Request changes car tu n'affiches pas ce qui est demandé dans le ticket, tu affiches seulement le nom de l'utilisateur actuel.

2024-07-10 09:44 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
> +        author=current_user,
je cloture le commentaire étant donné les nombreux changements

2024-07-10 12:39 UTC, mageoffray commented on api/src/pcapi/alembic/versions/20240710T090128_711c0959f111_add_cancellationauthor_to_booking.py
> +    )
Attention, la création de foreign_key va prendre un court lock sur la table booking et la table user, deux tables très utilisées. Il y a de grande chance que nous n'arrivons pas à prendre ces locks dans le temps imparti par notre lock timeout. 
Si la création de la foreign_key échoue, nous serons un peu bloqué, nous essayerons de rejouer la migration mais la colonne étant déjà créée nous échouerons à la création de la colonne. 

Pour plus de simplicité je te recommanderais de ne pas créer cette foreign key dans la même migration que la création de la colonne. 
Tu peux t'inspirer de la création de cette foreign key : [offer_offererAddressId_fkey](https://github.com/pass-culture/pass-culture-main/commit/05539c3f07b10505d960c1b3b41ebacabfce4075) : 
- Migration pré -> Création de la colonne 
- 2eme migration pré -> Création de la foreign key avec postgres_not_valid
- migration post -> validation de la foreign key

Si j'avais a faire ce développement, je m'en occuperais en 2 fois, une première PR sur les résevations individuelle et une deux PR sur les réservations collectives

2024-07-11 11:55 UTC, borisLeBonPro commented on api/src/pcapi/alembic/versions/20240710T090128_711c0959f111_add_cancellationauthor_to_booking.py
> +    )
sur cette PR sera fait les 4 premieres migration, je ferai la confirmation sur la prochaine du coup

2024-07-12 15:41 UTC, Meewan commented on api/src/pcapi/alembic/versions/20240710T090128_711c0959f111_add_cancellationauthor_to_booking.py
> +    )
add column prend deja un lock exclusif sur la table booking, je doute que cette migration passe bien en prod.

Il pourrait être interessant d'ajouter la colonne manuellement avant la MEP et de désactiver la migration en prod 

(pour collective_booking ce n'est pas un probleme elle est beaucoup moins active)

2024-07-12 16:05 UTC, Meewan commented on api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
> +            booking, bookings_models.BookingCancellationReasons(form.reason.data), author_id=current_user.id
autant tout passer en nommé

2024-07-12 16:05 UTC, Meewan commented on api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
> +                author_id=current_user.id,
idem

2024-07-12 16:05 UTC, Meewan commented on api/src/pcapi/routes/backoffice/bookings/individual_bookings_blueprint.py
> +            booking, bookings_models.BookingCancellationReasons(form.reason.data), author_id=current_user.id
Si c'est pour faire une lambda sur plusieurs ligne autant faire une fonction nomée a l'interrieur de la fonction. + autant tout passer en nommé

2024-07-12 16:05 UTC, Meewan commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
```suggestion
    if author and reason in [
        bookings_models.BookingCancellationReasons.OFFERER,
        bookings_models.BookingCancellationReasons.BACKOFFICE,
        educational_models.CollectiveBookingCancellationReasons.OFFERER,
        educational_models.CollectiveBookingCancellationReasons.BACKOFFICE,
    ]:
        return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
```

2024-07-12 16:05 UTC, Meewan commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_author_booking_cancellation(booking.cancellationAuthor) | safe }}
attention c'est pas safe si le nom de l'author contient du html/js malicieux il peut faire une attaque.

2024-07-15 08:35 UTC, borisLeBonPro commented on api/src/pcapi/core/bookings/api.py
> +    author_id: int | None = None,
c'est à dire que ca fait une ligne vachement longue, mon IDE me balance : 
`PEP 8: E501 line too long (141 > 120 characters)`

2024-07-15 08:47 UTC, borisLeBonPro commented on api/src/pcapi/core/bookings/repository.py
> +            .join(Booking, User.userBookings)
Alors j'ai pas compris pourquoi ce commentaire montre que cela n'a pas été fait car quand je vérifie autant sur mon code que sur la PR, c'est justement ce qui est fait. en tout cas pas d'inquiétude c'est fait déjà.

2024-07-15 09:11 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +                assert "Fraude" in extra_data
Tu peux aussi mettre les résultats dans le parametrize, je pense

2024-07-15 09:11 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +    def test_list_cancelled_booking_informations(self, authenticated_client, legit_user, cancellation_reason):
```suggestion
    def test_list_cancelled_booking_information(self, authenticated_client, legit_user, cancellation_reason):
```
Information est un indénombrable, en anglais

2024-07-15 09:11 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +    def test_list_cancelled_booking_informations(self, authenticated_client, legit_user, cancellation_reason):
Par ailleurs, ton test n'est pas très bien placé, entre des tests de filtre; tu peux le mettre en fin de classe.

2024-07-15 09:11 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
> -{% import "components/links.html" as links %}
Ping

2024-07-15 09:11 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
>      app.jinja_env.filters["format_booking_cancellation_reason"] = format_booking_cancellation_reason
Par uniformité, `format_booking_cancellation_author`...

2024-07-15 09:11 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
ça devait être l'adresse mail pour le pro, non ?

2024-07-15 09:14 UTC, Vencespass commented on api/src/pcapi/core/bookings/models.py
> +    deposit: Mapped["finance_models.Deposit"] = relationship(
Un autre commit, pas un autre ticket

2024-07-15 09:39 UTC, borisLeBonPro commented on api/src/pcapi/core/bookings/models.py
> +            self.cancellationAuthorId = author_id
question : ok mais en soit, quel est la différence entre mettre None et le laisser ainsi ( la colonne sera None de toutes façon )

2024-07-15 09:43 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_author_booking_cancellation(booking.cancellationAuthor) | safe }}
Si je ne fais pas safe, le resultat avec le filter sera ainsi: 
<img width="636" alt="Capture d’écran 2024-07-15 à 11 43 43" src="https://github.com/user-attachments/assets/0a72f3be-4a57-4ded-baa2-29b6b8069941">

2024-07-15 09:45 UTC, Meewan commented on api/src/pcapi/core/bookings/models.py
> +    deposit: Mapped["finance_models.Deposit"] = relationship(
alors en fait je l'ai pris a l'envers et il faut juste pas le faire (je penseais que Boris rajoutait le |None alors qu'il l'enlever) Le |None est parfaitement justifié ici.

2024-07-15 10:08 UTC, borisLeBonPro commented on api/tests/routes/backoffice/individual_bookings_test.py
> +                assert "Fraude" in extra_data
Tu es sur? Personnellement je trouve cela tellement pas lisible ainsi : 
on mettrait : 
```
@pytest.mark.parametrize(
    "cancellation_reason, expected_text",
    [
        (bookings_models.BookingCancellationReasons.BACKOFFICE, "Annulée sur le backoffice par"),
        (bookings_models.BookingCancellationReasons.OFFERER, "Annulée par l'acteur culturel par"),
        (bookings_models.BookingCancellationReasons.FRAUD, "Fraude"),
    ],
)
```
(bon ca ok mais ensuite ca donnerai quelque chose comme )

```
if expected_text == "Fraude":
            assert expected_text in extra_data.text
        else:
            assert f"{expected_text} {legit_user.full_name}" in extra_data.text
``` 

ce qui réduit fortement la lisibilité non?

2024-07-15 10:12 UTC, borisLeBonPro commented on api/tests/routes/backoffice/individual_bookings_test.py
> +        for extra_data in data_accordeon:
(voir mon commentaire d'apres par rapport au parametrize )

2024-07-15 10:16 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +        for extra_data in data_accordeon:
ça n'a pas de lien avec le parametrize, puisque tu n'as toujours qu'une seule donnée à tester

2024-07-15 10:17 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +                assert "Fraude" in extra_data
Certes... Je crois avoir déjà eu ce pb qque part, je vais voir si je retrouve comment j'avais fait

2024-07-15 10:58 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/templates/individual_bookings/list.html
> -{% import "components/links.html" as links %}
hmmm je l'avais remis ce truc... étrange ...

2024-07-15 11:12 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
plus maintenant, tout est l'utilisateur BO

2024-07-15 11:22 UTC, borisLeBonPro commented
j'ai push mes changements afin de travailler sur autre chose, néanmoins j'ai laissé ouvert les commentaires que je n'ai pas fait ( si questions j'ai répondu etc... )

2024-07-15 12:13 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
Comment ça tout est l'utilisateur BO ? Dans ce cas, pour quoi écrit-on `Annulée par l'AC par Utilisateur Quelconque` dans le cas où l'annulation est par un PRO ?

2024-07-15 13:18 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
alors on a vue pendant tes vacances avec Raphael et Victor et on ne peut tout simplement pas faire le lien avec l'AC car l'AC n'annule tout simplement pas un booking lui meme, c'est impossible, du coup seul l'utilisateur BO peut le faire ( à la demande de l'AC ) du coup quand c'est par un pro c'est plus "a sa demande"

2024-07-15 13:37 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return f"par <a href='{build_backoffice_public_account_link(author.id)}'>{author.full_name}</a>"
... je peux faire ca ...

2024-07-15 13:54 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_author_booking_cancellation(booking.cancellationAuthor) | safe }}
vue avec Raphael

2024-07-15 13:55 UTC, borisLeBonPro commented
A FAIRE UNE FOIS REVIEWED -> ajouter la colonne en staging et prod manuellement ( d'apres @Meewan )

2024-07-16 09:18 UTC, borisLeBonPro commented
vue apres grooming, j'ai encore des choses a modifié ( modification du métier )

2024-07-18 12:53 UTC, Meewan commented on api/src/pcapi/alembic/versions/20240716T150036_5f46232cb72f_add_cancellationauthor_for_booking.py
> +    op.add_column("booking", sa.Column("cancellationAuthorId", sa.BigInteger(), nullable=True))
```suggestion
    if not settings.IS_PROD:
        op.add_column("booking", sa.Column("cancellationAuthorId", sa.BigInteger(), nullable=True))
```

Je te l'ai deja dit plusieurs fois en commentaire et sur slack, il faut désactiver cette migration en prod, on la jouera manuellement

2024-07-18 12:53 UTC, Meewan commented on api/src/pcapi/alembic/versions/20240716T150303_ebbed0db4e99_add_cancellationauthor_foreign_key_for_booking.py
> +    )
```suggestion
    if not settings.IS_PROD:
        op.create_foreign_key(
        "booking_cancellation_author_fk",
        "booking",
        "user",
        ["cancellationAuthorId"],
        ["id"],
        postgresql_not_valid=True,
    )
```

idem

2024-07-18 12:53 UTC, Meewan commented on api/src/pcapi/core/bookings/api.py
> +            booking, reason, cancel_even_if_used, raise_if_error, one_side_cancellation, author_id
les passer en nommés serait pertinent pour rendre la fonction plus lisible

2024-07-23 19:09 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +        ).format(author_id=author.id, full_name=author.full_name)
j'ai une erreur de sécurité si je le transforme ainsi

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/core/bookings/models.py
> +        author_id: int | None = None,
Pourquoi on n'a pas forcément d'auteur, déjà ?

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/core/bookings/models.py
> +        "User", foreign_keys=[cancellationAuthorId], backref="cancellationAuthorBookings"
```suggestion
        "User", foreign_keys=[cancellationAuthorId], backref="cancelledBookings"
```

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/core/educational/models.py
> +        "User", foreign_keys=[cancellationAuthorId], backref="cancellationAuthorCollectiveBookings"
```suggestion
        "User", foreign_keys=[cancellationAuthorId], backref="cancelledCollectiveBookings"
```

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/core/educational/models.py
> +        author_id: int | None = None,
Même question

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            url=url_for("backoffice_web.public_accounts.get_public_account", user_id=author.id),
get_public_account ??

2024-07-25 16:40 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_booking_cancellation_author(booking.cancellationAuthor) }}
Tu peux juste mettre `booking`, et ensuite tu fais un `format_booking_cancellation` qui gère toute la string

2024-07-25 16:40 UTC, Vencespass commented on api/tests/routes/backoffice/collective_bookings_test.py
> +        data_accordeon = html_parser.extract(response.data, tag="tr", class_="collapse accordion-collapse")[0]
```suggestion
        extra_data = html_parser.extract(response.data, tag="tr", class_="collapse accordion-collapse")[0]
```

2024-07-25 16:40 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +            assert link in str(html_parser.get_soup(response.data))
On ne vérifie pas forcément les liens dans le BO

2024-07-26 07:54 UTC, borisLeBonPro commented on api/src/pcapi/core/bookings/models.py
> +        author_id: int | None = None,
Parce que `cancel_booking` est utilisé par des fonctions qui sont utilisé par des fonctions qui elle meme sont utilisé etc etc... et que dans ces fonctions, il y a des crons qui font les truc automatiquement et qui ne sont pas des auteurs.

2024-07-26 07:54 UTC, borisLeBonPro commented on api/src/pcapi/core/educational/models.py
> +        author_id: int | None = None,
Parce que `cancel_booking` est utilisé par des fonctions qui sont utilisé par des fonctions qui elle meme sont utilisé etc etc... et que dans ces fonctions, il y a des crons qui font les truc automatiquement et qui ne sont pas des auteurs.

2024-07-26 08:19 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            url=url_for("backoffice_web.public_accounts.get_public_account", user_id=author.id),
Et bien oui, le lien est supposé nous envoyer vers l'utilisateur en question

2024-07-26 08:25 UTC, borisLeBonPro commented on api/tests/routes/backoffice/individual_bookings_test.py
> +            assert link in str(html_parser.get_soup(response.data))
409 Conflit  => c'est a dire que c'est @aminepass qui m'a demandé de le faire.

2024-07-26 08:37 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_booking_cancellation_author(booking.cancellationAuthor) }}
format_booking_cancellation_reason est utilisé par plein de chose qui ne demande pas d'auteur. Je pense qu'il vaut mieux laisser les deux fonctions ainsi.

2024-07-26 08:47 UTC, Vencespass commented on api/src/pcapi/core/bookings/models.py
> +        author_id: int | None = None,
ok !

2024-07-26 08:48 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            url=url_for("backoffice_web.public_accounts.get_public_account", user_id=author.id),
Public account, c'est le profil d'un jeune...

2024-07-26 08:49 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/components/bookings/extra_row.html
> +                  {{ booking.cancellationReason | format_booking_cancellation_author(booking.cancellationAuthor) }}
C'est pas ce que je dis.
Tu peux faire une fonction qui va prendre un booking, et qui va afficher la raison formatée, et qui va en plus mettre l'info de l'auteur dans certains cas

2024-07-26 08:50 UTC, Vencespass commented on api/tests/routes/backoffice/individual_bookings_test.py
> +            assert link in str(html_parser.get_soup(response.data))
Ok

2024-07-30 08:54 UTC, Meewan commented on api/src/pcapi/alembic/versions/20240716T150036_5f46232cb72f_add_cancellationauthor_for_booking.py
> +    op.drop_column("booking", "cancellationAuthorId")
a désactiver pour la prod

2024-07-30 08:54 UTC, Meewan commented on api/src/pcapi/alembic/versions/20240716T150303_ebbed0db4e99_add_cancellationauthor_foreign_key_for_booking.py
> +    op.drop_constraint("booking_cancellation_author_fk", "booking", type_="foreignkey")
a désactiver pour la prod

2024-07-30 08:54 UTC, Meewan commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
```suggestion
def format_booking_cancellation(
    reason: bookings_models.BookingCancellationReasons | educational_models.CollectiveBookingCancellationReasons | None,
    author: users_models.User | None,
) -> str:
    match reason:
        case (
            bookings_models.BookingCancellationReasons.OFFERER
            | educational_models.CollectiveBookingCancellationReasons.OFFERER
        ):
            return "Annulée par l'acteur culturel"
        case (
            bookings_models.BookingCancellationReasons.BENEFICIARY
            | educational_models.CollectiveBookingCancellationReasons.BENEFICIARY
        ):
            return "Annulée par le bénéficiaire"
        case (
            bookings_models.BookingCancellationReasons.EXPIRED
            | educational_models.CollectiveBookingCancellationReasons.EXPIRED
        ):
            return "Expirée"
        case (
            bookings_models.BookingCancellationReasons.FRAUD
            | educational_models.CollectiveBookingCancellationReasons.FRAUD
        ):
            return "Fraude"
        case (
            educational_models.CollectiveBookingCancellationReasons.FINANCE_INCIDENT
            | bookings_models.BookingCancellationReasons.FINANCE_INCIDENT
        ):
            return "Incident finance"
        case (
            educational_models.CollectiveBookingCancellationReasons.BACKOFFICE
            | bookings_models.BookingCancellationReasons.BACKOFFICE
        ):
            if author:
                return Markup(
                    'Annulée sur le backoffice par <a href="{url}">{full_name}</a>'
                ).format(
                    url=url_for("backoffice_web.bo_users.get_bo_user", user_id=author.id),
                    full_name=author.full_name,
                )
            return "Annulée sur le backoffice"
        case (
            bookings_models.BookingCancellationReasons.REFUSED_BY_INSTITUTE
            | educational_models.CollectiveBookingCancellationReasons.REFUSED_BY_INSTITUTE
        ):
            return "Refusée par l'institution"
        case educational_models.CollectiveBookingCancellationReasons.REFUSED_BY_HEADMASTER:
            return "Refusée par le chef d'établissement"
        case None:
            return ""
        case _:
            return reason.value
```
1) le markup ne sert a rien si le user est None
2) je pense que c'est plus lisible de le mettre directement dans le cas.

2024-07-30 08:54 UTC, Meewan commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
pourquoi ne pas avoir simplement repris l'ancien filter en rendant le user facultatif ? ça éviterait de la duplication de code

2024-07-31 09:51 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
1. mypy n'aimait pas ne pas mettre de markup si le user n'est pas présent c'est pour ca que j'avais meme mis un markup dans ce cas. ( mais pour une raison inconnu, avec ton changement, mypy ne se trigger pas)
2. ok

2024-07-31 10:00 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
les choices_from_enum contenue dans form me semble toujours demander author, meme lorsqu'il est facultatif

2024-07-31 13:32 UTC, Vencespass approved these changes

2024-07-31 13:32 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
Si on arrive à ce cas là, c'est qu'on aura une donnée imprévue qui n'est pas forcément un enum; il serait plus sage de mettre juste `reason`, je pense

2024-07-31 13:32 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return rejection_reason
Il était mal placé ? Si c'est une erreur de manip, pense à le remettre où il était avant, ça évitera de polluer l'historique (bien que ça ne soit pas très crucial)

2024-07-31 14:00 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
mypy n'aime pas car il s'attend à avoir en retour un str

2024-07-31 14:04 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return reason.value
Certes, tant pis alors

2024-08-01 13:05 UTC, merged