(PC-30789) ci: Post a link to Slack for the deployment review
pass-culture/pass-culture-main pull request #13181
Opened 2024-07-10 12:20 UTC by francois-pass-culture

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30789

2024-07-10 12:27 UTC, mlachevre-pass requested changes

2024-07-10 12:27 UTC, mlachevre-pass commented on .github/workflows/dev_on_dispatch_release_deploy.yml
> +          slack_deploy_webhook_url: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
alors on fait en sort d'utiliser secret manager pour les secrets pour pouvoir les versionner + pouvoir les éditer, ce qui n'est pas le cas ici.

Tu peux dupliquer le job   slack-notification pour envoyer le message, ce sera plus iso avec notre gestion des secrets + avec le reste du code

2024-07-10 12:28 UTC, mlachevre-pass commented on .github/workflows/dev_on_dispatch_release_deploy.yml
> +          slack_deploy_webhook_url: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
apres si il y a une raison indispensable pour l'utilisation du webhook, passe tout de meme par la gestion via secret manager et pas par le secret github

2024-07-10 12:36 UTC, francois-pass-culture commented on .github/workflows/dev_on_dispatch_release_deploy.yml
> +          slack_deploy_webhook_url: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
- OK pour Secret Manager, je voulais éviter de passer par un tiers pour l'écriture
- Utiliser une automation plutôt que l'API de message Slack permet de modifier la mise en forme/contenu côté Slack sans repousser du code dans le repo. Pas indispensable mais quand même fort pratique.

2024-07-12 12:29 UTC, mlachevre-pass approved these changes

2024-07-12 13:18 UTC, merged