(PC-30741)[BO] feat: log_user_that_sync_in_pro_venue_pivot
pass-culture/pass-culture-main pull request #13338
Opened 2024-07-22 12:54 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-30741

2024-07-25 12:24 UTC, aminepass commented on api/src/pcapi/routes/backoffice/pivots/blueprint.py
> +            db.session.add(action_history)
je pense qu'il vaut mieux utiliser la fonction `add_action` de `pcapi.core.history.api` pour ajouter cette action. Ça sera plus cohérent avec le reste du code

2024-07-25 12:38 UTC, aminepass commented on api/src/pcapi/routes/pro/venue_providers.py
> +            payload=VenueProviderCreationPayload(
tant qu'a faire autant rajouter `provider_id=body.providerId`, `venue_id=body.venueId` et mettre `author=current_user` après `payload=…` vu que c'est l'ordre des arguments de la fonction

2024-07-25 13:31 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/pivots/blueprint.py
> +    return {"cinema_id": form.cinema_id.data, "pivot_name": name}
très interressant !

2024-07-25 15:03 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/components/history/actions.html
> +              Identifiant cinéma : {{ action.extraData["cinema_id"] }}
```suggestion
              Identifiant du cinéma : {{ action.extraData["cinema_id"] }}
```

2024-07-25 15:03 UTC, Vencespass commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
Ce serait top si tu pouvais trouver un moyen d'avoir les "beaux noms" à l'affichage dans le BO, du genre `Boost` et pas `boost`, ou `Allociné`, et pas `allocine`

2024-07-25 15:03 UTC, Vencespass commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
(ça ne changerait pas ce assert pour autant)

2024-07-25 15:06 UTC, borisLeBonPro commented on api/src/pcapi/core/history/models.py
> +    SYNC_VENUE_TO_PROVIDER = "synchronisation du lieu avec un fournisseur"
euh... provider c'est pas anglais?

2024-07-25 15:09 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/templates/components/history/actions.html
> +              Logiciel : {{ action.extraData["provider_name"] }}
<img width="343" alt="Capture d’écran 2024-07-25 à 17 07 23" src="https://github.com/user-attachments/assets/b1eabd9c-69cd-46d2-b20a-cdd29ecb3b18">
<img width="136" alt="Capture d’écran 2024-07-25 à 17 07 34" src="https://github.com/user-attachments/assets/b834ce4c-db2d-4f56-bd6f-dceb18adb48b">
<img width="63" alt="Capture d’écran 2024-07-25 à 17 07 49" src="https://github.com/user-attachments/assets/967c6e88-8c28-42a4-accf-2df09ec85027">


¯\_(ツ)_/¯

2024-07-25 15:09 UTC, aminepass commented on api/src/pcapi/routes/backoffice/pivots/blueprint.py
> +                return redirect(url_for(".get_pivots", active_tab=name), code=303)
il faut déplacer cette partie plus haut dans la fonction (au niveau du `if not form.validate()`) pour éviter de commencer la création de pivot.

2024-07-25 15:10 UTC, aminepass commented on api/src/pcapi/routes/backoffice/pivots/blueprint.py
> +from pcapi.core.history.api import add_action
par soucis de cohérence avec le reste du code il est recommandé de faire `from pcapi.core.history import api as history_api` puis `history_api.add_action(…)` plus bas dans la vue

2024-07-25 15:16 UTC, borisLeBonPro commented on api/src/pcapi/core/providers/api.py
> +    author: users_models.User | None = None,
Alors en soit non, mais il y a un paquet de test qui envoie la fonction sans author, c'est pour ca que je l'avais mis ainsi pour pas modifier plein de truc dans test_api

2024-07-25 15:16 UTC, Vencespass commented on api/src/pcapi/core/history/models.py
> +    SYNC_VENUE_TO_PROVIDER = "synchronisation du lieu avec un fournisseur"
Oui mais c'est uniforme 😛

2024-07-25 15:20 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/templates/components/history/actions.html
> +              Logiciel : {{ action.extraData["provider_name"] }}
En fait, dans le BO, on dit un Partenaire technique

2024-07-25 15:20 UTC, Vencespass commented on api/src/pcapi/core/history/models.py
> +    SYNC_VENUE_TO_PROVIDER = "synchronisation du lieu avec un fournisseur"
En fait, tu peux le changer, avec l'autre provider au dessus en `Partenaire technique`

2024-07-25 15:44 UTC, Vencespass commented on api/src/pcapi/core/providers/api.py
> +    author: users_models.User | None = None,
Bah, il faut modifier quand même mdr

2024-07-25 16:10 UTC, borisLeBonPro commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
il faudrait toucher a get_context dans __init__ et ce truc affecte toutes les fonctions du blueprint et test de pivot

2024-07-25 16:21 UTC, Vencespass commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
Je te demande pas d'utiliser `get_context`, tu peux juste faire un `format` qui gère ça dans l'affichage de l'historique

2024-07-25 17:53 UTC, borisLeBonPro commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
Haaa tu parlais de l'affichage front !

2024-07-26 07:52 UTC, Vencespass commented on api/tests/routes/backoffice/pivots_test.py
> +        assert action.extraData["pivot_name"] == "allocine"
Bah, "à l'affichage dans le BO"...

2024-07-26 09:09 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/pivots/blueprint.py
> +        flash("Lieu inexistant", "warning")
```suggestion
        flash(Markup("Le lieu id={venue_id} n'existe pas").format(venue_id=venue_id), "warning")
```
Un peu d'uniformité, c'est important

2024-07-26 09:09 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +    return pivot
Alors
- `pivot_name` en paramètre, c'est plus adapté
- tu peux utiliser un `case`, comme pour les autres formateurs
- Il y a d'autres pivots cinémas que ces deux là à formatter...

2024-07-26 09:09 UTC, Vencespass commented on api/src/pcapi/core/history/models.py
> +    SYNC_VENUE_TO_PROVIDER = "synchronisation du lieu avec un provider"
Tu peux donc utiliser Partenaire technique au lieu de provider

2024-07-26 10:54 UTC, borisLeBonPro commented on api/src/pcapi/routes/backoffice/filters.py
> +    return pivot
Je trouvais ca moche de mettre la majuscule au autre mais si tu insistes...

2024-07-26 12:18 UTC, Vencespass commented on api/src/pcapi/routes/backoffice/filters.py
> +            return pivot_name
C'est pas juste pour une histoire de majuscule, c'est des labels qu'on a déjà dans le BO, qu'on affiche un peu partout, et c'est important de pas l'écrire différemment à chaque fois, c'est un des principes d'une bonne UX.
<img width="1552" alt="Capture d’écran 2024-07-26 à 14 16 43" src="https://github.com/user-attachments/assets/457d882e-6d3a-48f8-b3ca-86e1159e801b">

2024-07-26 12:53 UTC, Vencespass approved these changes

2024-07-30 08:59 UTC, Meewan requested changes

2024-07-30 08:59 UTC, Meewan commented on api/src/pcapi/routes/pro/venue_providers.py
> +            author=current_user,
```suggestion
            author=current_user.real_user,
```

sinon tu vas avoir des problemes avec le connect-as

2024-07-31 10:00 UTC, Meewan commented on api/src/pcapi/routes/backoffice/pivots/contexts/allocine.py
> +    @classmethod
pourquoi des classmethod ? si tu n'utilises pas la class tu peux utiliser `@staticmethod`
https://docs.python.org/3/library/functions.html#staticmethod

2024-07-31 10:00 UTC, Meewan commented on api/src/pcapi/routes/backoffice/pivots/contexts/base.py
> +    @classmethod
pourquoi des classmethod ? si tu n'utilises pas la class tu peux utiliser `@staticmethod`
https://docs.python.org/3/library/functions.html#staticmethod

2024-07-31 10:00 UTC, Meewan commented on api/src/pcapi/core/providers/api.py
> +    author: users_models.User,
```suggestion
    current_user: users_models.User,
```
le rennomer en current_user permetrait d'être plus clair parce que ce n'est pas forcement le author qu'on lui passe.

2024-07-31 10:00 UTC, Meewan commented on api/src/pcapi/routes/pro/venue_providers.py
> +            author=current_user.real_user,
désolé je n'aitais pas allé assez mloin dans ma review précédente il vaudrait mieux passer juste le current_user

2024-08-01 14:19 UTC, Meewan approved these changes

2024-08-02 12:00 UTC, merged