(BSR)[PRO] test: only intercept one create offer
pass-culture/pass-culture-main pull request #13946
Opened 2024-09-03 12:42 UTC by scolson-pass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-XXXXX

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai mis à jour le fichier des [plans de tests](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit) du portail pro si nécessaire
- [ ] J'ai mis à jour [la liste des routes et des titres](https://www.notion.so/passcultureapp/Titre-des-pages-de-l-espace-Pro-f4e490619bc54010adeb67c86d5e6a40?pvs=4) de pages du portail pro si j'en ai rajouté/modifié ou supprimé une.
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-09-03 13:54 UTC, ncanseco-pass requested changes

2024-09-03 13:54 UTC, ncanseco-pass commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
C'est beaucoup d'attendre 60 secondes pour le retour d'une requête ! ça met vraiment autant de temps à charger? on peut réduire?

2024-09-03 14:15 UTC, scolson-pass commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
Cela a été rajouté par @AmineLouveau dans cette [PR](https://github.com/pass-culture/pass-culture-main/pull/13556)
Ni le titre ni la description ne me permettent de comprendre le pourquoi du comment :)

2024-09-03 14:38 UTC, scolson-pass commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
et donc ce n'est pas nouveau

2024-09-04 07:58 UTC, ncanseco-pass approved these changes

2024-09-04 08:37 UTC, jclery-pass commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
De mémoire (mais je peux me tromper), le temps d'attente avait été mis à 60s en raison du temps de retour de l'API qui pouvait être extrêmement long. Depuis, le soucis a été corrigé, je pense qu'on peut effectivement réduire ce timer.

2024-09-04 09:59 UTC, Aliochka approved these changes
c'est ok pour moi mais je pense que tu peux merger tes deux commits!

2024-09-04 13:00 UTC, merged

2024-09-06 18:34 UTC, AmineLouveau commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
@scolson-pass on avait pourtant parlé des timeout dans notre conversation slack 🤔

2024-09-09 14:11 UTC, scolson-pass commented on pro/cypress/e2e/step-definitions/signupJourneyCreateOfferer.cy.ts
> +  cy.wait('@createOfferer', { timeout: 60000 })
@AmineLouveau Oui c'est vrai, je l'avais oublié, my bad!
Mais je pense que c'est tout de même mieux de faire un petit résumé dans les PRs et de préférence squasher les commits, il y en a 8 dans le cas de https://github.com/pass-culture/pass-culture-main/pull/13556 🤔