(PC-31554)[API]docs: updated API documentation. externalTicketOfficeUrl field of offer model is now deprecated
pass-culture/pass-culture-main pull request #13952
Opened 2024-09-03 15:24 UTC by pcharlet-pass

## But de la pull request

Ticket Jira : https://passculture.atlassian.net/browse/PC-31554

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai mis à jour le fichier des [plans de tests](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit) du portail pro si nécessaire
- [ ] J'ai mis à jour [la liste des routes et des titres](https://www.notion.so/passcultureapp/Titre-des-pages-de-l-espace-Pro-f4e490619bc54010adeb67c86d5e6a40?pvs=4) de pages du portail pro si j'en ai rajouté/modifié ou supprimé une.
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-09-04 08:35 UTC, mageoffray approved these changes

2024-09-04 09:21 UTC, tcoudray-pass requested changes
Bon là je demande des changements parce que ça casse le design 😬. 

Pour les changements concernant la documentation, il faut mettre les screenshots dans la PR car ce sont des "changements graphiques" (dernier point de la checklist de PR). Ça permet d'attraper le genre d'erreur que je t'ai remontée.

Tu peux générer la documentation en local. Toute la doc est dans ce [README](https://github.com/pass-culture/pass-culture-main/tree/master/api/documentation) 🙂. Si jamais elle n'est pas claire, ou plus à jour, n'hésite pas à la modifier.

2024-09-04 09:21 UTC, tcoudray-pass commented on api/documentation/src/pages/change-logs.md
> +
Il manque`:::` après ton texte ce qui casse le design (cf. screenshot)

```suggestion
:::warning
  Offer field `externalTicketOfficeUrl` is now deprecated and is going to be removed in the coming months.
:::
```

![image](https://github.com/user-attachments/assets/3763d668-ed3c-4d90-8958-c2f5480df314)

2024-09-04 09:21 UTC, tcoudray-pass commented on api/src/pcapi/routes/public/individual_offers/v1/serialization.py
> +    description="**(deprecated)** Link displayed to users wishing to book the offer but who do not have credit.",
tu peux en profiter pour déplacer le field dans le fichier [fields.py](https://github.com/pass-culture/pass-culture-main/blob/master/api/src/pcapi/routes/public/documentation_constants/fields.py). Toutes les descriptions des champs doivent être migrées dans ce fichier à terme

2024-09-04 09:21 UTC, tcoudray-pass commented on api/tests/routes/public/expected_openapi.json
> +}
L'ajout de ce retour chariot me donne l'impression que tu as modifié ce fichier à la main, ce qu'il ne faut pas faire.

Pour le mettre à jour il faut utiliser la commande `generate_expected_openapi_json` : 
- Si tu utilises docker, il suffit de lancer la commande `pc generate_expected_openapi_json` 
- si tu run flask en local, `flask generate_expected_openapi_json`

C'est beaucoup plus pratique 😃

2024-09-04 11:54 UTC, tcoudray-pass approved these changes

2024-09-05 08:23 UTC, closed without merging

2024-09-05 08:23 UTC, pcharlet-pass commented
Abandon de la dépréciation de ce champ