(BSR)[API] chore: add atomic decorators in backoffice root routes
pass-culture/pass-culture-main pull request #14094
Opened 2024-09-11 15:30 UTC by jcicurel-pass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31791

Ajout du décorateur atomic sur les routes

siret_api
autocomplete
health_check
home
move_siret
redirect

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai mis à jour le fichier des [plans de tests](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit) du portail pro si nécessaire
- [ ] J'ai mis à jour [la liste des routes et des titres](https://www.notion.so/passcultureapp/Titre-des-pages-de-l-espace-Pro-f4e490619bc54010adeb67c86d5e6a40?pvs=4) de pages du portail pro si j'en ai rajouté/modifié ou supprimé une.
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-09-12 08:24 UTC, jcicurel-pass commented on api/tests/routes/backoffice/accounts_test.py
> +            expected_num_queries=self.expected_queries + 1,  # one additional query (select on user) due to redirect
J'ai une query en plus suite au @atomic() sur la route /home ici (quand je l'enlève je n'ai pas cette query), c'est un genre de select * sur User

2024-09-12 16:01 UTC, jcicurel-pass commented on api/tests/routes/backoffice/accounts_test.py
> +            expected_num_queries=self.expected_queries + 1,  # one additional query (select on user) due to redirect
Je suis d'accord mais.. comment mes changements ont pu impacter cette route ?

`Pourquoi @atomic sur /home toucherait uniquement ce test en particulier ?`
-> je sais pas trop mais si je commente le atomic sur la route /home le test passe avec 5 requêtes

2024-09-12 16:05 UTC, jcicurel-pass commented on api/tests/routes/backoffice/accounts_test.py
> +            expected_num_queries=self.expected_queries + 1,  # one additional query (select on user) due to redirect
J'ai ajouté le load_only comme tu l'as indiqué

2024-09-12 16:50 UTC, prouzet approved these changes

2024-09-12 16:55 UTC, prouzet commented on api/tests/routes/backoffice/accounts_test.py
> +            expected_num_queries=self.expected_queries + 1,  # one additional query (select on user) due to redirect
Ce sont les mystères de l’ORM... On pourrait invalider tous les objets après la récupération du csrf, afin de ne rien avoir  préchargé, mais ça peut avoir des effets de bord dans des tests.

Je pense que le retour d’atomic, après l’appel de /home pour avoir un jeton csrf, termine probablement une session qui, avant, gardait des objets.

On a ainsi identifié un bug qui, dans la vraie vie, déclenchait une requête supplémentaire.

2024-09-13 07:37 UTC, jcicurel-pass commented on api/tests/routes/backoffice/accounts_test.py
> +            expected_num_queries=self.expected_queries + 1,  # one additional query (select on user) due to redirect
Ok je vois, merci !

2024-09-23 09:13 UTC, Meewan requested changes
La disparition du begin est problématique pou moi.

Comme sur les autres pr le probleme de gérer explicitement les cas d'erreur (désolé de pas avoir été clair dessus)

2024-09-23 09:13 UTC, Meewan commented on api/src/pcapi/routes/backoffice/move_siret.py
> +@atomic()
Dans cette fonction il faudrait un rollback dans le except

2024-11-18 10:38 UTC, rpaoloni-pass approved these changes

2024-11-18 10:58 UTC, merged