Pc 13078 use jsonb fields
pass-culture/pass-culture-main pull request #1410
Opened 2022-02-16 14:20 UTC by AnthonySkorski

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13078

## But de la pull request

Utiliser les champs JSONB récemment créer plutôt que leurs équivalents JSON

## Implémentation

- _Exemples: Ajouts de modèles, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-02-18 11:46 UTC, xordoquy requested changes

2022-02-18 11:46 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220214T111936_e9ddaad94156_set_jsonb_fields_as_used_ones.py
> +branch_labels = None
il faudra rebaser et regénérer la migration suite aux migrations pre/post deploy

2022-02-18 14:35 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220214T111936_e9ddaad94156_set_jsonb_fields_as_used_ones.py
> +branch_labels = None
ce que je veux dire, c'est que "normalement" un simple changement de ` down_revision` est suffisant et dans le cas présent, il faudra un peu plus

2022-02-21 08:34 UTC, dbaty reviewed
J'ai pas tout super bien suivi à cette migration globale, mais ça m'a l'air OK.

2022-02-21 08:34 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220214T111936_e9ddaad94156_set_jsonb_fields_as_used_ones.py
> +# Those fields can be altered because they belong to tables that contain very few records
(détail) le commentaire n'est pas tout à fait vrai pour la table `email` ;)

2022-02-21 08:34 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220214T145737_e9ddaad94157_create_new_index_product-jsondata-isbn.py
> +    # ### commands auto generated by Alembic - please adjust! ###
on peut supprimer ce commentaire (idem plus bas dans ce fichier et dans les autres)

2022-02-21 09:04 UTC, AnthonySkorski commented on api/src/pcapi/alembic/versions/20220214T111936_e9ddaad94156_set_jsonb_fields_as_used_ones.py
> +# Those fields can be altered because they belong to tables that contain very few records
effectivement :)

2022-02-21 10:45 UTC, xordoquy reviewed
Que se passe-t-il si les migrations (de cette PR) passent mais que ça bloque plus loin ?
Le code aura le champs `content` par ex déclaré comme JSON mais ce sera un JSONB dans la DB.
SQLAlchemy sait-il gérer ça ?

2022-02-21 10:45 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220214T145738_e9ddaad94158_create_new_index_offer-jsondata-isbn.py
> +    op.execute("COMMIT")
Il sera probablement pertinent d'augmenter le statement timeout pour cette table.

2022-02-21 11:00 UTC, AnthonySkorski commented on api/src/pcapi/alembic/versions/20220214T145738_e9ddaad94158_create_new_index_offer-jsondata-isbn.py
> +    op.execute("COMMIT")
J'ai déjà créé les index en prod comme tu me l'avais conseillé (de mémoire, ça a pris ente 10 et 15 minutes)
Cette migration est là surtout pour que les DB sur les postes de travail soient OK.
Tu penses que c'est necessaire d'augmenter le timeout du coup?

2022-02-21 11:01 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220214T145738_e9ddaad94158_create_new_index_offer-jsondata-isbn.py
> +    op.execute("COMMIT")
non, c'est parfait ! J'avais complètement perdu de vu que les index étaient déjà en prod/staging.

2022-02-21 11:05 UTC, AnthonySkorski commented
> Que se passe-t-il si les migrations (de cette PR) passent mais que ça bloque plus loin ? Le code aura le champs `content` par ex déclaré comme JSON mais ce sera un JSONB dans la DB. SQLAlchemy sait-il gérer ça ?

@xordoquy j'avoue que je ne sais pas comment ça peut se passer.
tous les opérateurs/fonctions JSON fonctionnent aussi avec le JSONB normalement, mais SQLAlchemy va peut être faire la gueule s'il constate une différence effectivement.
Je vais voir pour tester ce cas cet après-midi

2022-02-21 17:26 UTC, AnthonySkorski commented
> Que se passe-t-il si les migrations (de cette PR) passent mais que ça bloque plus loin ? Le code aura le champs `content` par ex déclaré comme JSON mais ce sera un JSONB dans la DB. SQLAlchemy sait-il gérer ça ?
@xordoquy Bon d'après mon test, ça ne dérange absolument pas SqlAlchemy de travailler avec un champ de modèle déclaré en JSON qui tappe en réalité sur une colonne JSONB.

Pour vérifier, j'ai remplacé les type des champs de modèle JSONB par du JSON (sans générer de migration) et j'ai lancé les tests.

Est que tu peux valider ton "change requested" afin que je puisse merger?

2022-02-21 20:34 UTC, xordoquy approved these changes

2022-02-22 08:58 UTC, merged