(PC-13305)[API] feat: add ministry field in educational deposit table
pass-culture/pass-culture-main pull request #1420
Opened 2022-02-16 17:57 UTC by gvannest

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13305

## But de la pull request

Préparer le backend pour recevoir les budgets des nouveaux ministères

## Implémentation

- Créer une nouvelle colonne `ministry` dans la table `EducationalDeposit` (enum)
- Ecrire un script pour rattraper les données existantes

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-02-18 11:45 UTC, xordoquy requested changes

2022-02-18 11:45 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220217T103324_eaad7175e489_add_ministry_enum_field_to_educational_deposit.py
> +branch_labels = None
Il faudra rebaser et régénérer la migration suite à l'introduction des migrations pre/post deploy

2022-02-21 10:21 UTC, cgaunet commented on api/src/pcapi/core/educational/models.py
> +        String(30),
Go ENUM pour cette colonne :)

2022-02-21 10:22 UTC, cgaunet approved these changes
Pas sûr qu'il y ait besoin de commit le script par contre :)

2022-02-21 19:09 UTC, xordoquy approved these changes

2022-02-22 08:12 UTC, merged