(PC-31890)[API] fix: Création de produit cohérent (gtl_id / subcategory) dans la Sandbox
pass-culture/pass-culture-main pull request #14338
Opened 2024-09-26 07:07 UTC by pcharlet-pass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-31890

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai mis à jour le fichier des [plans de tests](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit) du portail pro si nécessaire
- [ ] J'ai mis à jour [la liste des routes et des titres](https://www.notion.so/passcultureapp/Titre-des-pages-de-l-espace-Pro-f4e490619bc54010adeb67c86d5e6a40?pvs=4) de pages du portail pro si j'en ai rajouté/modifié ou supprimé une.
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2024-09-26 10:08 UTC, ogeber approved these changes

2024-09-26 10:19 UTC, ogeber requested changes
~Avant de merge: sur testing quand on fait un GET, le gtl id erroné est écrasé. Il faut qu'on vérifie ce fonctionnement~ souci de mon côté c'est bon

2024-09-26 11:35 UTC, pcharlet-pass commented on api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_thing_products.py
> +            gtl_id=MUSIC_SLUG_TO_GTL_ID["ROCK-HARD_ROCK"],
Il n'y a pas tout les genre musicaux dans `GTL_ID_BY_TITELIVE_MUSIC_GENRE`. Il faudra donc utiliser le genre `"ROCK"` plutôt que `"ROCK-HARD_ROCK"`, on ne pourra donc pas être cohérent avec `musicSubType` et `musicType`. 

`MUSIC_SLUG_TO_GTL_ID` c'est ce qui est utilisé dans l'API public des offres, est-ce qu'on risque pas de se retrouver avec des genre musicaux inexistant dans  `GTL_ID_BY_TITELIVE_MUSIC_GENRE` ?

2024-09-26 12:01 UTC, ogeber commented on api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_thing_products.py
> +            gtl_id=MUSIC_SLUG_TO_GTL_ID["ROCK-HARD_ROCK"],
On essaye de ne plus utiliser de `Music Sub Type` , même via l'api publique (même si c'est toujours possible)

2024-09-27 07:08 UTC, pcharlet-pass commented on api/src/pcapi/sandboxes/scripts/creators/e2e/create_e2e_thing_products.py
> +            gtl_id=MUSIC_SLUG_TO_GTL_ID["ROCK-HARD_ROCK"],
Ce fichier va disparaite, annulation des modifications

2024-09-27 08:33 UTC, ogeber approved these changes

2024-09-27 13:30 UTC, merged