(BSR)[PRO] test: add some JSDoc for commands and helper functions
pass-culture/pass-culture-main pull request #15433
Opened 2024-12-09 15:10 UTC by scolson-pass

## But de la pull request

Ajoute de la JSDoc pour les helper et nouvelles `Cypress.Commands` créées

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai mis à jour le fichier des [plans de tests](https://docs.google.com/spreadsheets/d/12I9f68L312xEE8lKFN7LsBHO2M_tcBBMSs0Be6qCQ98/edit) du portail pro si nécessaire
- [ ] J'ai mis à jour [la liste des routes et des titres](https://www.notion.so/passcultureapp/Titre-des-pages-de-l-espace-Pro-f4e490619bc54010adeb67c86d5e6a40?pvs=4) de pages du portail pro si j'en ai rajouté/modifié ou supprimé une.
- [ ] J'ai [relu attentivement les migrations](https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027), en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques
- [ ] J'ai fait la revue fonctionnelle de mon ticket

2024-12-10 09:29 UTC, rchaffal-pass approved these changes

2024-12-11 09:03 UTC, ncanseco-pass requested changes

2024-12-11 09:03 UTC, ncanseco-pass commented on pro/cypress/support/helpers.ts
> + * This function takes a string[][] as a DataTable representing the data
je ne suis pas dev, mais ça me choque de dire qu'une chaîne de caractères (string) est un tableau à deux dimensions :thinking: 
```suggestion
 * This function takes a table[][] as a DataTable representing the data
```

2024-12-11 09:32 UTC, scolson-pass commented on pro/cypress/support/index.d.ts
> +     * Workaround bc onChange not triggered for an input type='range' rendered by React
because

2024-12-11 09:39 UTC, scolson-pass commented on pro/cypress/support/helpers.ts
> + * @param {string} sessionName name of the session. Same name will reuse browser session
Non, JSdoc rajoute un '--' et ça donnerait ça

![CleanShot 2024-12-11 at 10 37 22](https://github.com/user-attachments/assets/6e26b36b-c505-4467-aad5-e4666e3d76ab)

2024-12-11 09:43 UTC, scolson-pass commented on pro/cypress/support/helpers.ts
> + * This function takes a string[][] as a DataTable representing the data
Non c'est bien le type que décrit Typescript

![CleanShot 2024-12-11 at 10 42 08](https://github.com/user-attachments/assets/a4640a48-7230-426e-bc89-3bb1cc3bad7d)

2024-12-11 10:06 UTC, ncanseco-pass approved these changes

2024-12-11 10:07 UTC, merged