Pc 13776 sib cron email to pro 7 days before event
pass-culture/pass-culture-main pull request #1826
Opened 2022-03-26 18:47 UTC by thig-pc

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-13776

## But de la pull request

Envoi aux AC, un email de rappel 7 jours avant un événement (offre)

## Implémentation
N/A

## Informations supplémentaires
N/A

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-03-28 08:08 UTC, dbaty requested changes

2022-03-28 08:08 UTC, dbaty commented on api/src/pcapi/core/bookings/repository.py
> +    return bookings_count
On dénormalise cette information dans `Stock.dnBookedQuantity`, donc pas besoin d'une fonction pour la calculer ! :)

2022-03-28 08:08 UTC, dbaty commented on api/src/pcapi/scheduled_tasks/clock.py
> +        booking_count = bookings_repository.find_not_cancelled_bookings_count_by_stock(stock)
Ça fait une requête SQL pour récupérer chaque stock, puis une autre requête SQL pour récupérer le nombre de réservations en cours. C'est un peu coûteux. Comme indiqué dans un autre commentaire, la seconde requête (pour le nombre de résas) peut sauter. Et pour la première, je propose de modifier (et renommer) `find_event_stock_ids_happening_in_x_days()` pour que cette fonction renvoie une "query" (et pas une liste d'identifiants). Ainsi, on pourra ici faire quelque chose comme : 

```
stocks = find_event_stocks_happening_in_x_days()
for stock in stocks:
    send_reminder_7_days_before_event_to_pro(stock)
```

Au passage, on n'a plus besoin de passer un 2ème argument à `send_reminder_7_days_before_event_to_pro`, puisque le nombre de résas en cours est porté par le stock.

... et on pourra adapter l'autre endroit qui appelle `find_event_stocks_happening_in_x_days` et a seulement besoin des identifiants.

Dernière chose : utiliser `distinct()` dans `find_event_stocks_happening_in_x_days()` pour éviter d'avoir à le faire dans tous les appelants.

2022-03-28 17:17 UTC, thig-pc commented on api/src/pcapi/core/bookings/repository.py
> +    return bookings_count
merci pour l'info, c'est fait

2022-03-28 17:17 UTC, thig-pc commented on api/src/pcapi/scheduled_tasks/clock.py
> +        booking_count = bookings_repository.find_not_cancelled_bookings_count_by_stock(stock)
merci pour les infos détaillées c'est top -> DONE

2022-03-29 07:57 UTC, dbaty commented on api/src/pcapi/core/mails/transactional/pro/reminder_before_event_to_pro.py
> +    recipient = stock.offer.bookingEmail or stock.offer.venue.bookingEmail
Ces 2 champs `bookingEmail` sont nullables, on doit traiter ce cas : 

```suggestion
    recipient = stock.offer.bookingEmail or stock.offer.venue.bookingEmail
    if not recipient:
        return True
```

2022-03-29 07:57 UTC, dbaty commented on api/src/pcapi/scheduled_tasks/clock.py
> +    stocks = find_event_stocks_happening_in_x_days(7)
Il faudrait joinedload les offres et lieux liés ici pour charger toutes les informations liées, sinon on va faire 2 requêtes SQL par stock dans la fonction `send_reminder_7_days_before_event_to_pro`. Quelque chose comme ça (avec `import sqlalchemy.orm as sqla_orm`) : 

```suggestion
    stocks = find_event_stocks_happening_in_x_days(7).options(sqla_orm.joinedload(Stock.offer).joinedload(Offer.venue))
```

(et idem dans `commands.py` évidemment)

2022-03-29 07:57 UTC, dbaty commented on api/src/pcapi/core/offers/repository.py
> +def find_event_stock_ids_happening_in_x_days(number_of_days: int) -> set[int]:
Mon idée était de supprimer cette fonction, puisqu'elle est quasi identique à `find_event_stocks_happening_in_x_days()` que tu définis ci-dessous.

Là où on a besoin de récupérer seulement les identifiants de stock, on pourra faire écrire quelque chose comme ça : 

```
stock_ids = {stock_id for stock_id, in find_event_stocks_happening_in_x_days().with_entities(Stock.id)}
```

2022-03-29 09:49 UTC, dbaty commented
Attention, il faudra penser à déclarer ce nouveau cron job dans les fichiers "helm/pcapi/values.*.yaml" du dépôt pass-culture-deployment.

2022-03-29 11:32 UTC, thig-pc commented on api/src/pcapi/core/mails/transactional/pro/reminder_before_event_to_pro.py
> +    recipient = stock.offer.bookingEmail or stock.offer.venue.bookingEmail
Done

2022-03-29 11:34 UTC, thig-pc commented on api/src/pcapi/core/offers/repository.py
> +def find_event_stock_ids_happening_in_x_days(number_of_days: int) -> set[int]:
Done

2022-03-29 15:07 UTC, dbaty approved these changes

2022-03-29 15:32 UTC, merged