(PC-14131)[API] cron email booking event reminder to beneficiaries
pass-culture/pass-culture-main pull request #2156
Opened 2022-04-29 13:33 UTC by thig-pc

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14131

## But de la pull request

PR qui contient 3 éléments :
contenu du mail pour notifier les bénéficiares ayant un evenement le lendemain
une query pour aller chercher toutes les réservations de type événement ayant lieu le lendemain
une commande pour lancer un cron

## Implémentation
N/A

## Informations supplémentaires
2 commits supplémentaires
- un commit pour une configuration liveshare vscode pour le mob programming
- un commit pour permettre le bon fonctionnement de breakpoint() sous docker de test -> modification fichier test-backend.sh

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-05-02 08:33 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/bookings/repository.py
> +    return print(
je pense que ce print n'a rien à faire là et fait échouer les tests

2022-05-02 08:40 UTC, bruno-ebstein-pass-culture requested changes

2022-05-02 08:40 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/mails/transactional/bookings/booking_event_reminder_to_beneficiary.py
> +            "VENUE_POSTAL_CODE": individual_booking.booking.stock.offer.venue.postalCode,
on avait des TODO en commentaire

c'est bien de les supprimer avant de faire une PR

mais ils ne semblent pas avoir été fait

2022-05-02 12:17 UTC, thig-pc commented on api/src/pcapi/core/bookings/repository.py
> +    return print(
oublie pour le print.
Encore un petit problème avec la query qui ne filtre pas les événements digitaux (je vais faire une fonction qui les filtre à part, il n'y aura plus qu'à la retirer plus tard)

2022-05-10 09:49 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/bookings/repository.py
> +def find_individual_bookings_event_happening_tomorrow_query() -> list[IndividualBooking]:
je viens de tomber sur ça

https://github.com/pass-culture/pass-culture-main/blob/3e1ae475297a501533de31fc2418c8481be51303/api/src/pcapi/core/offers/repository.py#L480

est-ce qu'on pourrait réutiliser cette fonction ?

2022-05-10 14:53 UTC, bruno-ebstein-pass-culture approved these changes

2022-05-11 09:25 UTC, bruno-ebstein-pass-culture approved these changes

2022-05-12 08:10 UTC, merged