(PC-14632)[API] fix: Remove 7 deprecated feature flags
pass-culture/pass-culture-main pull request #2220
Opened 2022-05-05 13:39 UTC by prouzet

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-14632

## But de la pull request

Suppression de FF obsolètes sur FA :
- ALLOW_IDCHECK_UNDERAGE_REGISTRATION
- ENABLE_DUPLICATE_USER_RULE_WITHOUT_BIRTHDATE
- ENABLE_ID_CHECK_RETENTION
- ENABLE_NATIVE_APP_RECAPTCHA
- ENABLE_NATIVE_ID_CHECK_VERBOSE_DEBUGGING
- ENABLE_NATIVE_ID_CHECK_VERSION
- WEBAPP_V2_ENABLED

## Implémentation

## Informations supplémentaires

J'ai considéré leur valeur sur la production comme comportement à conserver : actifs pour tous sauf ENABLE_NATIVE_ID_CHECK_VERBOSE_DEBUGGING.

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-05-05 14:05 UTC, viconnex commented on api/src/pcapi/core/subscription/api.py
> -    if not FeatureToggle.ALLOW_IDCHECK_UNDERAGE_REGISTRATION.is_active():
? pourquoi enlever ce flag ? 🤔

2022-05-05 14:09 UTC, viconnex commented on api/src/pcapi/routes/native/v1/account.py
> -    if FeatureToggle.ENABLE_NATIVE_APP_RECAPTCHA.is_active():
je suis plus trop au clair sur ce flag, tu es sûr qu'on peut le supprimer ?

2022-05-05 14:18 UTC, prouzet commented on api/src/pcapi/core/subscription/api.py
> -    if not FeatureToggle.ALLOW_IDCHECK_UNDERAGE_REGISTRATION.is_active():
La liste des FF à supprimer a été demandée par Hadidja dans le ticket https://passculture.atlassian.net/browse/PC-14632
Ça donc sans doute été vu avec le produit.

2022-05-05 14:19 UTC, prouzet commented on api/src/pcapi/alembic/versions/20210803_bebba9216847_add_feature_toggle_webapp_v2_enabled.py
> +    feature.remove_feature_from_database(get_flag())
Ça ne gène pas d'avoir des révisions manquantes dans l'historique connu par alembic ?

2022-05-05 15:39 UTC, prouzet commented on api/src/pcapi/alembic/versions/20210803_bebba9216847_add_feature_toggle_webapp_v2_enabled.py
> +    feature.remove_feature_from_database(get_flag())
ok on les supprime ; à faire lorsqu'on sera sûrs des FF à supprimer

2022-05-05 15:47 UTC, dbaty commented on api/src/pcapi/models/feature.py
> -    WEBAPP_V2_ENABLED = "Utiliser la nouvelle web app (décli web/v2) au lieu de l'ancienne"
On est certain de pouvoir supprimer ce _feature flag_ ?

2022-05-09 15:52 UTC, dbaty commented on api/src/pcapi/models/feature.py
> -    WEBAPP_V2_ENABLED = "Utiliser la nouvelle web app (décli web/v2) au lieu de l'ancienne"
C'était par rapport au commentaire (c'est sûr qu'on ne va pas désactiver ce feature flag !). Si je me souviens bien, la webapp v1 appelle le backend pour récupérer la valeur de ce setting (sur `/features`, il me semble). S'il reste des utilisateurs qui vont sur la webapp v1, il faut conserver ce feature flag pour continuer à les rediriger vers la nouvelle webapp. La question est donc : restent-ils encore des utilisateurs qui vont sur cette webapp v1...

2023-03-10 10:00 UTC, dbaty commented
@prouzet : que fait-on de cette pull request ? Je suppose que quelques features flags (et peut-être tous) ont été supprimés depuis le temps. :)

2023-03-10 11:12 UTC, prouzet commented
> @prouzet : que fait-on de cette pull request ? Je suppose que quelques features flags (et peut-être tous) ont été supprimés depuis le temps. :)

H.H. devait voir avec les PM des squads concernées par ces features flags, mais j'ai l'impression que c'est tombé à l'eau

2023-03-29 15:50 UTC, dbaty requested changes
J'ai refait un tour sur les feature flags, j'ai quelques suggestions.

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="ALLOW_IDCHECK_UNDERAGE_REGISTRATION",
:heavy_check_mark: Suppression confirmée, on ne se sert plus de ce flag depuis 094eff1e1d9c6f3191adef9889fc9b0983941e17.

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="ENABLE_DUPLICATE_USER_RULE_WITHOUT_BIRTHDATE",
:heavy_check_mark: Suppression confirmée, on ne se sert plus de ce flag depuis 094eff1e1d9c6f3191adef9889fc9b0983941e17.

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +        ),
Ce feature flag a déjà été supprimé dans bae303a949ff03f58eecc593bf8a54b2c69ca4b2.

```suggestion
```

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="ENABLE_NATIVE_APP_RECAPTCHA",
:red_circle: Celui, j'ai un doute. Oui, je sais que H. avait apparemment demandé, mais j'ai quand même un doute. Je pense qu'on devrait demander aux PM mobile s'il est opportun de le supprimer. C'est-à-dire : est-ce qu'on ne voudra jamais désactiver ce feature flag ? Et j'aimerais bien que l'équipe dév mobile ait un ticket de suppression de l'utilisation de ce setting. Ainsi, on sera _vraiment_ certain que l'app n'en a plus besoin, et on sera _vraiment_ certain qu'on peut le supprimer. :)

En tout cas, je pense que ça devrait faire l'objet d'un commit séparé, parce que ça change nettement plus de code que la suppression des autres feature flags. Qu'en penses-tu ?

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="ENABLE_NATIVE_ID_CHECK_VERBOSE_DEBUGGING",
:heavy_check_mark: Suppression confirmée, ça n'est plus utilisé côté app (cf. pass-culture/pass-culture-app-native@e9e3d2e971ebbbdf65c98b47a0d6a501eef84716).

Là encore, comme on modifie le code d'une route utilisée par l'app, je verrais bien un commit distinct. Qu'en penses-tu ?

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/routes/native/v1/settings.py
> +        enable_native_id_check_verbose_debugging=False,
Il faudra aussi mettre à jour le schéma côté app pour en faire un champ optionnel à partir de la prochaine version X de l'app, puis indiquer dans le FIXME le numéro de cette version X dans ce commentaire. Ça nous aidera à détecter quand on pourra faire le ménage.

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +        ),
Déjà supprimé dans 0062b174b402c563a0d75295562fc2a4ffb2a837.

```suggestion
```

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/models/feature.py
> -    WEBAPP_V2_ENABLED = "Utiliser la nouvelle web app (décli web/v2) au lieu de l'ancienne"
Il est improbable qu'il reste des utilisateurs de la webapp v1. Je pense qu'il est temps de dire au revoir à ce feature flag. J'approuve sa suppression. :)

2023-03-29 15:50 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="WEBAPP_V2_ENABLED",
:heavy_check_mark: Cf. mon commentaire plus bas, on peut supprimer celui-ci.

2023-07-18 09:48 UTC, dbaty commented on api/src/pcapi/alembic/versions/20220505T122808_133781a56ae0_remove_7_feature_flags.py
> +            name="ENABLE_NATIVE_APP_RECAPTCHA",
:red_circle: Je confirme mon doute : ce setting est encore utilisé côté app, cf. [cette recherche](https://github.com/search?q=repo%3Apass-culture%2Fpass-culture-app-native%20isRecaptchaEnabled&type=code).

**Donc on n'est clairement pas prêt pour supprimer `ENABLE_NATIVE_APP_RECAPTCHA` côté backend.**

2023-10-18 11:46 UTC, closed without merging