(PC-15812)[API] feat: backoffice - add pagination to public account search
pass-culture/pass-culture-main pull request #2779
Opened 2022-07-01 10:56 UTC by AnthonySkorski

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-15812

## But de la pull request

_Ajout de fonctionnalités, Problèmes résolus, etc_

## Implémentation

- _Exemples: Ajouts de modèles, de routes, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Modifications du schéma de la base de données

- _Exemples: suppressions de telles colonnes, migration d'une information dans une nouvelle table_
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler l'implémentation technique_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-07-04 08:58 UTC, dupush requested changes

2022-07-04 08:58 UTC, dupush commented on api/tests/routes/backoffice/accounts_test.py
> +        for i in range(50):
Tu te sers dans les 4 fonctions de test.
En dans les 2 tests d'erreurs, seule la quantité change.
suggestion : factoriser cette fonction en passant le nombre d'éléments à créer en paramètre.

2022-07-04 08:58 UTC, dupush commented on api/tests/routes/backoffice/accounts_test.py
> +        assert content["size"] == 20
Je trouve pas très parlant que le nombre d'éléments par page par défaut est 20.
Il faut lire les assertions pour le comprendre mais c'est pas explicite.
suggestion : ajouter une variable `default_item_per_page=20` dans le given et utiliser cette variable dans l'assertion.

2022-07-04 08:58 UTC, dupush commented on api/tests/routes/backoffice/accounts_test.py
> +            url_for("backoffice_blueprint.search_public_account", q="Mireille", page=2),
suggestion: Pour que le test soit plus parlant, tu pourrais extraire le numéro de par dans une variable `page_number` et l'utiliser pour le when et pour l'assertion du content["page"].

2022-07-04 08:58 UTC, dupush commented on api/tests/routes/backoffice/accounts_test.py
> +            url_for("backoffice_blueprint.search_public_account", q="Mireille", page=3, perPage=5),
suggestion : idem extraire les deux paramètres dans des variables explicite pour plus de clarté.

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/routes/backoffice/serialization.py
> +    perPage: typing.Optional[int] = 20
Question d'habitude, mais je ne suis pas habitué au terme `perPage`.
J'ai plus souvent vu `limit` qui me semble tout aussi explicite (et qui rappelle par ailleurs le "limit" de sql dans postgres).
Je suggère donc d'utiliser plutôt `limit` ;)

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/routes/backoffice/accounts.py
> +    response_model=serialization.PaginatedResponse,
Pas trop d'accord là dessus.
Je trouve qu'on perd beaucoup en précision avec ce changement.
Pourquoi ne pas laisser `ListPublicAccountsResponseModel` ?

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/routes/backoffice/accounts.py
> +) -> serialization.PaginatedResponse:
Pareil, pourquoi ne pas laisser ListPublicAccountsResponseModel ?

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/routes/backoffice/accounts.py
> +    sorts = query.sort.split(",") if query.sort else ["id"]
🤔 je me demande si c'est le bon endroit pour indiquer la propriété de tri par défaut.
On ne pourrait pas la mettre ailleurs ?
De plus, dans le `PublicAccountSearchQuery` on dit bien que le `sort` est Optionnel.
Donc on pourrait mettre ici else None et traiter le tri par défaut dans le `search_public_account`.

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/routes/backoffice/accounts.py
> +    return utils.build_paginated_response(
Je me demande si on ne pourrait pas factoriser cette partie.
Car toutes les routes paginées vont fonctionner de la même manière à l'exception du serializer.
Pas forcément le faire dans cette PR, mais ce serait un bon move à faire.

2022-07-04 08:58 UTC, dupush commented on api/src/pcapi/core/users/api.py
> +            raise ApiErrors({"sorting": str(err)})
Rien à voir avec cette PR, mais on devrait définir un standard de messages d'erreurs pour toute l'API backoffice.
Quand je vois ce `sorting` je me dis que c'est un peu spécifique.
On en reparle ?

2022-07-04 09:03 UTC, akarki16 commented on api/src/pcapi/routes/backoffice/serialization.py
> +    perPage: typing.Optional[int] = 20
le paramètre conseillé par react-admin est bien `perPage`.

2022-07-04 12:43 UTC, AnthonySkorski commented on api/src/pcapi/routes/backoffice/serialization.py
> +    perPage: typing.Optional[int] = 20
je comprends, mais pour le coup `perPage` semble plus en phase avec la mode du moment apparemment:

- [la métode paginate de FlaskSqlalchemy](https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.BaseQuery.paginate) par exemple utilise un paramètre `per_page` 
- [ReactAdmin](https://marmelab.com/react-admin/doc/4.0/DataProviderWriting.html) utilise aussi un paramètre `perPage`

Du coup j'ai pris cette convention et je pense qu'elle est suffisamment explicite pour qu'on la conserve.

2022-07-04 12:48 UTC, AnthonySkorski commented on api/src/pcapi/routes/backoffice/accounts.py
> +    response_model=serialization.PaginatedResponse,
c'est un relicat d'un essai précédent ou l'attribut `PaginatedResponse.data` pouvait contenir une `ListPublicAccountsResponseModel`.
actuellement, vu que que `ListPublicAccountsResponseModel` hérite de `PaginatedResponse`, on peut effectivement laisser `ListPublicAccountsResponseModel`

2022-07-04 12:58 UTC, AnthonySkorski commented on api/src/pcapi/routes/backoffice/accounts.py
> +    sorts = query.sort.split(",") if query.sort else ["id"]
mettre le tri par d'afaut ici plutôt que dans `search_public_account`, permet de garder la possibilité à `search_public_account` de renvoyer une requête non triée dans le cas ou on lui fourni un `order_by=None`. Je ne sais pas si on en aura beau coup besoin, mais le fait de garder cette possibilité m'a paru interessant.

Pour autant, la route à quand même besoin d'un tri par défaut pour s'assurer que les résultat sont toujours renvoyés dans le même ordre (PG ne garantie pas l'ordre de résultat sans `ORDER BY`) et que la pagination soit donc fonctionnelle, même dans le cas ou n'a pas spécifié d'ordre. ça ne me parait donc pas déconnant que ça soit la route qui fixe ce tri par défaut.

2022-07-04 13:01 UTC, AnthonySkorski commented on api/src/pcapi/core/users/api.py
> +            raise ApiErrors({"sorting": str(err)})
yep

2022-07-05 09:50 UTC, dupush approved these changes

2022-07-05 10:15 UTC, merged