(PC-5572) deploy on GCP staging env
pass-culture/pass-culture-main pull request #283
Opened 2020-12-08 16:22 UTC by CamilSadiki

2020-12-14 09:51 UTC, achapusot-pass requested changes

2020-12-14 09:51 UTC, achapusot-pass commented on .circleci/config.yml
> +    docker:
Ajouter l'authent Docker Hub : DockeHub pull limit

2020-12-14 09:51 UTC, achapusot-pass commented on .circleci/config.yml
> +    docker:
same here

2020-12-14 09:51 UTC, achapusot-pass commented on .circleci/config.yml
> +          app_service_account_email: secret-reader@pass-culture-app-projet-test.iam.gserviceaccount.com
utiliser le SA staging

2020-12-14 09:51 UTC, achapusot-pass commented on .circleci/config.yml
> +          vpc_connector_name: metier-development
Vraiment penser à le rename

2020-12-14 14:33 UTC, CamilSadiki commented on .circleci/config.yml
> +          vpc_connector_name: metier-development
J'ai créé un ticket dans le backlog

2020-12-15 08:49 UTC, achapusot-pass approved these changes
lgtm

2020-12-15 08:49 UTC, merged