(PC-16353)[ADAGE] feat: use collective fields for venue adage serialization whenever possible
pass-culture/pass-culture-main pull request #3066
Opened 2022-07-28 09:31 UTC by Meewan

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16353

2022-07-28 10:15 UTC, MathildeDuboille commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +    return serialized
sinon on aurait pas pu le faire dans BaseVenueModel ? Puisque chaque autre serializer se base sur BaseVenueModel

2022-07-28 13:31 UTC, Meewan commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +    return serialized
Non parceque Venue a deja un champ description et que si on le modifie sans commiter apres on fait crasher les tests. ça m'a pris 2h pour arriver a cette solution (la seule que j'ai réussis a faire marcher)

2022-07-29 08:21 UTC, MathildeDuboille commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +    return serialized
Je viens de test en faisant 
```
def from_orm(cls: "Type[BaseVenueModel]", venue: Venue) -> "BaseVenueModel":
        contact: VenueContact | None = venue.contact

        if venue.collectiveEmail:
            venue.email = venue.collectiveEmail
        elif contact is not None:
            venue.email = contact.email

        if venue.collectiveWebsite:
            venue.website = venue.collectiveWebsite
        elif contact is not None:
            venue.website = contact.website

        if venue.collectivePhone:
            venue.phoneNumber = venue.collectivePhone
        elif contact is not None:
            venue.phoneNumber = contact.phone_number

        res = super().from_orm(venue)
        res.description = venue.collectiveDescription or venue.description

        return res
```

et le test passe

2022-07-29 08:26 UTC, Meewan commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +    return serialized
je vais essayer

2022-07-29 13:39 UTC, MathildeDuboille commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +
Je comprends pas pourquoi t'as besoin de ca ?

2022-07-29 13:46 UTC, MathildeDuboille approved these changes

2022-07-29 13:48 UTC, MathildeDuboille requested changes

2022-07-29 13:48 UTC, MathildeDuboille commented on api/src/pcapi/routes/adage/v1/serialization/venue.py
> +        result.description = venue.collectiveDescription or venue.description
pas description en fallback et collectiveDescription dans un champs à part cf la réu avec Mickael :)

2022-07-29 14:04 UTC, MathildeDuboille approved these changes

2022-08-01 09:37 UTC, merged