add db-ops docker image + CI
pass-culture/pass-culture-main pull request #308
Opened 2021-02-19 13:07 UTC by achapusot-pass

2021-02-22 10:40 UTC, CamilSadiki requested changes

2021-02-22 10:40 UTC, CamilSadiki commented on infra/docker-images/db-ops/Dockerfile
> +                        libpq-dev \
A enlever car deja installé dans l'image de base

2021-02-22 10:40 UTC, CamilSadiki commented on infra/docker-images/db-ops/Dockerfile
> +                        git \
Git n'est plus necessaire

2021-02-22 10:40 UTC, CamilSadiki commented on infra/docker-images/db-ops/Dockerfile
> +ARG  TAG
Argument a renommer pour plus de clarté.
BASE_PCAPI_TAG ?

2021-02-22 16:15 UTC, CamilSadiki commented on .circleci/config.yml
> +                - production
Ca ferait plus de sens de build l'image (et deployer le chart par la suite) sur la branche staging parce que cette image va utiliser le code de pcapi pour se connecter a la base de staging.

2021-02-23 10:33 UTC, achapusot-pass commented on infra/docker-images/db-ops/Dockerfile
> +ARG  TAG
👍

2021-02-23 10:33 UTC, achapusot-pass commented on .circleci/config.yml
> +                - production
👌

2021-02-23 11:27 UTC, merged