add CI helm chart dbops
pass-culture/pass-culture-main pull request #314
Opened 2021-02-26 09:26 UTC by achapusot-pass

2021-02-26 10:18 UTC, CamilSadiki requested changes

2021-02-26 10:18 UTC, CamilSadiki commented on .circleci/config.yml
> +      NAMESPACE: production
```suggestion
      NAMESPACE: operations
```

2021-02-26 10:18 UTC, CamilSadiki commented on .circleci/config.yml
> +                - PC-7153/db-ops
```suggestion
                - staging
```

2021-03-01 08:51 UTC, CamilSadiki requested changes

2021-03-01 08:51 UTC, CamilSadiki commented on .circleci/config.yml
> +            - GCP_PROD
GCP_EHP j'imagine ?

```suggestion
            - GCP_EHP
```

2021-03-01 14:58 UTC, achapusot-pass commented on .circleci/config.yml
> +      NAMESPACE: production
✅

2021-03-01 15:14 UTC, CamilSadiki approved these changes

2021-03-01 15:16 UTC, merged