feat remove tables from dump
pass-culture/pass-culture-main pull request #316
Opened 2021-03-02 16:36 UTC by achapusot-pass

2021-03-11 13:10 UTC, CamilSadiki requested changes

2021-03-11 13:10 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
Ne reutilise pas la meme variable:
```suggestion
export TIMESTAMPED_DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
```

2021-03-11 13:10 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
Et si on utilise la variable DUMP_BUCKET_PATH c'est pas clair. Si j'y mets un truc du genre `dir/dump.gs` ca va timestamper le repertoire, ce qui est pas forcement ce qu'on veut

2021-03-11 13:10 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +    retries=5
Pourquoi relancer 5 fois la même commande et attendre un resultat different ?

2021-03-11 13:10 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +    until [ "$import_running_output" = "" ]
Je ne comprends pas cette modif

2021-03-11 13:10 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
>  fi
A faire directement après l'import. Si c'est des données qu'on ne veut pas, autant les garder le moins longtemps possible. Et cette action prendra moins de temps que l'anonymisation et la creation des utilisateurs.

2021-03-11 13:13 UTC, achapusot-pass commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
Bien vu mais la suggestion ne corrige pas le problème
Insérer une var dir/ et une var file_name ?

2021-03-11 13:55 UTC, achapusot-pass commented on infra/docker-images/db-ops/dump_restore.sh
> +    retries=5
"Tu connais la définition de la folie?"
J'ai oublié de mettre un sleep ^^ c'est pour ne pas die si une ope fini dans les 10min

2021-03-11 13:56 UTC, achapusot-pass commented on infra/docker-images/db-ops/dump_restore.sh
> +    until [ "$import_running_output" = "" ]
lié au code ci dessous et au `--format="value(name)"` qui renvoie une liste de nom ou vide

2021-03-11 13:56 UTC, achapusot-pass commented on infra/docker-images/db-ops/dump_restore.sh
>  fi
très judicieux

2021-03-11 13:57 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
Yiss sire

2021-03-11 13:58 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +    retries=5
Good

2021-03-11 13:58 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +    until [ "$import_running_output" = "" ]
Good

2021-03-12 09:02 UTC, achapusot-pass reviewed
modifs effectuées
modifs ici aussi 👉  https://github.com/pass-culture/infra-config/pull/62

2021-03-12 09:02 UTC, achapusot-pass commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
fait

2021-03-12 09:15 UTC, CamilSadiki commented on infra/docker-images/db-ops/dump_restore.sh
> +export DUMP_BUCKET_PATH="$(date +'%y-%m-%d')_${DUMP_BUCKET_PATH}"
Toujours chaud pour que tu affectes pas une nouvelle valeur à la même variable

2021-03-19 09:31 UTC, CamilSadiki approved these changes

2021-03-19 09:31 UTC, merged