Pc 6957/adapt pc commands to kubernetes
pass-culture/pass-culture-main pull request #317
Opened 2021-03-09 14:27 UTC by bba-pass

2021-03-12 09:40 UTC, achapusot-pass reviewed
C'est très cool ça !!
J'aurais bien envie de variabiliser `$(kubectl get po -n $ENV | grep pcapi-console | awk '{print $1}')`

2021-03-12 09:40 UTC, achapusot-pass commented on pc
> +      #scalingo -a "$SCALINGO_APP" run "python -i src/pcapi/scripts/interact.py"
On peut retirer le commentaire

2021-03-12 09:40 UTC, achapusot-pass commented on pc
> +      #scalingo -a "$SCALINGO_APP" run --file "$FILE_TO_UPLOAD" "python -i src/pcapi/scripts/interact.py"
On peut retirer le commentaire

2021-03-12 09:40 UTC, achapusot-pass commented on pc
> +      #scalingo -a "$SCALINGO_APP" run 'python src/pcapi/scripts/pc.py '"$CMD $*"''
On peut retirer le commentaire

2021-03-12 09:40 UTC, achapusot-pass commented on pc
> +      #scalingo -a "$SCALINGO_APP" run --file "$FILE_TO_UPLOAD" 'python src/pcapi/scripts/pc.py '"$CMD $*"''
On peut retirer le commentaire

2021-03-15 11:01 UTC, cgaunet commented on pc
> +    kubectl cp "$FILE_TO_UPLOAD" $(pod_console):"$FILE_TO_UPLOAD"
L'idée c'est aussi d'avoir le bash qui se lance ici :)

2021-03-15 11:01 UTC, cgaunet commented on pc
> +    kubectl -n $ENV exec -it $(pod_console)  -- bash
A-t-on besoin d'avoir le $ENV ici du coup ? :thinking:

2021-03-15 11:01 UTC, cgaunet commented on pc
> +  kubectl -n $ENV exec -it $(pod_console) -- bash -c 'dbclient-fetcher postgresql 10.4 && pg_dump "$SCALINGO_POSTGRESQL_URL" -s' > /tmp/pc_schema_staging
Idem pour le $ENV

2021-03-15 11:01 UTC, cgaunet commented on pc
> +    kubectl -n $ENV exec -it $(pod_console)  -- bash -c 'psql "$DATABASE_URL"'
Idem $ENV

2021-03-15 11:01 UTC, cgaunet commented on pc
> +    kubectl -n $ENV exec -it $(pod_console)  -- bash -c 'pgcli "$DATABASE_URL"'
Idem $ENV

2021-03-15 11:02 UTC, cgaunet commented on pc
> +      kubectl -n $ENV exec -it $(pod_console) -- python -i src/pcapi/scripts/interact.py
$ENV

2021-03-15 11:02 UTC, cgaunet commented on pc
> +    fi
:+1: 
Mais $ENV en trop ?

2021-03-15 11:02 UTC, cgaunet commented on pc
> +      kubectl -n $ENV exec -it $(pod_console) -- python src/pcapi/scripts/pc.py '"$CMD $*"'
Idem

2021-03-15 13:58 UTC, achapusot-pass commented on pc
> +    kubectl -n $ENV exec -it $(pod_console)  -- bash
Oui pour faire la distinction namespace
Tu vois une autre façon de faire @cgaunet ?

2021-03-15 14:04 UTC, achapusot-pass commented on pc
> +while test -d /
Pourquoi ce while ?
Pour moi : simplement faire le echo puis if $rep != y;then exit;fi

2021-03-15 14:05 UTC, achapusot-pass commented on pc
> +    kubectl cp "$FILE_TO_UPLOAD" $(pod_console):"$FILE_TO_UPLOAD"
@bba-pass peux-tu ajouter la ligne de connexion bash juste en dessous avec un `&& \` ?

2021-03-15 14:10 UTC, achapusot-pass requested changes
Retirer le while & ouvrir un bash après le file upload

2021-03-15 14:18 UTC, achapusot-pass commented
Comme discuté avec @cgaunet, pour le namespace (si c'est gênant), on peut le set [ici](https://github.com/pass-culture/pass-culture-main/pull/317/files#diff-d8463bd3ba4b10e5916f65fa7b0c1f9f91f67ca40cc25b48810fb2f5a3340488R39-R44) dans la définition de l'env

2021-03-15 17:42 UTC, achapusot-pass commented
On laisse `-n $ENV` (pour l'instant peut-être)

2021-03-16 08:41 UTC, achapusot-pass approved these changes
Good

2021-03-19 08:54 UTC, merged