(PC-18204)[API] fix: fix history action date timezone
pass-culture/pass-culture-main pull request #4101
Opened 2022-10-28 09:57 UTC by Vencespass

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18204

## But de la pull request

Ajout de la gestion de timezone aux dates de l'historique des validations de rattachement.

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-10-28 10:35 UTC, prouzet requested changes
Si la date est bien formatée, alors on devrait avoir le fuseau horaire (ou "Z") dans la date formatée renvoyée dans les tests. Mais je ne vois pas de changement dans les tests auto.
Comment vois-tu que ça marche ?

On n'a pas seulement la `date` dans `HistoryItem`. Et le `lastComment` ?

2022-10-28 13:22 UTC, prouzet reviewed
PR proposée en remplacement :
https://github.com/pass-culture/pass-culture-main/pull/4110

2023-03-10 10:11 UTC, dbaty commented
@Vencespass : apparemment, c'est la pull request #4110 de @prouzet qui a été mergée à la place. Est-ce qu'on peut supprimer cette pull request et sa branche ?

2023-03-10 10:22 UTC, Vencespass commented
Tu fais de l'archéologie haha
Oui on peut supprimer PR et branche

2023-03-17 17:42 UTC, closed without merging