(PC-16856)[PRO] feat: update eslint-pluging-jest
pass-culture/pass-culture-main pull request #4144
Opened 2022-11-02 13:57 UTC by damienPassCulture

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-16856

## But de la pull request

mise a jour de react-eslint-plugin

2022-11-02 14:19 UTC, AmineLouveau approved these changes
À vérifier si ça n'a pas cassé `quality-adage-front`, mais sinon ça me semble ok.

2022-11-04 10:05 UTC, MathildeDuboille approved these changes

2022-11-04 10:06 UTC, MathildeDuboille requested changes
c'est normal que ce soit dans adage-front ?

2022-11-04 10:14 UTC, damienPassCulture commented
> 
cote pro cest a good selon yarn audit

2022-11-07 09:07 UTC, closed without merging