BSR accessible autocomplete
pass-culture/pass-culture-main pull request #4207
Opened 2022-11-07 16:23 UTC by mariedestandau

- (BSR)[PRO] refactor: create a new select (again) from existing
- (BSR)[PRO] refactor:inline menu
- (BSR)[PRO] fix: selection for screen readers
- (BSR)[PRO] fix: Icon import path after rebase
- (BSR)[PRO] refactor: replace hidden style with attribute
- (BSR)[PRO] docs: update TODO.md
- (BSR)[PRO] refactor: style options list

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

_Ajout de fonctionnalités, Problèmes résolus, etc_

## Implémentation

- _Exemples: Ajouts de modèles, de routes, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Modifications du schéma de la base de données

- _Exemples: suppressions de telles colonnes, migration d'une information dans une nouvelle table_
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler l'implémentation technique_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-11-08 11:16 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/OptionsList.module.scss
> +  label,
Suggestion : rajouter un commentaire sur pourquoi on target l'élément HTML `label` en plus de la classe (pour override le style `cursor: default` du navigateur)

2022-11-08 11:16 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/OptionsList.module.scss
> +  input[type='checkbox'] {
idem pour le commentaire

2022-11-08 11:17 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/OptionsList.module.scss
> +  input[type='checkbox'] {
D'ailleurs c'est peut être plus clair sur l'intention si on l'extrait dans une règle séparée : 

```
.label, label, input[type='checkbox'] {
  cursor: pointer;
}
```

2022-11-08 11:21 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.module.scss
> +  box-sizing: border-box;
Il y a déjà un `box-sizing: border-box;` global appliqué avec le selecteur `*`, est-ce qu'il y a besoin de le repréciser ici ?

2022-11-08 11:22 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.module.scss
> +    left: rem.torem(12.8px);
Pourquoi on doit mettre des valeurs de pixels avec des décimales ?

2022-11-08 11:24 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.module.scss
> +.hidden {
Question : est-ce qu'il n'y a pas de classe/mixin générique capable de faire ça dans la codebase ? (je ne la connais pas encore assez pour savoir)

2022-11-08 11:28 UTC, AlbericTrancart commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +  const [hovered, setHovered] = useState<number | null>(null)
Je l'appelerai bien hoveredOptionIndex pour préciser que c'est une option qu'on hover et pas le select en entier + préciser pq c'est un nombre avec index :slightly_smiling_face:

2022-11-08 13:39 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.module.scss
> +.hidden {
J'ai eu à cacher visuellement un élément pour les lecteurs d'écrans.

Je propose de reprendre le contenu de la class `identifier-hidden` (qui est une version plus complète de la clas hidden ici, et qui se trouve dans `VenueFormScreen.module.scss`), créer une class `visually-hidden` et la réutiliser ici.

Il ne faut pas mélanger `hidden` (non lu par les lecteurs d'écrans) et non visible à l'écran

2022-11-08 13:39 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/index.tsx
> +                aria-selected={isSelected ? 'true' : 'false'}
```suggestion
                aria-selected={isSelected}
```

2022-11-08 13:39 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +          setHovered(filteredOptions.length - 1)
Comme on ne scroll pas sur l'élément sélectionné, on pense que le `ArrowUp`, on sort de la liste, mais on se retrouve tout en bas.

D'ailleurs, je trouve ça particulier de revenir tout en bas de la liste, au lieu de ne juste rien faire.

2022-11-08 13:39 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +          setHovered(0)
Pareil ici, je trouve ça particulier de revenir tout en haut de la liste, au lieu de ne juste rien faire.

2022-11-08 13:39 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +        if (!isOpen) setIsOpen(true)
(avec la ligne d'après)
```suggestion        
        openField()
```

2022-11-08 13:46 UTC, Aliochka approved these changes
juste une question pourquoi SelectAutoComplete2 et pas juste remplacer l'ancien ?
ils ont des buts différents ?

2022-11-08 13:46 UTC, Aliochka commented on TODO.md
> +- [ ] remplacer le composant TextInputAutocomplete
on veut le commiter ce fichier ?

2022-11-08 13:46 UTC, Aliochka commented on pro/src/ui-kit/form/SelectAutoComplete2/Toggle/index.tsx
> +import cx from 'classnames'
à discuter peut être, 
mais partout ailleurs on met le composant dans un Composant.tsx
et on se sert de l'index.ts simplement pour l'exporter

2022-11-08 13:46 UTC, Aliochka commented on pro/src/ui-kit/form/SelectAutoComplete2/Toggle/index.tsx
> +      <Icon
on essaye de supprimer Icon,
il faudrait déplacer l'icone dans src/icons
et l'importer directement en tant que svg 
`import { ReactComponent as ArrowDown } from 'pages/Offers/Offer/Thumbnail/assets/arrow-down.svg'`
tu peux ensuite la retirer de PublicIcons.tsx et la rajouter dans Icons.tsx (pour le storybook)
(attention faudra changer ton style image en svg, parfois ça implique de changer le svg directement)

2022-11-08 13:46 UTC, Aliochka commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/OptionsList.module.scss
> +    background: #f5f5f5;
`background: colors.$grey-light;`
pour pouvoir gérer toutes les couleurs au même endroit

2022-11-08 13:56 UTC, rlecellier reviewed
Quelques remarques sur la forme à prendre ou pas :)

2022-11-08 13:56 UTC, rlecellier commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/index.tsx
> +type SelectOption = { value: string; label: string }
Un type exite pour les option de select
https://github.com/pass-culture/pass-culture-main/blob/master/pro/src/custom_types/inputs.d.ts#L1-L4

2022-11-08 13:56 UTC, rlecellier commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/index.tsx
> +                className={hovered === index ? styles['option-hovered'] : ''}
On pourrait utiliser `cn()` ici aussi

2022-11-08 15:57 UTC, mariedestandau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.module.scss
> +.hidden {
ça marche, je crée le mixin, je te laisserai le remplacer dans Venue

2022-11-08 16:05 UTC, mariedestandau commented on pro/src/ui-kit/form/SelectAutoComplete2/OptionsList/index.tsx
> +import BaseCheckbox from 'ui-kit/form/shared/BaseCheckbox'
en fait c'est `../../shared/BaseCheckbox` c'est pas génial, non ?

2022-11-08 16:56 UTC, AmineLouveau approved these changes

2022-11-09 10:52 UTC, AmineLouveau requested changes

2022-11-09 10:52 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +          hasError={searchMeta.touched && !!searchMeta.error}
Ici, il manque quelque chose pour que `useScrollToFirstErrorAfterSubmit`

Si le champ est vide, mais qu'il n'y a pas de valeur sélectionnée, alors que le champ est obligatoire, `hasError` devrait être `true` pour que le scroll sur l'erreur se fasse.

2022-11-09 11:00 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +          hasError={searchMeta.touched && !!searchMeta.error}
```suggestion
          hasError={!!meta.error || (searchMeta.touched && !!searchMeta.error)}
```

2022-11-09 12:21 UTC, mariedestandau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +    : !Array.isArray(field.value)
si mais typescript vrille si on ne la met pas parce que le type du champ formik est string | string[]

2022-11-09 12:23 UTC, AmineLouveau commented on pro/src/ui-kit/form/SelectAutoComplete2/SelectAutocomplete.tsx
> +    : !Array.isArray(field.value)
Dans ce cas, je ne comprends pas pourquoi le placeholder n'est jamais utilisé en mode non multi.

2022-11-09 15:51 UTC, AmineLouveau approved these changes

2022-11-09 15:57 UTC, AlbericTrancart approved these changes

2022-11-09 16:01 UTC, rlecellier approved these changes
testé sur le storybook, c'est tout bon.

2022-11-09 16:23 UTC, merged