(PC-18412)[PRO] fix: create offer v3 form category behavior
pass-culture/pass-culture-main pull request #4295
Opened 2022-11-15 16:32 UTC by hugocapuano

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18412

## But de la pull request

- Ne pas afficher le formulaire lorsque l'utilisateur n'a pas sélectionné de sous catégorie.
- Bien afficher la bonne sous catégorie lorsqu'on retourne sur le détail d'une offre.
- Ne pas pouvoir passer à l'étape suivante tant qu'il n'y a pas de sous catégorie séléctionnée.

## Implémentation

- Correction de l'affichage du style des sous catégories.
- N'affiche plus les erreurs lorsqu'on change de sous catégorie.

## Informations supplémentaires

- Lorsque le formulaire n'est pas visible, la page n'affiche plus les erreurs du formulaire lorsqu'on clique sur l'étape suivante, puis qu'on séléctionne une sous catégorie.

## Checklist :

- [X] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`

2022-11-15 17:11 UTC, AmineLouveau requested changes

2022-11-16 09:29 UTC, rlecellier reviewed
Je n'ai pas bien compris d'ou venait le bug, il faut que je teste la branche.
Je reviens vers toi rapidement: )

2022-11-16 09:29 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/validationSchema.ts
>      is: (categoryId: string) => categoryId !== undefined,
L'idée est que lorsqu'on à pas entré de catégorie, on ne veux pas avoir l'erreur 'Veuillez sélectionner une sous-catégorie'
Ton changement vas toujours valider la sous catégorie et donc afficher l'erreur.

2022-11-16 09:29 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/hooks/useSubCategoryUpdates/useSubCategoryUpdates.ts
> -          resetSubCategoryFieldValues()
Lorsqu'on change de sous catégorie, il faut que les `subCategoryFieldValues` soit reset.
Typiquement on a entré un auteur, puis on change pour une sous-catégorie qui n'a pas d'auteur, il faut que auteur soit reset à sa valeur par defaut.

2022-11-16 09:29 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/hooks/useSubCategoryUpdates/useSubCategoryUpdates.ts
> +          setTouched({
Je vais regarder car j'ai du mal à comprendre comment toutched pourrait etre à false

2022-11-16 11:09 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/Categories.tsx
> +    ) {
```suggestion
    if (touched.categoryId) {
```

2022-11-16 11:09 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/Categories.tsx
> +      setFieldTouched('subcategoryId', false)
trop bien, je pense que le bug venait d'ici

2022-11-16 11:09 UTC, rlecellier commented on pro/src/components/OfferIndividualForm/Categories/hooks/useSubCategoryUpdates/useSubCategoryUpdates.ts
>  import { setSubCategoryFields } from 'components/OfferIndividualForm/utils'
J'ai l'impression que tout les changement de ce fichier peuvent etre revert.

2022-11-16 14:27 UTC, rlecellier commented
reprise du fix dans https://github.com/pass-culture/pass-culture-main/pull/4313

2022-11-16 14:27 UTC, closed without merging