(PC-11489) Choose offer type
pass-culture/pass-culture-main pull request #433
Opened 2021-11-12 15:41 UTC by MathildeDuboille

Create screen to choose offer type

2021-11-15 10:32 UTC, gael-boyenval requested changes

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/custom_types/offerType.ts
> +export enum OffreType {
```suggestion
export enum OfferType {
```

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/custom_types/offerType.ts
> +    COLLECTIVE = 'COLLECTIVE'
Je sais pas si c'est à cette terminologie qu'on fait référence, tu as vu ça avec l'équipe ? 
car finalement le individuel peut prendre du `DUO`. Et le collectif, est-ce que ça serait pas plutôt `educational` à coller avec le back et le métier, ça va être assez structurant pour la suite.

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferType.module.scss
> +}
est-ce qu'on aura pas un layout partagé entre le formulaire et cette page ? 
peut-être créer un `new_component` avec ce layout et le bouton `suivant` et `annuler` à réutiliser dans les deux pages ?

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferType.tsx
> +      <h4 className={styles['offer-type-description']}>
```suggestion
      <h2 className={styles['offer-type-description']}>
```

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.tsx
> +  </button>
c'est pas très accessible, soit utiliser un input `radio` soit utiliser un `aria-pressed` (boolean) à set sur le bouton sélectionné. (pour ma part je préfère le radio, car c'est vraiment l'usage que tu cherches à en faire, sélectionner une option ou l'autre)

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.tsx
> +    <p className={styles['button-label']}>
il est invalide au W3C de mettre une balise de type bloc dans une balise inline. (à l'exeption de `<a>` je crois)
```suggestion
    <span className={styles['button-label']}>
```

mais du coup si tu utilises un radio : 


```suggestion
    
    <label>
       <input type radio>
       <Icon/>
       <span/>
    </label>
```

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.module.scss
> +    }
du coup la c'est l'état `is-checked` ? ou l'élément `check-mark`, j'utiliserait plutôt `&-check-mark { ... }` du coup pour rendre l'intention plus claire

2021-11-15 10:32 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.tsx
> +    isSelected: boolean;
4 espaces => 2 espaces (faut vraiment régler cette histoire de pressier, C'est chiant...

2021-11-15 11:21 UTC, MathildeDuboille commented on pro/src/screens/OfferType/OfferType.module.scss
> +}
vu ensemble on ne fait pas pour l'instant :)

2021-11-16 11:38 UTC, gael-boyenval approved these changes

2021-11-16 11:38 UTC, gael-boyenval commented on pro/src/screens/OfferType/OfferTypeButton/OfferTypeButton.module.scss
> +}
```suggestion
    &.is-selected {
        border: 1px solid $primary;
        font-weight: 700;
        color: $primary;
        
        .button-icon {
            fill: $primary;
        }
    } 
}
```

2021-11-16 12:29 UTC, merged