(PC-17089)[PRO] fix: correction design & wording page signup
pass-culture/pass-culture-main pull request #4466
Opened 2022-11-30 10:47 UTC by smokhtari-passculture

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17089

## But de la pull request
Avant :
<img width="230" alt="Capture d’écran 2022-11-30 à 11 37 36" src="https://user-images.githubusercontent.com/119043808/204775064-de0d0d1d-3406-4461-bdfe-bc0f7566e736.png">
Après :
<img width="230" alt="Capture d’écran 2022-11-30 à 11 38 32" src="https://user-images.githubusercontent.com/119043808/204775117-37c01115-0c6c-475a-88ab-e545fc8a17a9.png">

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] Changer la largeur du contenu pour 486 px (idem créa d’offre)
- [x] Supprimer la phrase “Merci de compléter les champs suivants pour créer votre compte. “
- [x] Changer le wording du placeholder mail pour : mail@exemple.com
- [x] Dans le message d’erreur du mail remplacer “mail” par “e-mail”
- [x] Pour le champ téléphone changer le placeholder par 0612345678
- [x] Changer dans tous les placeholder “Mon” par “Votre”
- [x] Les 2 CTA doivent faire la même largeur avec un margin entre eux de 24px
- [x] Descendre le bloc jaune sous les boutons
- [x] Faire attention aux spacing verticaux
- [x] remplacer les picto par les pictos plein dans le texte en caption 
- [x] Remplacer “contactez notre support” par “Contacter notre support”
- [x] Ajouter les icônes au storybook

2022-11-30 11:00 UTC, AmineLouveau requested changes
Il faudra aussi supprimer les fichiers pour les icônes rajoutées, vu qu'ils existent déjà.

2022-11-30 11:00 UTC, AmineLouveau commented on pro/src/ui-kit/Icons/PublicIcons.tsx
> +      <tr>
Cette icône (`IcoExternalSiteRedFilled`) existe déjà dans `pro/src/ui-kit/Icons/Icons.tsx`.

Tu peux voir les icônes existantes en allant sur `http://localhost:6006/?path=/docs/icons-icons--source-icons` après avoir fait un `yarn run storybook`

De plus, le fichier `PublicIcons` est déprécié.

2022-11-30 11:00 UTC, AmineLouveau commented on pro/src/ui-kit/Icons/PublicIcons.tsx
> +        <td>public/icons/ico-mail-red-filled</td>
Pareil ici, l'icône correspond à `IcoMail`, il faudra juste vérifier la couleur de l'icône et la changer en css au besoin.

2022-11-30 12:57 UTC, AlbericTrancart commented on pro/src/pages/Signup/SignupForm/SignupForm.tsx
> -        <h2>Merci de compléter les champs suivants pour créer votre compte.</h2>
Juste un truc d'accessibilité : en regardant dans le DOM de la page tu peux vérifier qu'il n'y a pas de h3 avant le prochain h2 ?
(il ne doit pas y avoir de saut dans les niveaux de titres, par ex pas de h3 après un h1 sans h2)

2022-11-30 16:19 UTC, AmineLouveau reviewed
Pourquoi `pro/public/icons/ico-email-red.svg` a été supprimé ?

2022-11-30 16:32 UTC, smokhtari-passculture commented on pro/src/ui-kit/Icons/PublicIcons.tsx
> +          <Icon svg="ico-external-site-red-filled" />
> Pourquoi `pro/public/icons/ico-email-red.svg` a été supprimé ?

je pensais que c'était moi qui l'avait ajouté, mais au final il n'est pas utilisé dans le projet, je peux le supprimer non ?

2022-11-30 16:34 UTC, AmineLouveau commented on pro/src/ui-kit/Icons/PublicIcons.tsx
> +          <Icon svg="ico-external-site-red-filled" />
Je dirais que oui, mais il vaut mieux vérifier avec quelqu'un de plus ancien. Peut-être que l'icône doit rester au cas où.

2022-12-01 09:54 UTC, rlecellier approved these changes
C'est tout bon, 
juste une propostion a prendre à loisir :)

2022-12-01 09:54 UTC, rlecellier commented on pro/src/components/LegalInfos/LegalInfos.tsx
> +import { ReactComponent as IcoMail } from 'icons/ico-mail.svg'
proposition: ajout dans `icons/index.ts` 
```js
export { ReactComponent as IcoExternalSiteRedFilled } from 'icons/ico-external-site-red-filled.svg'
export { ReactComponent as IcoMail } from 'icons/ico-mail.svg'
```
puis 
```suggestion
import { IcoExternalSiteRedFilled, IcoMail } from 'icons'
```

2022-12-01 09:54 UTC, rlecellier commented on pro/src/styles/components/pages/SignupForm/_SignupForm.scss
> +      gap: rem.torem(24px);
trop bien, je ne connaissait pas :) (j'ai trouvé la [doc](https://coryrylan.com/blog/css-gap-space-with-flexbox) )!

2022-12-01 15:16 UTC, smokhtari-passculture commented on pro/src/components/LegalInfos/LegalInfos.tsx
> +import { ReactComponent as IcoMail } from 'icons/ico-mail.svg'
merci c'est plus propre donc je l'ai ajouté

2022-12-01 15:35 UTC, AmineLouveau approved these changes

2022-12-02 09:43 UTC, merged