(PC-18203) fix synced products thumb storage
pass-culture/pass-culture-main pull request #4486
Opened 2022-12-01 09:51 UTC by francois-seguin

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18203

## But de la pull request

En cas de nouvelle image dans une synchro, elle était uploadée avec un suffixe _1 mais n'était jamais consultée par l'AN ou pc pro.
D'autre part, on uploadait inutilement les images supplémentaires de Titelive, parfois en créant des copies inutiles.

Archéologie: PR qui a introduit la logique d'upload: https://github.com/pass-culture/pass-culture-api/pull/674

## Implémentation

- _Exemples: Ajouts de modèles, de routes, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Modifications du schéma de la base de données

- _Exemples: suppressions de telles colonnes, migration d'une information dans une nouvelle table_
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler l'implémentation technique_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-12-01 16:44 UTC, apibrac requested changes
> on upload désormais au plus 1 image par objet, en écrasant si besoin l'image précédente

Je pense que ça ne colle pas au fonctionnement d'assets web distribués via un CDN : 

Indice 1 : On ne maitrise pas bien le remplacement d'une image par une autre, cela va dépendre de l'expiration des caches et donc de quand l'image a été demandée pour la dernière fois sur chaque noeud (et dans chaque navigateur puisqu'il y a un cache local)

Indice 2 : 
- le coût d'ajout et de stockage d'un asset est minime (c'est ce qui est particulièrement pas cher avec le cloud)
- le coût d'invalidation de cache ne l'est pas forcément, c'est une opération par ailleurs déconseillée par la doc de Cloud CDN l'outil GCP
https://cloud.google.com/cdn/docs/cache-invalidation-overview#limitations
Il est possible que ça soit plus coûteux (coût, consommation, écologie etc) de fonctionner par invalidation plutôt que de créer des nouveaux objets.

Indice 3 : Une partie des fonctionnalités construites par dessus les images se reposent sur le fait qu'elles ne changent jamais, par exemple l'image resizing qui a lui même un cache.
En fonction de quand les caches s'invalident on pourrait donc recevoir une image quand on demande une petite taille et une autre quand on demande une grande taille, ça serait incohérent.

Je recommande donc de ne pas écraser les images qui sont dans le bucket mais plutôt en créer une nouvelle.
=> ce serait possible non ? C'est presque ce qu'il y avait ?

(Si l'idée éttait de minimiser la taille du bucket, je pense il faudrait traiter ce sujet à part avec un système de nettoyage ou d'expiration ?)

2022-12-01 17:48 UTC, francois-seguin commented
> Indice 1 : On ne maitrise pas bien le remplacement d'une image par une autre, cela va dépendre de l'expiration des caches et donc de quand l'image a été demandée pour la dernière fois sur chaque noeud (et dans chaque navigateur puisqu'il y a un cache local)

On fait cela depuis 3 (4?) ans pour les images d'offres créées manuellement et donc uploadées par les AC, et je n'ai pas eu de retour particulier là-dessus.

> Indice 2 :
> le coût d'ajout et de stockage d'un asset est minime (c'est ce qui est particulièrement pas cher avec le cloud)
le coût d'invalidation de cache ne l'est pas forcément, c'est une opération par ailleurs déconseillée par la doc de Cloud CDN l'outil GCP
https://cloud.google.com/cdn/docs/cache-invalidation-overview#limitations
Il est possible que ça soit plus coûteux (coût, consommation, écologie etc) de fonctionner par invalidation plutôt que de créer des nouveaux objets.

Soit, tant mieux si on peut ignorer le coût de stockage

> Indice 3 : Une partie des fonctionnalités construites par dessus les images se reposent sur le fait qu'elles ne changent jamais, par exemple l'image resizing qui a lui même un cache.
En fonction de quand les caches s'invalident on pourrait donc recevoir une image quand on demande une petite taille et une autre quand on demande une grande taille, ça serait incohérent.

Cf point 1: les médiations changent, par design

> Je recommande donc de ne pas écraser les images qui sont dans le bucket mais plutôt en créer une nouvelle.
=> ce serait possible non ? C'est presque ce qu'il y avait ?

Les nouvelles images de synchro (hors titelive) écrasaient le fichier avec suffixe `_1`

-> On devrait faire un chantier dédié à tout cela, mais pour le moment j'ai plusieurs AC qui ont des soucis de mauvaises images synchronisées en prod, donc je préfèrerais merge ces changements, et designer quelque chose de peut-être plus malin plus tard.

2022-12-02 08:01 UTC, apibrac commented
> On fait cela depuis 3 (4?) ans pour les images d'offres créées manuellement et donc uploadées par les AC, et je n'ai pas eu de retour particulier là-dessus.

Non non je pense que tu as mal saisi la fonctionnalité de médiation, je t'invite à faire un test à la main tu devrais identifier l'url de l'image qui change sur pro

> tant mieux si on peut ignorer le coût de stockage

Pareil, c'est une fausse impression d'économie, c'est toujours plus coûteux de mal utiliser un service in fine

Mes 3 "indices" sont plutôt des vrais arguments !

Je comprends qu'il y ait un bug à corriger, mais introduire un bad pattern ne me semble pas adapté, tu vas te retrouver avec d'autres bugs encore plus difficile à maitriser, faisant entrer en compte le CDN ou le cache des navigateurs...

Par contre je ne comprends pas trop pourquoi essayer cette solution te semble mieux, on avait déjà explicité sur slack la correction du bug en gérant bien les images multiples (vu qu'elle sont gérées à l'upload, il _suffit_ de bien gérer à la lecture)
ça semble plus simple que cette pr et plus pérenne non ?

2022-12-05 17:58 UTC, apibrac approved these changes

2022-12-05 17:58 UTC, apibrac commented on api/src/pcapi/models/has_thumb_mixin.py
> +        return f"{self.thumb_path_component}/{humanize(self.id)}"
Est-ce possible d'utiliser `self.thumb_storage_id_suffix` pour que tous se réfèrent à la même définition plutôt que de la recopier ?
Il faut bien s'assurer que le thumbCount est incrémenté avant l'appel à cette fonction

2022-12-05 17:58 UTC, apibrac commented on api/src/pcapi/local_providers/local_provider.py
> +    suffix_str = "" if pc_object.thumbCount == 1 else str(pc_object.thumbCount - 1)
Pareil est ce que ça serait possible de se référer à la même définition écrite dans has_thum_mixin.py ?
Pas forcément dans l'idée de mutualiser au maximum, mais plutôt considérer cette règle comme "métier" donc bien isolée et écrite à un seul endroit pour éviter l'oublie à la prochaine modification

2022-12-05 17:58 UTC, apibrac commented on api/src/pcapi/models/has_thumb_mixin.py
> +        """
Donc une partie de ce code est utilisé par les Venue mais pas la partie pour retrouver l'url ?
Je me rend compte que c'est enregistré en dur dans la db :/
C'est vraiment pas top, le jour où change de nom de domaine par exemple il faudra faire une migration... coupler migration de données à migration d'infra...

Top de l'avoir marqué en tout cas, je vais ping les devs qui l'ont fait

On a vrai enjeu pour simplifier la gestion des images, réussir à intégrer toutes les problématiques de manière propres et bien réutiliser

2022-12-06 09:59 UTC, dbaty approved these changes
J'ai l'impression que c'est correct, mais je connais très mal tout ça, pas facile à relire.

2022-12-06 09:59 UTC, dbaty commented on api/src/pcapi/local_providers/allocine/allocine_stocks.py
> +    def syncs_thumbs(self) -> bool:
(nommage / question de goût) Un nom comme `must_synchronize_thumbs()` indiquerait plus clairement ce que cette méthode renvoie, et éviterait au lecteur pressé de penser qu'elle effectue une action.

2022-12-06 10:16 UTC, francois-seguin commented on api/src/pcapi/local_providers/allocine/allocine_stocks.py
> +    def syncs_thumbs(self) -> bool:
La conjugaison seule du verbe n'est effectivement pas assez explicite.
J'ai un doute sur le verbe modal, je propose `shall_synchronize_thumbs()`

2022-12-07 08:54 UTC, merged