(PC-19202)[PRO] fix: css set correct fields width for stockThing and correct vertical align for stock action
pass-culture/pass-culture-main pull request #4615
Opened 2022-12-12 15:30 UTC by hugocapuano

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19202

## But de la pull request

- Mettre les champs du formulaire stock physique à la bonne taille.
- Bien placer le bouton action pour les stocks à droite de la ligne

## Implémentation

Avant:
![Screenshot from 2022-12-12 16-28-13](https://user-images.githubusercontent.com/106379750/207085103-9bb222f4-8505-4db1-a0d8-ec43eebe8585.png)

Après:
![Screenshot from 2022-12-12 16-20-22](https://user-images.githubusercontent.com/106379750/207085197-a7850da7-a9bf-43cd-86e5-f00ae733e662.png)

## Informations supplémentaires

- Correction de l'alignement pour le bouton action des stocks évènements

Avant:
![Screenshot from 2022-12-12 16-30-26](https://user-images.githubusercontent.com/106379750/207085584-04522ddd-2524-4b74-a9d4-93702d5b2790.png)

Après:
![Screenshot from 2022-12-12 16-19-36](https://user-images.githubusercontent.com/106379750/207085299-56553d95-9e9a-4eb7-918b-7f8972a522c4.png)

2022-12-12 15:37 UTC, AmineLouveau approved these changes

2022-12-12 15:44 UTC, mageoffray requested changes
⚠️ J'ai des styles un peu cassés sur un chromium : 
![Screenshot 2022-12-12 at 16 43 18](https://user-images.githubusercontent.com/95358853/207088767-4e635a91-5dbc-4b3c-9d7c-1efcf098998c.png)
![Screenshot 2022-12-12 at 16 43 32](https://user-images.githubusercontent.com/95358853/207088826-c98ec10e-1014-41ef-b442-011a50d481ac.png)
Bien tester le cas en edition pour voir toutes les colonnes possibles

2022-12-12 15:46 UTC, hugocapuano commented
> 

Oh non, bien vu

2022-12-12 16:48 UTC, hugocapuano commented
Correction lorsqu'il y a un code d'activation
![Screenshot from 2022-12-12 17-47-05](https://user-images.githubusercontent.com/106379750/207104119-8c74cafe-a893-4b67-a242-bdaffd17d129.png)

2022-12-13 08:11 UTC, mageoffray approved these changes
Ca m'a l'air ok 👌

2022-12-13 09:22 UTC, merged