Pc 11419 send dms user message
pass-culture/pass-culture-main pull request #464
Opened 2021-11-16 14:26 UTC by akarki16

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11419

## But de la pull request

Ajout de l'envoie de message d'erreur à l'utilisateur lors d'un dossier "en construction" pour indiquer un email non trouvé, une erreur de pièce d'identité ou de code postal. 

##  Implémentation

- Ajout d'une fonction dans le webhook 
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​

2021-11-16 15:31 UTC, dzen requested changes

2021-11-16 15:31 UTC, dzen commented on api/src/pcapi/routes/external/users_subscription.py
> +    if not user:
Est-ce que tu as pu voir avec Mariam pour conditionner l'envoi des messages à l'état du dossier ?

2021-11-16 15:31 UTC, dzen commented on api/src/pcapi/routes/external/users_subscription.py
> +            raw_data["dossier"]["usager"]["email"],  # application.email
on a pas trop l'habitude de garder des commentaires, git est la pour l'historique

2021-11-16 15:31 UTC, dzen commented on api/src/pcapi/scripts/beneficiary/remote_import.py
> +        client.send_user_message(
du coup, on a X messages envoyés a l'utilisateur, je verrais bien avec Mariam si on en envoie X ou plusieurs

2021-11-16 15:31 UTC, dzen commented on api/tests/routes/external/user_subscription_test.py
> +        breakpoint()
breakpoint() :)

2021-11-16 15:31 UTC, dzen commented on api/tests/routes/external/user_subscription_test.py
> +            id_piece_number="jkfejlkfezjlfejkzlfejzflke",
"wrong_value" serait plus explicite :)

2021-11-17 08:44 UTC, xordoquy reviewed
Je pense qu'il serait aussi grand temps d'ajouter un backend sur le client GraphQL avec un mode de test.

2021-11-17 08:44 UTC, xordoquy commented on api/tests/routes/external/user_subscription_test.py
> +        )
Ce que l'on teste ici n'est pas clair du tout pour moi.

2021-11-17 08:44 UTC, xordoquy commented on api/tests/routes/external/user_subscription_test.py
> +        assert client.execute_query.call_count == 1
Je me pose la question de la pertinence du test. La fonction testée fait 2 lignes et on ne regarde pas les arguments passés.

2021-11-17 08:44 UTC, xordoquy commented on api/src/pcapi/routes/external/users_subscription.py
> +        client.send_user_message(
Est-ce que l'on ne risque pas de spammer l'utilisateur à chaque modification du dossier d'ailleurs ?

2021-11-17 08:44 UTC, xordoquy commented on api/src/pcapi/routes/external/users_subscription.py
>          logger.info(
Est-ce que l'on ne pourrait pas ajouter un peu de contexte avec l'application_id en extra data pour filtrer plus vite sur les logs ? Y a-t-il d'autres infos en extra à ajouter ? La procédure ?

2021-11-17 08:44 UTC, xordoquy commented on api/src/pcapi/routes/external/users_subscription.py
> +            "Cannot parse DMS application %d in webhook. Errors will be handled in the remote_import cron",
les logs comme ça sont des messages techniques. On ne devrait pas avoir besoin de rappeler qu'il y a aussi un cron. Par contre un peu de contexte dans les extras comme l'application_id, l'utilisateur ou autre serait top.

2021-11-17 08:44 UTC, xordoquy commented on api/tests/routes/external/user_subscription_test.py
> +        breakpoint()
```suggestion
```

2021-11-17 08:44 UTC, xordoquy commented on api/tests/routes/external/user_subscription_test.py
> +        breakpoint()
```suggestion
```

2021-11-17 08:44 UTC, xordoquy commented on api/src/pcapi/scripts/beneficiary/remote_import.py
> +            "Bonjour,\nLe champ du code postal doit être rempli par 5 chiffres uniquement, sans lettres ni espace. Si tu as saisi ta ville dans le champ du code postal, merci de ne saisir que ces 5 c
en utilisant les triples quotes et virant les `\n`, on ajouterait de la lisibilité sur le message (idem en dessous).
On pourrait aussi monter ces messages en constantes au début du fichier

2021-11-17 09:48 UTC, dzen commented on api/src/pcapi/routes/external/users_subscription.py
> +        client.send_user_message(
tant qu'il y a des erreurs et a chaque mise à jour du dossier, si, mais est-ce bien grave ?
Idéalement, tant que le dossier est "en construction" et qu'il y fait une modification, il s'agit ici du webhook

2021-11-17 09:48 UTC, dzen commented on api/src/pcapi/routes/external/users_subscription.py
>          logger.info(
+1

2021-11-17 09:48 UTC, dzen commented on api/tests/routes/external/user_subscription_test.py
> +        )
je pense qu'on peut supprimer ce test

2021-11-22 15:25 UTC, xordoquy commented on api/src/pcapi/routes/external/users_subscription.py
> +            "Cannot parse DMS application %d in webhook. Errors will be handled in the remote_import cron",
Ex: https://github.com/pass-culture/pass-culture-api/blob/5e1c07945173f8f909fe917f5da4a314e12d26a4/api/src/pcapi/use_cases/create_beneficiary_from_application.py#L42-L49

2021-11-29 09:31 UTC, merged