(PC-19114)[API] feat: automatic offerer tagging for national partners
pass-culture/pass-culture-main pull request #4773
Opened 2022-12-30 10:58 UTC by Vencespass

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19114

## But de la pull request

Ajout du tag "Partenaire national" et auto taggage des structures correspondantes.

## Implémentation

- Ajout du tag en fonction de l'adresse mail du plus ancien Compte pro rattaché à cette structure.

## Informations supplémentaires

- Ajout du tag "Partenaire national" par requête sql
- Liste des adresses mails considérées comme partenaires nationaux dans un secret.
- Script pout updater les structures existantes :
`from pcapi import settings
import sqlalchemy as sa

import pcapi.core.offerers.models as offerers_models
import pcapi.core.users.models as users_models
from pcapi.models import db

DOMAINS = settings.NATIONAL_PARTNERS_EMAIL_DOMAINS.split(",")

def get_national_partner_tag() -> int:
    tag_id = db.session.execute(
        sa.select(offerers_models.OffererTag.id).filter(offerers_models.OffererTag.name == "partenaire-national")
    ).scalar()
    if not tag_id:
        raise ValueError("The tag 'partenaire-national' doesn't exist")
    return tag_id

def get_offerers() -> list[int]:
    offerers_first_user = (
        sa.select(
            sa.func.min(offerers_models.UserOfferer.id).label("first_user_offerer"),
            offerers_models.UserOfferer.offererId,
        )
        .group_by(offerers_models.UserOfferer.offererId)
        .subquery()
    )
    offerers_to_tag = (
        sa.select(offerers_models.UserOfferer.offererId)
        .join(offerers_first_user, offerers_models.UserOfferer.id == offerers_first_user.c.first_user_offerer)
        .join(users_models.User, users_models.User.id == offerers_models.UserOfferer.userId)
    ).filter(sa.or_(users_models.User.email.endswith(partner_domain) for partner_domain in DOMAINS))

    result = db.session.execute(offerers_to_tag)
    return [offerer[0] for offerer in result]

def create_missing_mappings(dry_run: bool = False) -> str | None:
    tag_id = get_national_partner_tag()
    offerers = get_offerers()

    for offerer_id in offerers:
        print(f"Added tag to {offerer_id}")
        db.session.add(offerers_models.OffererTagMapping(offererId=offerer_id, tagId=tag_id))

    if not dry_run:
        db.session.commit()
    else:
        db.session.rollback()

if __name__ == "__main__":
    from pcapi.flask_app import app
    with app.app_context():
        create_missing_mappings()
`

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [x] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-12-30 11:01 UTC, Vencespass commented
```from pcapi import settings
import sqlalchemy as sa

import pcapi.core.offerers.models as offerers_models
import pcapi.core.users.models as users_models
from pcapi.models import db

DOMAINS = settings.NATIONAL_PARTNERS_EMAIL_DOMAINS.split(",")

def get_national_partner_tag() -> int:
    tag_id = db.session.execute(
        sa.select(offerers_models.OffererTag.id).filter(offerers_models.OffererTag.name == "partenaire-national")
    ).scalar()
    if not tag_id:
        raise ValueError("The tag 'partenaire-national' doesn't exist")
    return tag_id


def get_offerers() -> list[int]:
    offerers_first_user = (
        sa.select(
            sa.func.min(offerers_models.UserOfferer.id).label("first_user_offerer"),
            offerers_models.UserOfferer.offererId,
        )
        .group_by(offerers_models.UserOfferer.offererId)
        .subquery()
    )
    offerers_to_tag = (
        sa.select(offerers_models.UserOfferer.offererId)
        .join(offerers_first_user, offerers_models.UserOfferer.id == offerers_first_user.c.first_user_offerer)
        .join(users_models.User, users_models.User.id == offerers_models.UserOfferer.userId)
    ).filter(sa.or_(users_models.User.email.endswith(partner_domain) for partner_domain in DOMAINS))

    result = db.session.execute(offerers_to_tag)
    return [offerer[0] for offerer in result]


def create_missing_mappings(dry_run: bool = False) -> str | None:
    tag_id = get_national_partner_tag()
    offerers = get_offerers()

    for offerer_id in offerers:
        print(f"Added tag to {offerer_id}")
        db.session.add(offerers_models.OffererTagMapping(offererId=offerer_id, tagId=tag_id))

    if not dry_run:
        db.session.commit()
    else:
        db.session.rollback()


if __name__ == "__main__":
    from pcapi.flask_app import app
    with app.app_context():
        create_missing_mappings()
```

2022-12-30 14:03 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +        )
```python
def add_tag_to_offerer(offerer: offerers_models.Offerer, tag_name: str) -> None:
    tag = offerers_models.OffererTag.query.filter_by(name=tag_name).one_or_none()
    if tag:
        offerer.tags.append(tag)
        db.session.commit()
    else:
        logger.error(
            "Could not assign tag to offerer",
            extra={"offerer": offerer.id, "tag": tag_name},
        )
        return
```

Qu'en penses-tu ?

2022-12-30 14:04 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +        )
Et est-ce que le commit est nécessaire ici ? Est-ce que ce n'est pas à la fonction appelante de gérer ça ?

2022-12-30 14:05 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +        )
Et plutôt qu'un log d'erreur, est-ce qu'il ne vaudrait pas une exception plutôt ? Ce n'est pas censé arrivée, si ?

2022-12-30 14:06 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +        )
Ce qui pourrait donner quelque chose comme : 

```python
def add_tag_to_offerer(offerer: offerers_models.Offerer, tag_name: str) -> None:
    tag = offerers_models.OffererTag.query.filter_by(name=tag_name).one_or_none()
    if not tag:
        raise OfferTagNotFoundError()

    offerer.tags.append(tag)

```

2023-01-02 14:19 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +    if user.email.endswith(national_partners_email_domain):
si on veut autoriser le domaine `super-partenaire.fr`, avec un `endswith` on va se retrouver à autoriser `mon-super-partenaire.fr`, ce qui risque de créer quelques surprises.

2023-01-02 14:24 UTC, Vencespass commented on api/src/pcapi/core/offerers/api.py
> +    if user.email.endswith(national_partners_email_domain):
Si on rajoute l'@ dans les domaines, on ne devrait pas avoir de problème

2023-01-02 17:05 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +    if user.email.endswith(national_partners_email_domain):
Ce n'est pas forcément évident d'inclure le `@` dans ce qui est censé être un nom de domaine, ça risque de créer de la confusion.

Qu'est-ce que tu penses de ne mettre que des (vrais) noms de domaine dans `NATIONAL_PARTNERS_EMAIL_DOMAINS` et pour cette ligne de l'extraire de l'adresse email de l'utilisateur et vérifier qu'il fait partie de ceux autorisés  ?

C'est-à-dire quelque chose qui ressemblerait à ça : 

```python
user_email_domain = user.email.split("@")[-1]  # ou autre chose si tu préfères
national_partners_email_domains = set(settings.NATIONAL_PARTNERS_EMAIL_DOMAINS.split(","))
if user_email_domain in national_partners_email_domains:
    # [...]
```

2023-01-02 17:12 UTC, Vencespass commented on api/src/pcapi/core/offerers/api.py
> +    if user.email.endswith(national_partners_email_domain):
Je vois pas pourquoi c'est gênant d'avoir les @ dans la variable : je loupe quelque chose ? Sinon on peut renommer cette dernière plus clairement, plutôt que de rajouter de la complexité dans l'algo, non ? 
D'autant qu'il faut aussi gérer les cas plus tordus comme `user.name@nom_de_la_ville.nom_du_partenaire` : ça implique d'utiliser `endswith`, avec `.nom_du_partenaire` dans la variable globale.

2023-01-02 17:56 UTC, jeremieb-pass commented on api/src/pcapi/core/offerers/api.py
> +    if user.email.endswith(national_partners_email_domain):
> Je vois pas pourquoi c'est gênant d'avoir les @ dans la variable : je loupe quelque chose ?

Il ne me semble pas que le `@` fasse partie du nom de domaine. J'ai peur que pas mal de personnes ne s'attendent pas à retrouver des noms de domaines avec. Et le risque pour commencer c'est que quelqu'un mette à jour `NATIONAL_PARTNERS_EMAIL_DOMAINS` avec un vrai nom de domaine (sans @) et on risque d'avoir le problème évoqué plus haut.

> plutôt que de rajouter de la complexité dans l'algo, non ?

Qu'est-ce qui te semble complexe ?

> D'autant qu'il faut aussi gérer les cas plus tordus comme user.name@nom_de_la_ville.nom_du_partenaire : ça implique d'utiliser endswith, avec .nom_du_partenaire dans la variable globale.

Certaines entreprises utilisent le format prenom@maboite.fr. Si tu as besoin d'autoriser charles@maboite.fr (par exemple) tu vas aussi autoriser jean.charles@maboite.fr avec un `endswith`.

Si on doit autoriser tous les utilisateurs de maboite.fr, je pense qu'il est plus sûr et surtout plus clair de vérifier exactement le nom de domaine. On garde cette liste de noms de domaine et ensuite on extrait le nom de domaine de l'email on vérifie qu'il fait bien partie de ceux autorisés.

Et si on doit autoriser des utilisateurs spécifiques, utilisons une seconde variable (un second `secret`). Ce sera plus simple à gérer à mon avis.

Ce qui me gène c'est le `endswith`. C'est, à mon sens, un très bon moyen d'avoir de (très) mauvaises surprises un jour.

On en parle de vive voix si tu préfères.

2023-01-04 11:19 UTC, prouzet requested changes

2023-01-04 11:19 UTC, prouzet commented on api/src/pcapi/core/offerers/api.py
> +        add_tag_to_offerer(offerer=offerer, tag_name="partenaire-national")
Afin de grouper tout ce qui concerne les tags automatiques, n'était-il pas possible de l'intégrer à la fonction `auto_tag_new_offerer` utilisée plus haut, en lui passant `user` dans un paramètre supplémentaire ?
Ce qui permettrait aussi d'ajouter le tag pour `create_pro_user_and_offerer` (`core/users/api.py`), cas de création de structure manquant dans cette PR.

2023-01-04 11:19 UTC, prouzet commented on api/tests/core/offerers/test_api.py
> +
Ajouter aussi un test pour vérifier que le tag est bien ajouter si on passe par `create_pro_user_and_offerer` (création de structure à la création de compte pro)

2023-01-04 17:34 UTC, prouzet commented on api/src/pcapi/core/offerers/api.py
> +            raise exceptions.OffererTagNotFoundException(f"Could not assign tag to offerer: {tag_name} not found in DB")
Je serais plutôt d'avis de laisser une erreur dans les logs, à partir de `logger.error`, comme dans la première partie ci-dessus. D'une part par cohérence, et d'autre part pour éviter une erreur 500 pour l'utilisateur du portail pro à la création de la structure, qui le bloque.
L'erreur issue de `logger.error` sera rapportée par Sentry, donc on ne la louper pas.

2023-01-04 17:34 UTC, prouzet commented on api/src/pcapi/core/offerers/api.py
> +        offerer.tags.append(tag)
As-tu bien vérifié que ça suffit sans `db.session.add()` ?

2023-01-05 09:22 UTC, Vencespass commented on api/src/pcapi/core/offerers/api.py
> +        offerer.tags.append(tag)
Vérifié !

2023-01-06 13:08 UTC, prouzet requested changes

2023-01-06 13:08 UTC, prouzet commented on api/src/pcapi/core/offerers/api.py
>                  extra={"offerer": offerer.id, "tag": tag_label},
Copier/coller trop rapide :)
Ça ne va pas passer avec `tag_label`

2023-01-06 13:43 UTC, prouzet approved these changes

2023-01-06 14:07 UTC, merged