(PC-19464)[PRO] fix: allow to delete synchronized offer in edition mode
pass-culture/pass-culture-main pull request #4781
Opened 2023-01-02 15:50 UTC by hugocapuano

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19464

## But de la pull request

- Permettre à l'utilisateur de supprimer un stock synchronisé si possible en ne désactivant pas le bouton supprimer.

## Implémentation

![image](https://user-images.githubusercontent.com/106379750/210253952-ec685ca6-4628-4338-82b7-01051ddb7e11.png)

2023-01-03 08:35 UTC, Aliochka reviewed
à confirmer

2023-01-03 08:35 UTC, Aliochka commented on pro/src/screens/OfferIndividual/StocksEvent/StockFormList/StockFormList.tsx
> +                    disabled: !stockValues.isDeletable || isDisabled,
je crois qu'il faut que ça ne concerne que les stock synchronisée par allociné, les autres stocks restent non supprimable (à confirmer)

il exite un `isAllocineOffer` si tu veux

2023-01-03 08:59 UTC, Aliochka approved these changes
vu avec Pauline sur les specs c'est ok du coup

2023-01-03 09:27 UTC, Aliochka requested changes
en fait faut faire la modif aussi sur les things !

2023-01-03 14:05 UTC, Aliochka approved these changes

2023-01-05 11:13 UTC, AmineLouveau approved these changes

2023-01-05 11:14 UTC, merged