(PC-19172)[PRO] feat: remove CSV_MULTI_DOWNLOAD_BUTTON ff
pass-culture/pass-culture-main pull request #4836
Opened 2023-01-06 16:10 UTC by hugocapuano

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19172

## But de la pull request

- Supprimer la feature flag CSV_MULTI_DOWNLOAD_BUTTON

## Checklist :

- [X] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [X] J'ai écrit les tests nécessaires

2023-01-06 16:14 UTC, AlbericTrancart approved these changes

2023-01-06 16:19 UTC, smokhtari-passculture approved these changes

2023-01-06 16:43 UTC, mageoffray requested changes

2023-01-06 16:43 UTC, mageoffray commented on api/src/pcapi/alembic/versions/sql/schema_init.sql
> -INSERT INTO public.feature VALUES (46, 'ENABLE_CSV_MULTI_DOWNLOAD_BUTTON', 'Active le multi-téléchargement des réservations', true);
⚠️ Ce n'est pas la bonne façon de faire. Le FF ne sera pas supprimé de la base, il faut écrire une migration alembic

2023-01-06 16:45 UTC, mageoffray commented on api/src/pcapi/alembic/versions/sql/schema_init.sql
> -INSERT INTO public.feature VALUES (46, 'ENABLE_CSV_MULTI_DOWNLOAD_BUTTON', 'Active le multi-téléchargement des réservations', true);
En faite à la mise en ligne on ne va pas rejouer le schema_init.sql en base, le FF sera toujours présent. Tu peux t'inspirer de `api/src/pcapi/alembic/versions/20221201T110438_51d8855b12f6_delete_collective_offer_choice_creation_ff.py`
Tu peux retrouver des infos sur comment générer les migrations dans `api/src/pcsapi/alembic/contributing.md`

2023-01-09 09:34 UTC, hugocapuano commented on api/src/pcapi/alembic/versions/sql/schema_init.sql
> -INSERT INTO public.feature VALUES (46, 'ENABLE_CSV_MULTI_DOWNLOAD_BUTTON', 'Active le multi-téléchargement des réservations', true);
Merci je vais regarder ça

2023-01-10 16:03 UTC, merged