(PC-19603)[API] feat: add price category models and creation/edition route
pass-culture/pass-culture-main pull request #5039
Opened 2023-01-24 14:09 UTC by mageoffray

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19603

2023-01-26 13:30 UTC, viconnex commented on api/src/pcapi/core/bookings/models.py
> +    priceCategoryLabel: str = Column(String(20), nullable=True)
str | None

2023-01-26 13:31 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +    priceCategoryId: int = sa.Column(sa.BigInteger, sa.ForeignKey("price_category.id"), index=True, nullable=True)
int | None

2023-01-26 13:36 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +    price_category: sa_orm.Mapped["PriceCategory"] = sa.orm.relationship(
PriceCategory | None

2023-01-26 13:38 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +        "PriceCategory", foreign_keys=[priceCategoryId], backref="stocks"
Je crois qu'il y a pas besoin de spécifier `foreign_keys=`.
Ce serait cool d'homogénéiser le projet mais pour les nouveaux objets on peut utiliser la définition canonique :

<img width="668" alt="image" src="https://user-images.githubusercontent.com/22373097/214849396-528e4258-c0fb-4b23-a1ce-ab457a0d8762.png">

2023-01-26 13:40 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +
ne pas mettre d'espace

2023-01-26 13:42 UTC, viconnex commented on api/src/pcapi/core/offers/api.py
> -from pcapi.core.offers.repository import update_stock_quantity_to_dn_booked_quantity
😌

2023-01-26 13:43 UTC, viconnex commented on api/src/pcapi/core/offers/api.py
> +    validation.check_stock_price(price, offer)
ajouter une validation sur la taille du label ?

2023-01-26 13:44 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
> +@private_api.route("/offers/<offer_id>/price_category", methods=["POST"])
Je crois que c'est plus standard de mettre l'entité au pluriel : 
`"/offers/<offer_id>/price_categories"`

2023-01-26 13:47 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
> +        offers_api.create_price_category(offer, price_category.label, decimal.Decimal(price_category.price))
encapsuler cela dans un `with transaction:`

2023-01-26 13:49 UTC, viconnex commented on api/src/pcapi/core/offers/factories.py
> +    label = "Mon premier tarif"
c'est quoi le label par défaut pour les offres précédentes ?

2023-01-26 13:50 UTC, viconnex commented on api/src/pcapi/core/offers/api.py
> +    modifications: dict[str, typing.Any] = {}
pas besoin de cette variable, si ?

2023-01-26 13:50 UTC, viconnex commented on api/src/pcapi/core/offers/api.py
> +        modifications["label"] = label
vérifier la taille du label ?

2023-01-26 13:51 UTC, viconnex commented on api/src/pcapi/core/offers/factories.py
> +    price_category = factory.SubFactory(PriceCategoryFactory, offer=factory.SelfAttribute("..offer"))
est-ce que ça crée une price_category sur une offre ?

2023-01-26 13:53 UTC, viconnex commented on api/src/pcapi/routes/serialization/offers_serialize.py
> +    id: int
ordre alphabétique

2023-01-26 13:54 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
> +            raise ApiErrors({"price_category_id": ["We cannot find a price_category with this id"]})
erreur en français ?

2023-01-26 13:57 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
> +            offer, price_category_to_create.label, decimal.Decimal(price_category_to_create.price)
Je me demande s'il ne faut pas écrire :
```
Decimal(str(price))
```
En effet 
```
>>> from decimal import Decimal
>>> Decimal(0.4)
Decimal('0.40000000000000002220446049250313080847263336181640625')
>>> Decimal("0.4")
Decimal('0.4')
>>>
```
Il faudra peut-être modifier la route /stocks aussi. Qu'en penses-tu @dbaty ?

2023-01-26 14:01 UTC, viconnex commented on api/src/pcapi/core/offers/repository.py
> +            .options(joinedload(models.Offer.price_categories).joinedload(models.PriceCategory.price_category_label))
On n'a pas besoin de filtre `isSoftDelted = True`, c'est ça ? car à partir du moment où il y a une réservation, on empêche la suppression du label ?

2023-01-26 16:08 UTC, mageoffray commented on api/src/pcapi/core/offers/repository.py
> +            .options(joinedload(models.Offer.price_categories).joinedload(models.PriceCategory.price_category_label))
On empêche la suppression du label dés que l'offre est publiée

2023-01-26 17:34 UTC, mageoffray commented on api/src/pcapi/core/offers/factories.py
> +    price_category = factory.SubFactory(PriceCategoryFactory, offer=factory.SelfAttribute("..offer"))
Non, on créé uniquement un price_category quand on créé un stock

2023-01-27 09:56 UTC, cepehang approved these changes

2023-01-27 09:56 UTC, cepehang commented on api/tests/routes/pro/post_price_categories_test.py
> +    def test_create_too_expansive_price_category(self, client):
```suggestion
    def test_create_too_expensive_price_category(self, client):
```

2023-01-27 10:29 UTC, cepehang commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.status_code == 200
détail, mais le nom de classe de test est `Returns201Test` mais on s'attend à un code 200 ici

2023-01-27 10:56 UTC, cepehang requested changes

2023-01-27 10:56 UTC, cepehang commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.status_code == 400
on devrait laisser les librairies de validation d'entrée d'endpoints renvoyer le code 400 si la requête est malformée

en cas de validation métier échouée, le code 403 Forbidden est plus approprié

2023-01-27 10:56 UTC, cepehang commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.status_code == 401
le code 401 est reservé à une authentification échouée, le code 403 forbidden est plus approprié en cas de validation métier échouée

2023-01-27 14:19 UTC, mageoffray commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.status_code == 400
Vu ensemble. On va laisser une 400 quand les données fournies ne sont pas valides

2023-01-27 14:44 UTC, mageoffray commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.status_code == 401
Oui en effet, d'ailleurs ce test est à coté de la plaque, merci du comm'

2023-01-30 08:29 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +    priceCategory: sa_orm.Mapped["PriceCategory"] | None = sa.orm.relationship(  # type: ignore [misc]
d'où vient ce type: ignore ? on peut pas s'en débarrasser si on type avec : `PriceCategory | None` ou alors avec `Mapped[PriceCat | None]` ?

2023-01-30 08:43 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +
saut de ligne enlevé dans un commit ultérieur ?

2023-01-30 08:44 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +    price: decimal.Decimal = sa.Column(
ordre alphabétix

2023-01-30 08:44 UTC, viconnex commented on api/src/pcapi/core/offers/models.py
> +
pas de saut de \n

2023-01-30 09:24 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
>  @private_api.route("/offers/<offer_id>/price_categories", methods=["POST"])
nom upsert_price_categorie du coup ?

2023-01-30 09:24 UTC, viconnex commented on api/src/pcapi/routes/pro/offers.py
> -    for price_category in body.price_categories:
nom de la méthode : `upsert_price_categorie` du coup ?

2023-01-30 09:27 UTC, viconnex approved these changes
ça peut être cool de squasher les commits, notamment LabelTooLong et la modif du isDuo.

+ ordonner par ordre alphabétique les propriétés
+ enlever les sauts de ligne

2023-01-30 09:37 UTC, cepehang approved these changes

2023-01-30 10:15 UTC, dbaty commented on api/src/pcapi/core/offers/exceptions.py
> +class LabelTooLong(OfferCreationBaseException):
(détail) "label" est peut-être un peu trop vague.

```suggestion
class PriceCategoryLabelTooLong(OfferCreationBaseException):
```

2023-01-30 10:15 UTC, dbaty commented on api/src/pcapi/core/offers/exceptions.py
> +        super().__init__("label", "Le label ne peut dépasser 20 caractères")
(détail) On devrait peut-être plutôt avoir cette vérification dans un validateur pydantic ?

2023-01-30 10:15 UTC, dbaty commented on api/src/pcapi/core/offers/api.py
> +        price_category.priceCategoryLabel.label = label
(question) Idem plus haut, on risque ainsi d'avoir des labels dupliqués. Si le label change, je pense qu'il faudrait faire un `get_or_create()` sur le nouveau label, et lier `price_category` à celui-ci.

2023-01-30 12:14 UTC, mageoffray commented on api/src/pcapi/core/offers/models.py
> +class PriceCategoryLabel(PcObject, Base, Model):
Si, c'est vrai que cette duplication m'embétait, j'aurais du penser à cette réutilisation

2023-01-30 15:54 UTC, dbaty approved these changes

2023-01-30 16:01 UTC, merged