PC-19922 feat: A new feature. allow editing venue linked to offer if …
pass-culture/pass-culture-main pull request #5057
Opened 2023-01-25 16:04 UTC by borisLeBonPro

…offer not used or reimbursed

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19922

## But de la pull request

Autoriser la modification du lieu associé à une offre tant que cette offre n'est pas USED

2023-01-26 09:37 UTC, Meewan requested changes

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_validation_status_if_offer_rejected_or_pending(
Pourquoi avoir renommer la fonction ?

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +        error = ApiErrors()
Je prefererait que ce soit la view qui leve un apiError et que l'api leve une erreur spécifique (déclarée dans educational.exceptiosn.py). ça permet de rendre le code plus reutilisable.

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +        error.add_error("global", "Le nouveau lieu doit avoir le meme offerer")
tu peux faire bien plus simple pour lever une ApiError, tu peux t'inspirer de ce qui est fait ici par exemple:
`api/src/pcapi/routes/pro/collective_offers.py:130`

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +    if offer_to_update.venue.managingOfferer != offerer:
Le test est trop tard, les données sont deja écrite dans la base de données et commités ici. Il faut vérifier AVANT l'appel à _update_collective_offer

Tu peux le vérifier par exemple avec ce snippet:

```
if 'venueId' in new_values: 
    offerer = get_by_collective_offer_id(offer_id)
    new_venue = get_venue_by_id(new_values['venueId'])
    if not venue.managingOffererId == offerer.id:
        raise ...

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_venue_eligibility(offer: Offer | CollectiveOffer | CollectiveOfferTemplate) -> None:
Ce  test ne fait pas ce que tu crois. Pour tester si une venue existe utilises plutot get_venue_by_id ;) (et pas besoin de faire un validateur pour ça)

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_validation_status_if_offer_used_or_reimbursed(
cette fonction ne teste pas du tout le validatioln status, elle teste juste si l'offre à un booking USED ou REIMBURSED

2023-01-26 09:37 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +                    error = ApiErrors()
voir le commentaire précédent sur la façon de lever des ApiErrors

2023-01-26 09:37 UTC, Meewan commented on api/tests/routes/pro/patch_collective_offer_test.py
> +        assert response.status_code == 400
403 serait plus approprié ici ;)

2023-01-26 09:37 UTC, Meewan commented on api/tests/routes/pro/patch_collective_offer_test.py
> +        assert response.status_code == 400
404 serait plus approprié

2023-01-26 15:57 UTC, Meewan requested changes

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_if_offer_used_or_reimbursed(
attention le nom est trompeur. Il laisserait penser que le check vérifie ei le status est user ou reimbursed alors qu'il fait exactement l'inverse.

je te propose ce nom `check_if_offer_not_used_or_reimbursed`

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +        if key == "venueId":
cette fonction n'est pas vraiment le bon endroit pour faire cette verification. Je pense que ce serait plus a sa place dans `update_collective_offer` et `update_collective_offer_template`

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/exceptions.py
> +    def __init__(self) -> None:
Il vaut mieux laisser le corps vide et passer les arguments pertinents a l'appel ;)

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/exceptions.py
> +    def __init__(self) -> None:
Il vaut mieux laisser le corps vide et passer les arguments pertinents a l'appel ;)

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/exceptions.py
> +class OffererOfVenueDontMatchOfferer(OfferCreationBaseException):
Il vaudrait mieux hériter de `Exception` dans ce cas

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/core/offers/exceptions.py
> +class VenueIdDontExist(OfferCreationBaseException):
Il vaudrait mieux hériter de Exception dans ce cas

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"venue": "le lieu doit exister"}, 404)
```suggestion
        raise ApiErrors({"venueId": "le lieu doit exister"}, 404)
```

2023-01-26 15:57 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"offerer": "new venue need to have same offerer"}, 403)
```suggestion
        raise ApiErrors({"venueId": "new venue need to have same offerer"}, 403)
```
c'est le champ venueId qui est fautif

2023-01-27 09:22 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +            new_venue = get_venue_by_id(value)
il vaudrait mieux importer le module que la fonction

2023-01-27 13:23 UTC, Meewan commented
On pourrait profiter de l'occasion pour déplacer les fonction update_collective_offer et update_collective_offer_template vers educational_api. (dans un autre commit en BSR)

2023-01-30 13:12 UTC, Meewan requested changes

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +    if "venueId" in new_values.keys():  # if offer_to_update.venueId in new_values["venueId"]:
plusieur petites remarques: 
1) le `.keys()` ne sert a rien ici:
```suggestion
    if "venueId" in new_values:  # if offer_to_update.venueId in new_values["venueId"]:
```
est tres bien et plus pythonique
2) petite optimisation pour éviter de faire le calcul si on nous passe l'argument mais que la valeur n'a pas changé
```suggestion
    if "venueId" in new_values and new_values["venueId"] != offer_to_update.venueId:
```

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +        offerer = get_by_collective_offer_id(offer_to_update.id)
[style] il vaudrait mieux importer le module, la on ne sait pas ce qu'on recupere.

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +        new_venue = get_venue_by_id(new_values["venueId"])
[style] il vaudrait mieux importer le module

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +def update_collective_offer_template(offer_id: int, new_values: dict) -> None:
pour le venueId il faut faire les mêmes validations sur les offres template que sur les offres collectives

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +def batch_update_offers(query: BaseQuery, update_fields: dict) -> None:
pourquoi déplacer cette fonction dans le fichier ?

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_if_offer_not_used_or_reimbursed(
si c'est que pour les collectives offers, il vaudrait mieux le mettre dans `core/educational/validation.py`

2023-01-30 13:12 UTC, Meewan commented on api/src/pcapi/core/offers/validation.py
> +def check_venue_eligibility(offer: Offer | CollectiveOffer | CollectiveOfferTemplate) -> None:
Cette fonction n'a aucune raison d'être, le venueId ne peut en aucun cas être None  (c'est granti par la db)

2023-01-30 14:46 UTC, borisLeBonPro commented on api/src/pcapi/core/educational/api/offer.py
> +    if "venueId" in new_values.keys():  # if offer_to_update.venueId in new_values["venueId"]:
hummm je ne peux etre d'accord dans le sens ou cette modification du code va entrainer un bug.

En effet, si je place 
```python 
and new_values["venueId"] != offer_to_update.venueId:
```

alors il y aura une incompatibilité car new_values["venueId"] != offer_to_update.venueId est supposé raiser une erreur.

2023-01-30 14:59 UTC, borisLeBonPro commented on api/src/pcapi/core/offers/api.py
> +def batch_update_offers(query: BaseQuery, update_fields: dict) -> None:
Une simple erreur, elle était a l'origine dans ce fichier ( peut etre à un endroit different? ) je l'ai embarqué par erreur avec une autre fonction que j'ai déplacé, mais je l'ai remise, du coup normalement c'est déplacé mais c'est bon car dans le meme fichier ( juste a un endroit different du fchier

2023-01-31 13:50 UTC, Meewan requested changes

2023-01-31 13:50 UTC, Meewan commented on api/src/pcapi/core/educational/validation.py
> +    offer: Offer | CollectiveOffer | CollectiveOfferTemplate,
cette fonction ne prend plus de Offer en entrée

2023-01-31 13:50 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +    if "venueId" in new_values.keys():  # if offer_to_update.venueId in new_values["venueId"]:
cette fonction ne devrait plus exister puisque tu l'as déplacée.Un probleme de rebase ?

2023-01-31 13:50 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
> +    offer: educational_models.CollectiveOffer | educational_models.CollectiveOfferTemplate,
Cette fonction ne devrai plus exister puisque tu l'as déplacée. Un probleme de rebase ?

2023-01-31 13:50 UTC, Meewan commented on api/src/pcapi/core/offers/api.py
>  def batch_update_collective_offers(query: BaseQuery, update_fields: dict) -> None:
cette fonction a été déplacée et devrait donc être enlevée.

La fonction batch_update_collective_offers_templates_ aussidevrait avoir disparu

2023-01-31 14:19 UTC, dbaty commented on api/src/pcapi/core/educational/validation.py
> +        stocks = offer.collectiveStock
(détail / nommage) L'utilisation du pluriel semble indiquer qu'il y a plusieurs éléments, alors que ce n'est pas le cas.

```suggestion
        stock = offer.collectiveStock
```

2023-01-31 14:19 UTC, dbaty commented on api/src/pcapi/core/educational/validation.py
> +                        {"global": ["les offres utilisé ou remboursé ne sont pas modifiable"]}, status_code=400
```suggestion
                        {"global": ["Les offres utilisées ou remboursées ne sont pas modifiables"]}, status_code=400
```

2023-01-31 14:19 UTC, dbaty commented on api/src/pcapi/core/offers/validation.py
> +def check_venue_eligibility(offer: Offer | CollectiveOffer | CollectiveOfferTemplate) -> None:
J'ai l'impression que cette fonction n'est plus utilisée et qu'on pourrait la supprimer, non ? (Je suppose qu'elle l'était dans une précédente version de ta pull request et que tu en as supprimé l'usage suite au commentaire de Raphaël.)

2023-01-31 14:19 UTC, dbaty commented on api/src/pcapi/core/offers/validation.py
> +                    )
On le fait encore parfois ailleurs, mais c'est une mauvaise pratique de lever une exception ApiErrors qui est à destination seulement d'une route HTTP. Or cette fonction est susceptible d'être appelée via d'autres moyens. Il est donc préférable de lever une exception métier et la récupérer dans la route (comme ce que tu as fait avec `OffererOfVenueDontMatchOfferer`).

2023-01-31 14:19 UTC, dbaty commented on api/src/pcapi/routes/serialization/collective_offers_serialize.py
> +    def validate_venue_id(cls, venue_id: int | None) -> int | None:
(question) Je ne comprends pas ce validateur. Le schéma indique `int | None` (ce qui veut dire qu'on autorise une absence de valeur), mais ici on lève une erreur si la valeur est absente. C'est contradictoire. Si l'argument est requis, il suffit de type `venueId: int` (pas besoin de ce validateur).

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    def test_patch_collective_offer(self, client):
(détail / nommage) Puisqu'ici tu testes le cas particulier d'une tentative de modification d'une offre dont une réservation a été validée, le nom du test devrait l'indiquer clairement : 

```suggestion
    def test_cannot_update_offer_with_used_booking(self, client):
```

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    def test_patch_collective_offer_replacing_venue_without_venueId(self, client):
(détail / nommage) "without_venueId" ne me semble pas très clair. Suggestion : "replacing_by_non_unknown_venue"

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            # offer.venueId= 17442
"Code commenté, code à supprimer !" :)

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            interventionArea=["01", "07", "08"],
(détail) À quoi servent tous ces arguments ? S'il n'influe pas sur le comportement du test, il n'y a pas de raison à les spécifier : `CollectiveOfferFactory` devrait avoir des valeurs par défaut raisonnables.

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            # offer.venueId= 17442
"Code commenté, code à supprimer !" :)

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +        )
La date de l'événement ne semble pas utilisée dans le test, il ne me semble donc pas nécessaire de la spécifier : 

```suggestion
        CollectiveBookingFactory(collectiveStock__collectiveOffer=offer)
```

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +        )
Ce test a le même comportement sans ou avec la réservation, ça n'est pas ce que l'on teste ici. Donc autant supprimer ces données. Ça rend la lecture du test plus claire : le lecteur n'a pas besoin de se dire "hmm, pourquoi créé-t-on une réservation ici ? Est-ce qu'on n'aurait pas le même comportement sans réservation ?"

```suggestion
```

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +        )
idem plus haut

```suggestion
```

2023-01-31 14:19 UTC, dbaty commented on api/tests/routes/pro/test_boris.py
> +import pytest
Si ce fichier doit rester, il faudrait le renommer. ;)

2023-01-31 17:17 UTC, Meewan commented on api/src/pcapi/core/educational/validation.py
> +                        {"global": ["les offres utilisé ou remboursé ne sont pas modifiable"]}, status_code=400
et une phrase se termine toujours par un point ^^

2023-01-31 17:20 UTC, Meewan commented on api/src/pcapi/routes/serialization/collective_offers_serialize.py
> +    def validate_venue_id(cls, venue_id: int | None) -> int | None:
Non en pratique dans ce cas le validateur ne sera présent que si la valeur est transmise (le | None permet aussi bien de passer la valeur a NULL que de ne pas la passer. On accepte qu'il ne la passe pas mais pas qu'il passe NULL)

2023-02-01 10:27 UTC, Meewan requested changes

2023-02-01 10:27 UTC, Meewan commented on api/src/pcapi/core/educational/validation.py
> +                    {"global": ["Les offres utilisées ou remboursées ne sont pas modifiable."]}, status_code=400
Je suis d'accord avec Damien, cette fonction devrait lever une Exception classique qui devrait être transformée en ApiError par la route.

2023-02-01 10:27 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +from pcapi.core.offerers import repository
```suggestion
from pcapi.core.offerers import repository as offerers_repository
```

Sinon on ne sait pas de quel repository il est question.

2023-02-01 10:27 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
>  from pcapi.core.users.models import User
```suggestion
from pcapi.core.offers. import models as offers_models
```
et revoir la ou User et OfferValidationStatus sont utilisés

2023-02-01 10:27 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +            raise offers_exception.OffererOfVenueDontMatchOfferer()
Une petite optimisation au cas ou la venue n'existe pas

```suggestion
        new_venue = repository.get_venue_by_id(new_values["venueId"])
        if not new_venue:
            raise offers_exception.VenueIdDontExist()
        offerer = repository.get_by_collective_offer_id(offer_to_update.id)
        if new_venue.managingOffererId != offerer.id:
            raise offers_exception.OffererOfVenueDontMatchOfferer()
```

2023-02-01 10:27 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +            raise offers_exception.OffererOfVenueDontMatchOfferer()
Une petite optimisation au cas ou la venue n'existe pas

```suggestion
        new_venue = repository.get_venue_by_id(new_values["venueId"])
        if not new_venue:
            raise offers_exception.VenueIdDontExist()
        offerer = repository.get_by_collective_offer_id(offer_to_update.id)
        if new_venue.managingOffererId != offerer.id:
            raise offers_exception.OffererOfVenueDontMatchOfferer()
```

2023-02-01 10:27 UTC, Meewan commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    def test_patch_collective_offer_replacing_by_non_unknown_venue(self, client):
```suggestion
    def test_patch_collective_offer_replacing_by_unknown_venue(self, client):
```
typo

2023-02-01 13:02 UTC, Meewan requested changes

2023-02-01 13:02 UTC, Meewan commented on api/src/pcapi/admin/custom_views/offerer_view.py
> +from pcapi.core.offerers import offerers_repository
à revert

2023-02-01 16:32 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_stocks.py
> +from pcapi.core.offerers import repository
```suggestion
from pcapi.core.offerers import repository as offerers_repository
```

2023-02-05 21:06 UTC, closed without merging