(PC-19605)[API] feat : link price_category to stock on creation and edition
pass-culture/pass-culture-main pull request #5150
Opened 2023-02-02 09:21 UTC by mageoffray

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-19605

2023-02-06 15:41 UTC, cepehang requested changes

2023-02-06 15:41 UTC, cepehang commented on api/src/pcapi/core/offers/api.py
> +    if price not in (UNCHANGED, None) and price != stock.price:
```suggestion
    if price is not UNCHANGED and price is not None and price != stock.price:
```
je suis d'accord que c'est moins élégant mais mypy est content comme ça et tu peux retirer des `ignore` plus bas

2023-02-06 15:41 UTC, cepehang commented on api/src/pcapi/core/offers/factories.py
> +    priceCategory = factory.Maybe(
pourquoi ajouter un `Maybe` plutôt que bouger ce champ dans le `EventStockFactory` plus bas ?

2023-02-06 15:41 UTC, cepehang commented on api/tests/routes/pro/post_stocks_test.py
> +    def test_edit_one_event_stock_created_without_price_category(self, mocked_async_index_offer_ids, client):
ce test et celui d'au dessus testent tous les deux des stocks créés sans catégorie de prix

je propose les noms `test_edit_one_event_stock_using_price(_category)`

2023-02-06 15:41 UTC, cepehang commented on api/tests/routes/pro/post_stocks_test.py
> +    def test_update_product_stock_without_price_is_forbidden(self, app):
ce test est identique à celui au dessus, il est amené à disparaître quand on supprimera le feature flag ?

2023-02-06 15:41 UTC, cepehang commented on api/src/pcapi/core/offers/validation.py
> +                {"price": ["Le prix est obligatoire pour les offres produit"]},
c'est pas grave si le mot `produit` apparaît quand le feature flag est désactivé et qu'on ne reçoit pas de `stock.price` pour un évènement ?

2023-02-07 10:43 UTC, mageoffray commented on api/src/pcapi/core/offers/factories.py
> +    priceCategory = factory.Maybe(
En faite il y a `EventStockFactory` et `CinemaStockProviderFactory` qui sont des évènement. 
Je me dit qu'au niveau du stock ça évite de dupliquer et d'oublier

2023-02-07 10:48 UTC, mageoffray commented on api/src/pcapi/core/offers/api.py
> +    price_category = models.PriceCategory.query.filter_by(price=price, offer=offer).one_or_none()
Bien vu, en effet 👍

2023-02-07 10:55 UTC, mageoffray commented on api/src/pcapi/core/offers/validation.py
> +                {"price": ["Le prix est obligatoire pour les offres produit"]},
Boh, je me suis dit qu'on aurait vite fait d'oublier de le modifier quand on supprimera le FF. 
Le front marche bien et ne devrait jamais afficher vraiment ce message

2023-02-07 11:25 UTC, mageoffray commented on api/tests/routes/pro/post_stocks_test.py
> +    def test_update_product_stock_without_price_is_forbidden(self, app):
Yes, c'est pour valider le comportement dans les 2 états du FF

2023-02-08 10:57 UTC, cepehang commented on api/src/pcapi/core/offers/factories.py
> +    priceCategory = factory.Maybe(
`CinemaStockProviderFactory` peut hériter directement de `EventStockFactory`

```python
class EventStockFactory(StockFactory):
    offer = factory.SubFactory(EventOfferFactory)
    beginningDatetime = factory.LazyFunction(lambda: datetime.datetime.utcnow() + datetime.timedelta(days=30))
    bookingLimitDatetime = factory.LazyAttribute(lambda stock: stock.beginningDatetime - datetime.timedelta(minutes=60))


class CinemaStockProviderFactory(EventStockFactory):
    beginningDatetime = factory.LazyFunction(
        lambda: datetime.datetime.utcnow().replace(second=0, microsecond=0) + datetime.timedelta(days=30)
    )
```

```python
class ChildFactoryFieldOverrideTest:
    @pytest.mark.usefixtures("db_session")
    def test_child_field_overrides_parent_field(self):
        cinema_stock = offers_factories.CinemaStockProviderFactory()

        beginning_datetime = cinema_stock.beginningDatetime
        assert beginning_datetime.second == 0
        assert beginning_datetime.microsecond == 0
```

2023-02-08 12:37 UTC, mageoffray commented on api/src/pcapi/core/offers/factories.py
> +    priceCategory = factory.Maybe(
J'ai pris cette remarque dans [la pr](https://github.com/pass-culture/pass-culture-main/pull/5218) qui modifie la sandbox

2023-02-08 15:58 UTC, cepehang approved these changes

2023-02-09 09:17 UTC, merged