--wip-- [skip ci]
pass-culture/pass-culture-main pull request #517
Opened 2021-11-19 15:09 UTC by gvannest

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

(Ajout de fonctionnalités, Problèmes résolus, etc)

##  Implémentation

- (Ajouts de modèles, Changements significatifs)
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-11-22 13:55 UTC, gael-boyenval requested changes
se serait pas mal d'avoir un micro test pour tester l'affichage des champs, et si possible de récupérer le layout de form sur cette PR en cours ici : https://github.com/pass-culture/pass-culture-main/pull/530/files pour l'intégrer à celle-ci

2021-11-22 13:55 UTC, gael-boyenval commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
> +          initialValues={{}}
se serait pas mal d'avoir toutes les initial values ici, au lieu de clé/values undefined

2021-11-22 13:55 UTC, gael-boyenval commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
> +          {isOfferDraft ? 'Valider et créer l’offre' : 'Enregistrer'}
je pense pas qu'on ai validé cette notion en V0.1 si ?

2021-11-22 13:58 UTC, gael-boyenval requested changes

2021-11-22 13:58 UTC, gael-boyenval commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
> +  const hasNoStock = false
dans tous les cas ça va venir des props ça, du coup tu peux ajouter les props + signature typescript

2021-11-22 15:42 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/FormStock/FormStock.tsx
> +        name="event_date"
plutôt du camelCase et on fera le mapping avec les noms des champs attendus par le back au moment du submit :)

2021-11-22 15:44 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.module.scss
> +  button,
est ce que tu peux plutôt utiliser des noms de classe plutôt que des tags ? :) il peut y avoir des conflits si jamais tu as 2 boutons dans le même container mais que tu ne veux pas appliquer le même style

2021-11-22 15:48 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
> +          }}
```suggestion
          {() =>  <FormStock />}
```

c'est du détail mais c'est plus court :p

2021-11-22 15:49 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.tsx
> +          {isOfferDraft ? 'Valider et créer l’offre' : 'Enregistrer'}
J'imagine que c'est par rapport à l'édition de l'offre :) du coup si ?

2021-11-22 17:21 UTC, gael-boyenval commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.module.scss
> +  button,
de toute façon il devrait pouvoir réutiliser les composants FormLayout qui viennent d'être mergés :)

2021-11-23 10:33 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.module.scss
> +  button,
Ah yes j'avais fait un copié-collé du style du formulaire individuel, et je ne m'étais pas rendu compte qu'il utilisait des tags! Mais yes je vais utiliser le layout de Gaël

2021-11-25 10:47 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/FormStock/FormStock.tsx
> +        className={styles['section']}
je trouve que le nom de classe est pas très adapté, `form-field` ca t'irait comme naming ? ou autre chose qui colle plus à l'élément :)

2021-11-25 10:48 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
> +    onSubmit={values => console.log(values)}
ici tu peux utiliser `action('onSubmit')` avec action qui vient de `storybook/addon-action` :)

2021-11-25 10:53 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
> +    onSubmit={values => console.log(values)}
Ah non mais c'est là où tu voulais logger pour vérifier que ca marchait bien, je croyais que c'était plutôt à faire sur la page

2021-11-25 11:03 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/FormStock/FormStock.tsx
> +        className={styles['section']}
Yes, je me disais que `section` du formulaire stock c'était pas mal, mais `form-field` ça me va oui, ça colle davantage à l'élément

2021-11-25 11:06 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/OfferEducationalStock.stories.tsx
> +    onSubmit={values => console.log(values)}
Ah okay, il fait quoi exactement le `action` du storybook déjà (je crois que tu m'avais expliqué mais ma mémoire me fait défaut)?
@gael-boyenval me disait de pouvoir tester le composant, mais peut-être que le console log à cet endroit n'est pas idéal?

2021-11-25 15:48 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/FormStock/FormStock.module.scss
>  }
il te manque une ligne à la fin :) bizarre qu'eslint ne t'ait pas fait le format on save, peut etre un truc qui manque dans la config de ton vscode

2021-11-25 15:52 UTC, MathildeDuboille commented on pro/src/routes/OfferEducationalStockCreation/OfferEducationalStockCreation.tsx
> +  const urlParams: URLSearchParams = new URLSearchParams(location.search)
l'offer Id est pas dans les query params il me semble :) je pense que tu peux utiliser
```
import { useParams } from "react-router-dom";
...
const {offerId} = useParams<{offerId: string}>()
```

2021-11-25 15:55 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/FormStock/FormStock.module.scss
>  }
Pourtant ça a passé la CI de qualité! 😕

2021-11-25 15:56 UTC, gvannest commented on pro/src/routes/OfferEducationalStockCreation/OfferEducationalStockCreation.tsx
> +  const urlParams: URLSearchParams = new URLSearchParams(location.search)
Ah d'accord 😅
J'ai vu qu'on utilisait le new URLSearchParams à plusieurs endroits;
Merci pour le tip en effet c'est bien plus propre

2021-11-25 16:11 UTC, MathildeDuboille approved these changes

2021-11-25 16:38 UTC, gael-boyenval requested changes
pas loin, désolé...

2021-11-25 16:38 UTC, gael-boyenval commented on pro/src/screens/OfferEducationalStock/types.ts
> +  status: string
désolé pour la validation sans réserve : 

```suggestion
  status: OfferStatus
```

et autre part 

```ts
type OfferStatus =  'ACTIVE' | 'INACTIVE' | 'SOLD_OUT' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'DRAFT'
```

et aussi : 

```ts
export const OFFER_STATUS_ACTIVE: OfferStatus = 'ACTIVE'
 export const OFFER_STATUS_INACTIVE: OfferStatus = 'INACTIVE'
 export const OFFER_STATUS_SOLD_OUT: OfferStatus = 'SOLD_OUT'
 export const OFFER_STATUS_EXPIRED: OfferStatus = 'EXPIRED'
 export const OFFER_STATUS_PENDING: OfferStatus = 'PENDING'
 export const OFFER_STATUS_REJECTED: OfferStatus = 'REJECTED'
 export const OFFER_STATUS_DRAFT: OfferStatus = 'DRAFT'
```

2021-11-25 16:42 UTC, MathildeDuboille commented on pro/src/screens/OfferEducationalStock/types.ts
> +  status: string
tant qu'à faire un enum non ? 😇😇😇😇😇😇😇😇😇 ca fait les 2 à la fois

2021-11-25 16:42 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/types.ts
> +  status: string
J'avoue, j'ai été mauvais

2021-11-25 16:43 UTC, gvannest commented on pro/src/screens/OfferEducationalStock/types.ts
> +  status: string
@MathildeDuboille tu es sensée prendre ma défense!!! Pas me rajouter du taf!! 😭

2021-11-26 11:10 UTC, merged