(PC-18475)[BO] feat: suspend and unsuspend user (beneficiary, gp, pro)
pass-culture/pass-culture-main pull request #5192
Opened 2023-02-03 17:35 UTC by prouzet

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-18475

## But de la pull request

Ajouter les boutons de suspension et réactivation de compte utilisateur dans le backoffice v3.
Fonctionnalité similaire à Flask-Admin et réservée à l'équipe Fraude & Conformité (comme la revue manuelle).

## Implémentation

Plus de détails sur les spécifications dans le ticket.

À noter : j'ai renommé une permission, qui se retrouvera donc nouvelle, et sera à réaffecter dans les rôles sur les différents environnements.

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2023-02-06 13:25 UTC, Vencespass approved these changes
Juste un minuscule commentaire :)
Tu as des `flash` où les phrases ont un point à la fin, et d'autres non; il faut peut-être uniformiser ? (pas dans ce ticket)

2023-02-07 15:43 UTC, mlachevre-pass requested changes
Le workflow que tu supprimes est actuellement appelé dans test-main.yml et fait donc échoué cette [action](https://github.com/pass-culture/pass-culture-main/actions/runs/4104172762) (normal vu qu'il n'est plus présent)
Si tests-backoffice-v3.yml est censé remplacé ce workflow il faut aussi que tu edit test-main.yml

2023-02-07 15:50 UTC, prouzet commented
> Le workflow que tu supprimes est actuellement appelé dans test-main.yml et fait donc échoué cette [action](https://github.com/pass-culture/pass-culture-main/actions/runs/4104172762) (normal vu qu'il n'est plus présent) Si tests-backoffice-v3.yml est censé remplacé ce workflow il faut aussi que tu edit test-main.yml

Les tests du backoffice v3 sont déjà dans la chaîne d'intégration continue.
Je désactive ceux du backoffice v2, qui cohaitaient. La v2 va disparaître car n'est plus utilisée.

2023-02-07 16:00 UTC, prouzet commented
> > Le workflow que tu supprimes est actuellement appelé dans test-main.yml et fait donc échoué cette [action](https://github.com/pass-culture/pass-culture-main/actions/runs/4104172762) (normal vu qu'il n'est plus présent) Si tests-backoffice-v3.yml est censé remplacé ce workflow il faut aussi que tu edit test-main.yml
> 
> Les tests du backoffice v3 sont déjà dans la chaîne d'intégration continue. Je désactive ceux du backoffice v2, qui cohaitaient. La v2 va disparaître car n'est plus utilisée.

Confusion ; en fait je laisse pour l'instant les tests backend v2, ce ne sont que les tests front v2 que je veux supprimer : `tests-backoffice-front-unit-tests`. Ça devrait désormais être bon.

2023-02-07 16:10 UTC, mlachevre-pass approved these changes

2023-02-07 16:10 UTC, merged