(PC-20019)[API] feat:
pass-culture/pass-culture-main pull request #5193
Opened 2023-02-03 19:00 UTC by borisLeBonPro

Prevent deregistered users from re-activating their deactivated offers

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20019

## But de la pull request

empecher les utilisateurs non enregistré de réactiver leur offre désactivé

2023-02-05 09:58 UTC, dbaty requested changes

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offers_active_status_test.py
> +from tests.conftest import TestClient
On ne doit plus utiliser `TestClient`. La fixture pytest `client` est équivalente et doit être utilisée.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offers_active_status_test.py
> +class MockMoiCa:
? Est-ce le nom définitif ? Cette classe (et sa fonction de test) sera ignorée par pytest (cf. la [configuration de pytest](https://github.com/pass-culture/pass-culture-main/blob/21773b12d1464af82a687c71ae3adbcc6374582b/api/pyproject.toml#L181)).

2023-02-05 09:58 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +                offerers_api.can_offerer_create_educational_offer(offerer_id)
On va faire une requête HTTP vers Adage par offre, alors qu'il est très probable que toutes les offres sont liées à la même structure. On pourrait plutôt d'abord récupérer l'ensemble des structures distinctes, puis itérer dessus : 

```python
    offerer_ids = set()
    for offer_id in body.ids:
        offerer_ids.add(...)
    for offerer_id in offerer_ids:
        can_offerer_create_educational_offer(offerer_id)
        ...
```

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +from tests.conftest import TestClient
On ne doit plus utiliser `TestClient`. La fixture pytest `client` fait la même chose.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            "offererId": user_offerer.offerer.id,
(détail) On a déjà accès à `offerer`. Pas besoin d'utiliser la variable `user_offerer`. C'est plus concis.

```suggestion
            "offererId": offerer.id,
```

Idem dans d'autres fonctions de test que tu as ajoutées.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    def when_activating_all_existing_offers_work(self, app):
Ce test vérifie la route `/collective/offers/all-active-status`. Ça n'est pas le bon module de test. Le bon module est `patch_all_collective_offers_active_status_test.py` (qui doit sûrement déjà contenir un tel test de base).

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            response = client.patch("/collective/offers/all-active-status", json=data)
idem plus haut, ça n'est pas le bon fichier de test.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offers_active_status_test.py
> +    def when_activating_all_existing_offers_active_status(self, app):
Idem plus haut, cette fonction devrait être dans un autre fichier de test.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +            "venueId": humanize(venue.id),
Est-ce que ces deux arguments sont nécessaires au test ? Si ça n'est pas le cas, supprimons-les. (J'ai même un doute sur `page`, il n'a pas l'air d'être dans les arguments possibles pour cette route...)

Idem dans les autres tests : il est important qu'un test soit le plus court et clair possible. Ajouter des données ou des arguments inutilisées rend le test plus complexe à lire. Le lecteur se demande : "est-ce que cet argument change quelque chose au test ?"

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offer_test.py
> +    def when_activating_all_existing_offers_fail(self, app):
"fail" n'est pas assez précis.

2023-02-05 09:58 UTC, dbaty commented on api/tests/routes/pro/patch_collective_offers_active_status_test.py
> +    def when_activating_all_existing_offers_active_status_fail(self, app):
idem plus haut : "fail" n'apporte aucune information sur que l'on teste vraiment. Et "activating_all_existing_offers_active_status" non plus, puisque c'est la seule fonctionnalité testée dans ce fichier.

2023-02-07 09:39 UTC, Meewan requested changes
Les offres templates sont pas concernés ?

2023-02-07 09:39 UTC, Meewan commented on api/src/pcapi/core/offerers/api.py
> +from pcapi.core.offerers import exceptions
Pourquoi changer cet import ? l'import relatif posait des problemes ?

2023-02-07 09:39 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +            offer = educational_repository.get_collective_offer_by_id(offer_id)
En général on essaye autant que possible de faire des requetes SQL dans des boucles.

Ici on pourrait faire une fonction dans offerers/repository.py qui ressemblerait a ça:

```
def get_offerer_ids_from_collective_offers_ids(offers_ids) -> set[int]:
    query = db.query(Offere.id)
    query = query.join(Venue, Offerer.managedVenues)
    query = query.join(CollectiveOffer, Venue.collectiveOffers)
    query = query.filter(CollectiveOffer.id.in_(offers_ids)
    return set(query.all())
```

Pour faire exactement la même chose que la boucle mais bien plus vite et en chargeant moins la bdd

2023-02-09 09:25 UTC, Meewan requested changes

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/core/offerers/api.py
> +
pourquoi modifier une ligne dans un fichier qui n'a pas changé autrement ?

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/core/educational/repository.py
> +    query = db.session.query(offerers_models.Offerer)
```suggestion
    query = db.session.query(offerers_models.Offerer.id)
```
Pas besoin de remonter tout l'objet, l'id suffit (et ça va plus vite) et ce serait plus raccord avec le type déclaré

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/core/educational/repository.py
> +    return set(query.all())
```suggestion
    return {result[0] for result in query.all()}
```

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +        offers = educational_repository.get_offerer_ids_from_collective_offers_ids(body.ids)
c'est des offerers_id pas des offers ;)

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +        for offer in offers:
```suggestion
        for id in offerers_id:
```

2023-02-09 09:25 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +        offers = educational_repository.get_offerer_ids_from_collective_offers_ids(body.ids)
Attention tu manipules de collective offers template ici, pas des collective offers. Il faut écrire une autre fonction qui travail a partir des collective offers template (mais qui sera presque la même sur tout le reste)

2023-02-09 09:46 UTC, borisLeBonPro commented on api/src/pcapi/core/offerers/api.py
> +
un breakpoint, c'est resté comme une modification en l'effacant

2023-02-09 15:21 UTC, Meewan requested changes
il manque encore patch_collective_offers_template_active_status mais sinon on s'approche du but

2023-02-09 15:21 UTC, Meewan commented on api/src/pcapi/core/offerers/api.py
> +
il faudrait enlever la ligne vide rajoutée (pour la propreté)

2023-02-09 15:21 UTC, Meewan commented on api/src/pcapi/routes/pro/collective_offers.py
> +            raise ApiErrors({"Partner": ["User not in Adage can't edit the offer"]}, status_code=403)
```suggestion
            raise ApiErrors({"offerer_id": ["The offerer is not approved by adage."]}, status_code=403)
```

2023-02-15 09:21 UTC, Meewan requested changes
Il manque des tests pour 
- le cas d'erreur quand on essayes d'activer plusieurs offres template
- quand on essaye d'activer une offre
- quand on essaye d'activer une offre template

(ou alors je les ai raté)

2023-02-15 09:21 UTC, Meewan commented on api/tests/routes/pro/patch_all_collective_offers_active_status_test.py
> +        assert response.json == {"offerer_id": ["The offerer is not approved by adage."]}
il faudrait vérifier en base que l'offre n'ai pas été reactivé.

2023-02-15 09:21 UTC, Meewan commented on api/tests/routes/pro/patch_all_collective_offers_active_status_test.py
> +    def test_when_activating_all_existing_offers_active_status(self, client):
on a pas deja un test pour ce cas ?

2023-02-15 09:21 UTC, Meewan commented on api/tests/routes/pro/patch_all_offers_active_status_test.py
> +        assert response.json == {"offerer_id": ["The offerer is not approved by adage."]}
quelle est la différence avec les tests du fichier au dessus ? sauf erreuron appele la même route.

2023-02-16 14:00 UTC, Meewan approved these changes
commit a squash

2023-02-20 15:18 UTC, dbaty approved these changes

2023-02-20 15:18 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +    if body.is_active == True:
(détail / style) `is_active` est un booléen non nullable, on peut écrire ça plus simplement :

```suggestion
    if body.is_active:
```

idem dans les autres routes

2023-02-20 15:18 UTC, dbaty commented on api/tests/routes/pro/patch_all_collective_offers_active_status_test.py
> +            "venueId": humanize(venue.id),
(détails) `venueId` ne me semble pas nécessaire à ce test. De plus, je ne vois pas `page` dans le schéma. À supprimer ?

```suggestion
```

Idem les autres tests que tu as ajoutés.

2023-02-21 09:57 UTC, merged