(PC-20210)[API] feat: Profil jeune - Lien vers le second profil en cas de doublon
pass-culture/pass-culture-main pull request #5278
Opened 2023-02-13 21:20 UTC by akarki16

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20210

## But de la pull request

En tant que support jeune
J'aimerais accéder au profil doublon depuis le profil d’un jeune
Afin de gagner du temps

## Implémentation

- L’onglet par défaut lorsqu’on arrive sur le profil jeune doit être “Informations personnelles” (et non plus “Historique du compte)
- Sur le profil jeune, lorsqu’un doublon est identifié par Ubble (ID doublon visible dans le bloc “ubble”) : 
    - Remonter l’information du second ID dans le bloc d’informations générales en haut de page => User ID doublon : xxxxx
        - L’afficher uniquement en cas de doublon
    - Rendre cliquable cet ID doublon pour rediriger l’utilisateur vers le profil du doublon

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [x] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

<img width="797" alt="Capture d’écran 2023-02-13 à 22 20 16" src="https://user-images.githubusercontent.com/9610732/218577049-b2eb266f-404f-45ea-b38a-c0ed26efdd97.png">

2023-02-14 14:55 UTC, Vencespass commented on api/src/pcapi/routes/backoffice_v3/accounts.py
> +    for eligibility_type in users_models.EligibilityType:
Ça aurait peut-être été plus beau/lisible dans une méthode séparée ?

2023-02-14 14:59 UTC, Vencespass approved these changes

2023-02-14 15:35 UTC, prouzet requested changes

2023-02-14 15:35 UTC, prouzet commented on api/src/pcapi/core/fraud/api.py
> +            detail=f'Duplicat de l\'utilisateur <a class=\'link-primary\' href="{utils_urls.build_backoffice_public_account_link(duplicate_user.id)}" target="_blank">{duplicate_user.id}</a>',
La mise en forme html dans le module core.fraud.api ne me semble pas du tout une bonne idée.
On est ici dans la logique, pas dans la mise en forme, d'autant plus avec des liens spécifiques backoffice.
Ne stockons pas ce html dans la base de données !

2023-02-14 15:35 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
> +                        <small><a href="{{ duplicate_user_id | pc_backoffice_public_account_link }}" target="_blank">User ID
Souhaite-t-on vraiment ouvrir dans un nouvel onglet alors qu'on reste dans le BO ?

2023-02-14 15:35 UTC, prouzet commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                <td>{{ review.reason | safe }}</td>
Ici au lieu d'appeler `safe`, je verrais plutôt une mise en forme permettant d'extraire les id et leur appliquer des liens.

2023-02-14 15:35 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/accounts.py
> +    for eligibility_type in users_models.EligibilityType:
Oui, mais surtout, veut-on effectivement mesurer les doublons de toute éligibilité, ou seulement de l'éligibilité courante ? (ou la dernière)

Une idée serait de n'afficher que les doublons bloquant l'éligibilité actuelle, donc en ne cherchant que pour l'éligibilité renvoyée par :
`users_api.get_eligibility_at_date(user.birth_date, datetime.datetime.utcnow())` (si non nulle)
qui est d'ailleurs peut-être tout simplement : `user.eligibility` (à vérifier)

2023-02-14 15:35 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/accounts.py
> +                and item.status != subscription_models.SubscriptionItemStatus.OK.value
on peut aussi filtrer les reasonCodes ici, et trier par date décroissante, pour ne garder que le premier, qui sera le seul vérifié plus bas

2023-02-14 15:55 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/templates/accounts/get/general.html
> +                        <small><a href="{{ duplicate_user_id | pc_backoffice_public_account_link }}" target="_blank">User ID
Oui vu avec Michael. Le but étant d'avoir les deux profils sur deux onglets pour comparer.

2023-02-15 17:51 UTC, prouzet commented on api/src/pcapi/core/fraud/api.py
> +            detail=f"Duplicat de l'utilisateur {duplicate_user.id}.",
Pourquoi ces points ? Je pense que tu peux laisser le contenu des FraudItem inchangés, au moins tout reste de la même forme en bdd.

2023-02-15 17:51 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/accounts.py
> +                and item.status != subscription_models.SubscriptionItemStatus.OK.value
oui ? non ?

2023-02-15 17:51 UTC, prouzet commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                <td>{{ review.reason | safe }}</td>
j'ai l'impression qu'il manque `pc_backoffice_public_account_link_in_comment` ici

2023-02-15 17:51 UTC, prouzet commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                    <td>{{ check.reason|default("Aucune") | safe }}</td>
Pas de `pc_backoffice_public_account_link_in_comment` ici aussi ?

2023-02-15 17:51 UTC, prouzet commented on api/src/pcapi/utils/urls.py
> +    reasearch = re.search(r"(\d+).$", comment)
Si le point dans le FraudItem est pour ici, ça ne va pas, car ça ne marchera pas pour tous ceux déjà en base de données sans le point. Pourquoi pas `\b(\d+)\b` avec `re.sub` comme j'avais suggéré ?

2023-02-16 10:23 UTC, merged