(PC-20640)[BO] Remove backofficeV2 tests for backofficeV3 tests
pass-culture/pass-culture-main pull request #5384
Opened 2023-02-21 10:29 UTC by stephane-liabat

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20640

## But de la pull request

Supprimer les tests beckofficeV2 pour les tests bezckofficeV3

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2023-02-21 11:48 UTC, prouzet approved these changes
OK, par contre je ne sais pas si `tests-backoffice-v3.yml` a déjà été testé sur github.
As-tu vu avec @jeremieb-pass ?

2023-02-21 12:46 UTC, Vencespass approved these changes
Même question que Patrick

2023-02-21 18:18 UTC, stephane-liabat commented
Eh beh non :)
Et me suis tâté longtemps à tester, puis en voyant le fichier, me suis dit qu'il devait fonctionner.
@jeremieb-pass c'est fonctionnel ?

2023-02-23 08:25 UTC, mlachevre-pass requested changes
Le test-backoffice-v3 doit être testé avant de mergé, au vu d'un run effectué en --fast j'ai de gros doute sur la viabilité

https://github.com/pass-culture/pass-culture-main/actions/runs/4243111989/jobs/7375504924

2023-03-01 17:19 UTC, stephane-liabat commented
Ah oui, closed parce que le nom de la branche était trop long, sorry ....

2023-03-01 17:19 UTC, closed without merging