(PC-20430)[API] feat: following of booking when a booking is uncancel…
pass-culture/pass-culture-main pull request #5396
Opened 2023-02-22 00:35 UTC by borisLeBonPro

…led by support

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20430

## But de la pull request

Suivi des résas - cas d'une résa désannulée par le support

2023-02-22 10:31 UTC, Meewan requested changes

2023-02-22 10:31 UTC, Meewan commented on api/src/pcapi/admin/custom_views/booking_view.py
> +            flash("La réservation a été dés-annulée et marquée comme confirmé.", "info")
pas forcement, ça eut être utilisée, fconfirmée ou preréserver selon le cas

2023-02-22 10:31 UTC, Meewan commented on api/src/pcapi/core/educational/models.py
>          self.status = CollectiveBookingStatus.USED
comme on set le status plus loin cette ligne est innutile

2023-02-22 10:31 UTC, Meewan commented on api/src/pcapi/core/educational/models.py
> +            self.dateUsed = datetime.utcnow()
```suggestion
        if self.confirmationDate:
            self.status = CollectiveBookingStatus.CONFIRMED
            if self.collectiveStock.beginningDatetime < datetime.utcnow():
                 self.status = CollectiveBookingStatus.USED
                 self.dateUsed = datetime.utcnow()
             else:
                 self.status = CollectiveBookingStatus.CONFIRMED
        else:
            self.status = CollectiveBookingStatus.PENDING

```pour êter certain de toujours mettre un status

2023-02-22 10:31 UTC, Meewan commented on api/tests/admin/custom_views/booking_view_test.py
> +        with freeze_time("2023-02-02 15:00:00"):
le temps est deja freeze par le decorator, pas besoin de le refreeze

2023-02-22 10:53 UTC, dbaty commented on api/src/pcapi/templates/admin/booking.html
> +    possible de la Désannuler.
pas de majuscule au milieu d'une phrase

```suggestion
    possible de la désannuler.
```

idem dans les autres fichiers

2023-02-22 13:01 UTC, borisLeBonPro commented on api/src/pcapi/core/educational/models.py
>          self.status = CollectiveBookingStatus.USED
la ligne 917

2023-02-23 08:53 UTC, Meewan approved these changes

2023-02-23 10:05 UTC, merged