Pc 20558 remonter valeur ispublicapi dans routes offer
pass-culture/pass-culture-main pull request #5429
Opened 2023-02-23 10:58 UTC by borisLeBonPro

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20558

## But de la pull request

savoir si les offres ont été ajouter via l'api publique ou non 

## NOTE

la page de test dans test_api a été copié de master apres une erreur de ma part ( j'ai embarqué les info d'une autre branche et j'ai remis en modifiant.

2023-02-23 13:47 UTC, Meewan requested changes

2023-02-23 13:47 UTC, Meewan commented on api/src/pcapi/routes/serialization/collective_offers_serialize.py
> +        isPublicApi=offer.isPublicApi if not is_offer_template else False,
une autre façon de l'écrire aurait été: `getattr(offer, 'isPublicApi', False)` mais je ne sais pas lequel des deux est le plus souhaitable

2023-02-23 13:47 UTC, Meewan commented on api/tests/routes/pro/get_all_collective_offers_test.py
> +        assert response_json[0]["isPublicApi"] == False
il faudrait rajouter un test ou cette valeur est a `True`

2023-02-23 14:07 UTC, borisLeBonPro commented on api/src/pcapi/routes/serialization/collective_offers_serialize.py
> +        isPublicApi=offer.isPublicApi if not is_offer_template else False,
Je trouve personnellement la première approche plus lisible, mais je veux bien

2023-02-23 21:13 UTC, borisLeBonPro commented on api/src/pcapi/routes/serialization/collective_offers_serialize.py
> +        isPublicApi=offer.isPublicApi if not is_offer_template else False,
sans réponse de ta part je me permet de faire le prochain push avec le même code

2023-02-24 08:58 UTC, Meewan approved these changes
lgtm

2023-02-24 10:22 UTC, merged