(PC-20877)[API] fix: remove id from all html templates
pass-culture/pass-culture-main pull request #5563
Opened 2023-03-07 15:03 UTC by kopax-polyconseil

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20877

## But de la pull request

Actuellement, nous utilisons des id pour des composants réutilisable, ce qui empêche si l'on souhaite de rester sémantiquement correct au yeux de la w3c, de réutiliser un composant.

Ceci peut également avoir un impact sur l'API du DOM, afin d'éviter l'accumulation de dette technique, ce nettoyage est nécessaire.

## Implémentation

- Éviter le risque d'avoir deux identifiant unique dans la page
- Suppression de tout les ids (sauf pour checkbox/radio/accessibility, mais nous n'avons encore rien de tel)
- TODO: remove `id` from csrf input

## Informations supplémentaires

NA

## Modifications du schéma de la base de données

NA

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2023-03-07 18:14 UTC, akarki16 approved these changes

2023-03-08 07:42 UTC, prouzet requested changes

2023-03-08 07:42 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/templates/accounts/get/credit.html
> +        <div class="card">
Cet `id` supprimé fait échouer le test `test_fraud_check_link`, qu'il faut adapter

2023-03-08 07:42 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/templates/components/forms/select_field.html
> +    <select class="form-select form-control" name="{{ field.name }}"
Cet `id` supprimé fait échouer le test `test_add_pro_user_choices`, qu'il faut adapter

2023-03-08 09:59 UTC, prouzet approved these changes

2023-03-08 10:01 UTC, merged