(PC-11684) Add route to post educational offers
pass-culture/pass-culture-main pull request #564
Opened 2021-11-24 15:27 UTC by cgaunet

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11684

## But de la pull request

(Ajout de fonctionnalités, Problèmes résolus, etc)

##  Implémentation

- (Ajouts de modèles, Changements significatifs)
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-11-25 18:03 UTC, gvannest approved these changes

2021-11-25 18:03 UTC, gvannest commented on api/tests/routes/pro/post_offer_test.py
> +    def test_create_valid_educational_offer_with_new_route(self, app):
Tu fais juste un cas passant car globalement `api.create_offer` est testée + ce sont les mêmes erreurs que la route `post_offer`?
Du coup ça me va :)

2021-11-29 08:52 UTC, gvannest commented on api/src/pcapi/routes/pro/offers.py
> +        offerers_api.can_offerer_create_educational_offer(dehumanize(body.offerer_id))
@MathildeDuboille en fait ce call il vaut mieux le faire au début de `api.create_educational_offer`
(sans ajouter de `try...catch` dans `api.create_educational_offer`; le `try .. catch` se fait en effet bien là où tu l'as mis!).
C'est purement une règle métier, donc il vaut mieux le mettre dans le code métier; ici on est dans du code technique / infra (déserialization / serialization + conversion des erreurs métiers en erreurs API)

2021-11-29 08:52 UTC, gvannest commented on api/tests/routes/pro/post_offer_test.py
> +        with requests_mock.Mocker() as request_mock:
Est-ce qu'on ne ferait pas un test d'un cas non passant?
Si non ici, au moins au niveau du use case `api.create_educational_offer`? Qu'on s'assure que l'offre n'est pas créée (i.e. pas présente en base) en cas de retour not found d'adage?
J'avoue que je serais chaud pour qu'on ajoute ça :)

2021-11-29 08:55 UTC, gael-boyenval requested changes

2021-11-29 08:55 UTC, gael-boyenval commented on pro/src/routes/OfferEducationalCreation/OfferEducationalCreation.tsx
>  import { queryParamsFromOfferer } from 'components/pages/Offers/utils/queryParamsFromOfferer'
j'aime pas trop qu'on ai des dépendances vers des pages Legacy, mais bon, faudra voir plus tard.

2021-11-29 08:55 UTC, gael-boyenval commented on pro/src/routes/OfferEducationalCreation/OfferEducationalCreation.tsx
> +  }
tous nos appels API doivent suivre le pattern adapter, à discuter ensemble (en pair maybe), mais en gros, c'est un mix de `createOfferPayload` et de ton try catch ici

2021-11-29 08:55 UTC, gael-boyenval commented on pro/src/routes/OfferEducationalCreation/OfferEducationalCreation.tsx
>        }}
```tsx
onSubmit={createOffer}
```

2021-11-29 09:56 UTC, gael-boyenval approved these changes
pour le front

2021-11-29 10:09 UTC, gvannest commented on api/tests/routes/pro/post_offer_test.py
> +    def when_offerer_cannot_create_educational_offer(self, app):
Cool!
Peut-être ajouter juste une toute petite assertion : tu fais un `Offer.query.all()` et tu assert que la longueur est de 0
Et après ça sera okay pour moi!

2021-11-29 10:18 UTC, gvannest approved these changes

2021-11-29 14:02 UTC, merged