(PC-21179)[API] fix: Editer les tags des offres en masse
pass-culture/pass-culture-main pull request #5740
Opened 2023-03-20 15:21 UTC by akarki16

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21179

## But de la pull request

_Ajout de fonctionnalités, Problèmes résolus, etc_

## Implémentation

- _Exemples: Ajouts de modèles, de routes, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Modifications du schéma de la base de données

- _Exemples: suppressions de telles colonnes, migration d'une information dans une nouvelle table_
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler l'implémentation technique_

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2023-03-22 11:07 UTC, prouzet reviewed
Je ne vois aucun test ajouté ? Un oubli ?

2023-03-22 11:07 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        for criterion in deleted_criteria:
A priori ce bloc doit pouvoir aller dans `if offer.criteria:`, après le `extend`, car on n'a forcément rien à enlever si `offer.criteria` est vide.

2023-03-22 11:07 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        request.environ.get("HTTP_REFERER", url_for("backoffice_v3_web.offer.list_offers")),
pourquoi ne pas utiliser `request.referer` ?

2023-03-22 11:07 UTC, prouzet commented on api/src/pcapi/static/backofficev3/js/addons/pc-batch-action-form.js
> + * - `[data-fetch-url]`: URL that render the form, it use `POST` with the `selectedRowsIds` from table multi select.
URL that render**s**
it use**s**

2023-03-22 11:07 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +            return redirect(request.referrer, 400)
Le comportement est-il bien vérifié dans la turbo-frame ?

2023-03-22 12:14 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        request.environ.get("HTTP_REFERER", url_for("backoffice_v3_web.offer.list_offers")),
Parce qu'il est parfois égal à `None`

2023-03-22 12:58 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +            return redirect(request.referrer, 400)
Je ne comprends pas la question

2023-03-22 13:04 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        request.environ.get("HTTP_REFERER", url_for("backoffice_v3_web.offer.list_offers")),
Non parce que si on a le `referer`, on l'utilise. En gros, si on a le `referer` on retourne à la page dans l'état dans lequel on l'avait avant l'envoi du formulaire, si le referer est à `None` on a le fallback de la page de liste comme si on n'avait renseigné aucun filtre.

2023-03-22 13:05 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +            return redirect(request.referrer, 400)
Oui, il y a un message d'erreur qui s'affiche dans la `turbo-frame`.

2023-03-22 13:07 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        request.environ.get("HTTP_REFERER", url_for("backoffice_v3_web.offer.list_offers")),
Ce comportement que tu attends correspond au code que je suggère ; exemple dans la console python :
```
>>> "http://referrer.com" or "url_for"
'http://referrer.com'
>>> None or "url_for"
'url_for'
```

2023-03-22 13:12 UTC, kopax-polyconseil commented on api/src/pcapi/static/backofficev3/js/addons/pc-batch-action-form.js
> +        console.error(error)
L'erreur n'est toujours pas traité

2023-03-22 13:22 UTC, akarki16 commented
> Je ne vois aucun test ajouté ? Un oubli ?

Non je suis dessus justement.

2023-03-22 15:56 UTC, kopax-polyconseil approved these changes

2023-03-22 16:30 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +    )
Détail : on doit pouvoir laisser ce `return` sur une ligne

2023-03-22 16:30 UTC, prouzet commented on api/tests/routes/backoffice_v3/offers_test.py
> +        authenticated_client.get(edit_url)
Pas besoin car tu as appelé la récupération du formulaire, qui t'a généré un _csrf token_.

2023-03-22 17:40 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +    )
Je suis d'accord avec toi. Mais il semblerait que `black` et `isort` le voient d'un autre œil ;)

2023-03-22 17:41 UTC, akarki16 commented on api/tests/routes/backoffice_v3/offers_test.py
> +        ]
👍🏼

2023-03-22 17:41 UTC, akarki16 commented on api/tests/routes/backoffice_v3/offers_test.py
> +        authenticated_client.get(edit_url)
bien vu !

2023-03-22 17:41 UTC, akarki16 commented on api/tests/routes/backoffice_v3/offers_test.py
> +class BatchEditOfferFormTest:
c'est mis à jour ! 💯

2023-03-23 07:35 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +    )
Tu as probablement dû laisser la virglule après `303`. Sans cette virgule, `black` laisse bien sur une ligne : 
`    return redirect(request.referrer or url_for("backoffice_v3_web.offer.list_offers"), 303)`

2023-03-23 07:50 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +    )
C'est fait ✅

2023-03-23 07:59 UTC, prouzet commented on api/tests/routes/backoffice_v3/offers_test.py
> +class BatchEditOfferFormTest:
Ton test est assez compliqué à suivre, normalement on crée un test par cas vérifié, ici c'est un mélange entre le test du « get form » et le test de la soumission du formulaire batch ainsi que celui d'une seule offre. En fait 4 routes appelées.

2023-03-23 08:21 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +    )
Ligne 262 aussi...

2023-03-23 08:25 UTC, akarki16 commented on api/tests/routes/backoffice_v3/offers_test.py
> +        choosenRankingWeight = 12
✅

2023-03-23 08:33 UTC, akarki16 commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        if form.rankingWeight.data:
il faut la mettre à 0 pour la supprimer

2023-03-23 08:44 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        if form.rankingWeight.data:
J'ai beau essayer avec une offre ou plusieurs offres, ça ne fonctionne pas.
si `form.rankingWeight.data` vaut `0`, alors ça ne passe probablement pas le `if`.
Ça veut dire qu'il manque un test pour ça :)

2023-03-23 08:54 UTC, akarki16 commented on api/tests/routes/backoffice_v3/offers_test.py
> +        choosenRankingWeight = 12
✅  là c'est fait ^^

2023-03-23 09:10 UTC, prouzet requested changes

2023-03-23 09:10 UTC, prouzet commented on api/src/pcapi/routes/backoffice_v3/offers.py
> +        if form.rankingWeight.data:
Je viens de tester avec ta correction, si la pondération est vide : 
```
pc-backoffice    | ERROR:pcapi.routes.error_handlers.generic_error_handlers:Unexpected error on method=POST url=http://localhost:5001/backofficev3/pro/offer/batch-edit: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
pc-backoffice    | Traceback (most recent call last):
pc-backoffice    |   File "/home/pcapi/.local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
pc-backoffice    |     rv = self.dispatch_request()
pc-backoffice    |   File "/home/pcapi/.local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
pc-backoffice    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
pc-backoffice    |   File "/usr/src/app/src/pcapi/routes/backoffice_v3/offers.py", line 256, in batch_edit_offer
pc-backoffice    |     if int(form.rankingWeight.data) == 0:
pc-backoffice    | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
Please... test !!!

2023-03-23 09:53 UTC, prouzet approved these changes
ok (testé en local dans le bo)

2023-03-23 09:55 UTC, merged