Jeremieb/remove bov3 prefix
pass-culture/pass-culture-main pull request #5752
Opened 2023-03-21 08:45 UTC by jeremieb-pass

## But de la pull request

Supprimer le suffixe /backofficev3 des URLs.

2023-03-21 10:00 UTC, prouzet requested changes
- Je vois d'autres `backofficev3` dans le code : 
  - .gitignore
  - api/src/pcapi/static/backofficev3/js/pc-backoffice-app.js
  - api/src/pcapi/routes/backoffice_v3/docs/JSDOC.md
  - api/src/pcapi/routes/backoffice_v3/scss.py
  - api/src/pcapi/routes/backoffice_v3/templates/home/login.html
  - api/src/pcapi/routes/backoffice_v3/templates/layouts/base.html
  - api/src/pcapi/static/backofficev3/js/addons/pc-select-multiple-field.js
  - api/src/pcapi/static/backofficev3/js/pc-backoffice-app.js
- **534 tests failed  out of 628**
https://app.circleci.com/pipelines/github/pass-culture/pass-culture-main/41717/workflows/a1442407-63fc-4c1c-8533-05cd69211dc0/jobs/345570

2023-03-21 10:00 UTC, prouzet commented on api/src/pcapi/routes/error_handlers/thumbnails_error_handlers.py
> -from pcapi.routes.error_handlers import utils as error_handlers_utils
generate_error_response est-il à supprimer dans ce module ?

2023-03-21 10:13 UTC, jeremieb-pass commented on api/src/pcapi/routes/error_handlers/thumbnails_error_handlers.py
> -from pcapi.routes.error_handlers import utils as error_handlers_utils
C'est comme pour les autres modules, non ? On appelle la bonne fonction via `app`.

2023-03-21 10:14 UTC, jeremieb-pass commented on api/src/pcapi/backoffice_app.py
> +    app.generate_error_response = generate_error_response  # type: ignore [attr-defined]
Je ne vois pas comment dire à mypy que Flask a une propriété ou une fonction qui s'appelle `generate_error_response`. En tout cas, je n'ai pas trouvé. Mais si quelqu'un a une idée, je prends !

2023-03-29 07:57 UTC, Vencespass commented on api/src/pcapi/static/backofficev3/scss/boussole.pid
> +79794
je suppose que c'est un ajout automatique ? J'ai l'ai vu apparaître chez moi aussi, mais je sais pas quoi en tirer...

2023-03-29 08:56 UTC, prouzet reviewed
Encore pas mal de `backofficev3` sur ta branche :
![image](https://user-images.githubusercontent.com/23212130/228481769-01df30f9-22eb-48c2-b2f2-176ab64c50db.png)

2023-04-13 07:41 UTC, kopax-polyconseil commented on api/src/pcapi/static/backofficev3/scss/boussole.pid
> +79794
Oui,  et je l'ai supprimé du gitignore ensuite ^^

2023-04-13 07:44 UTC, kopax-polyconseil commented on api/src/pcapi/static/backofficev3/js/addons/pc-select-multiple-field.js
> + *   data-tomselect-autocomplete-url="/autocomplete/offerers"
il faut regen la doc, voir `JSDOC.md` (sauf si c'est déjà fait)

2023-04-14 07:35 UTC, jeremieb-pass commented on api/src/pcapi/routes/error_handlers/utils.py
> -def generate_error_response(errors: dict, backoffice_template_name: str = "errors/generic.html") -> Response:
Pour que chaque app (la normale pour l'api, le portail pro et FA ; et celle du backoffice) ait son implémentation de `generate_error_response`, légèrement différente.

2023-04-14 07:45 UTC, jeremieb-pass commented on api/src/pcapi/static/backofficev3/js/addons/pc-select-multiple-field.js
> + *   data-tomselect-autocomplete-url="/autocomplete/offerers"
Je l'ai régénérée mais ça ne change rien. Est-ce normal ?

2023-04-21 15:49 UTC, jeremieb-pass commented on api/tests/conftest.py
> +        response = self.post(f"/signin/{user.id}")
pour une raison inconnue, `url_for` ne fonctionne pas ici.

2023-04-24 07:34 UTC, kopax-polyconseil approved these changes

2023-05-11 14:56 UTC, prouzet approved these changes
Approuvé à la demande de @jeremieb-pass pour retirer l'état «  Changes requested  ».
La PR a déjà été revue et approuvée par @kopax-polyconseil

2023-05-11 15:06 UTC, merged