(PC-20193)[API] feat: return information about DMS for a venue
pass-culture/pass-culture-main pull request #5839
Opened 2023-03-25 14:19 UTC by borisLeBonPro

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-20193

## But de la pull request

return information about DMS for a venue

2023-03-27 14:26 UTC, Meewan commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    siret: str
detail: A voir avec le front mais je ne pense pas que le siret soit pertinent ici vue qu'on le remonte deja dans l'objet venue. (il ets utile en backend pour faire le lien)

2023-03-27 14:28 UTC, Meewan commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    hasAdageId: bool = bool(offerers_models.Venue.adageId)
attention si tu met ça il retournera toujours True.

Il faut le setter dans la méthode `from_orm`
```suggestion
    hasAdageId: bool
```

2023-03-27 22:42 UTC, borisLeBonPro commented on api/tests/routes/pro/get_venue_test.py
> +            "hasAdageId": True,
Pourtant dans le test, l'adageId = "0" . 
dans le factory : adageId = factory.Sequence(str)
rien ne specifie le contraire... du moins je ne l'ai pas vue

2023-03-28 10:18 UTC, Meewan requested changes

2023-03-28 10:18 UTC, Meewan commented on api/src/pcapi/routes/serialization/venues_serialize.py
> +    expirationDate: datetime
ce champ est nullable (je l'ai appris a mes dépends ce matin :sob: )
```suggestion
    expirationDate: datetime | None
```

2023-03-28 10:18 UTC, Meewan commented on api/tests/routes/pro/get_venue_test.py
> +        assert response.json["adageInscriptionDate"] == None
```suggestion
        assert response.json["adageInscriptionDate"] == None
        assert response.json["hasAdageId"] == False
```

2023-03-28 13:51 UTC, Meewan commented on api/tests/routes/pro/get_venue_test.py
> +            "hasAdageId": True,
errur de ma part en effet :)

2023-03-30 08:02 UTC, Meewan approved these changes

2023-03-30 11:17 UTC, merged