(PC-12005) fix design offer type screen
pass-culture/pass-culture-main pull request #591
Opened 2021-11-26 15:58 UTC by MathildeDuboille

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12005

## But de la pull request

Fix design du bouton de droite qui prenait trop de place

##  Implémentation

Suppression de l'utilisation du design du formulaire
Ajout du css scopé pour cet écran
​
##  Informations supplémentaires

- Exemples : nettoyage de code, utilisation de factories, Boy Scout Rule
- Explications sur l'utilisation d'outils peu communs (Exemple psql window function, metaclasses, yield from)
​
## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2021-11-29 08:03 UTC, gael-boyenval requested changes
pas d'ac avec cette PR, pour moi tout est identique, faut juste ajouter une prop au `FormLayout` pour qu'il ai la capacité d'ajouter une `max-width` et fixer l'apparence des boutons dans le `FormLayout.Actions` c'était déjà identifié à la base, mais à modifier plus tard, genre : 

```scss
.FormLayout {
    &.small {
       width: rem(468px);
    }
    ....

  &-actions {
    display: flex;
    justify-content: flex-start;
  }

  &-action {
    flex: initial;
  }
}

```

usage dans le layout : 

```tsx
<FormLayout small>
</FormLayout>
```

2021-11-30 09:18 UTC, gael-boyenval commented on pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
> +    <FormLayout className={styles['educational-form']} small>
et sur type aussi non ?

2021-11-30 09:27 UTC, MathildeDuboille commented on pro/src/screens/OfferEducational/OfferEducationalForm/OfferEducationalForm.tsx
> +    <FormLayout className={styles['educational-form']} small>
Pas la peine vu qu'on a enlevé le flex 1 :)

2021-11-30 10:37 UTC, gael-boyenval approved these changes

2021-11-30 10:38 UTC, merged