(PC-21431)[API] feat: endpoint duplication collective offer
pass-culture/pass-culture-main pull request #5962
Opened 2023-04-03 16:44 UTC by borisLeBonPro

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21431

## But de la pull request

endpoint duplication collective offer

2023-04-04 09:03 UTC, Meewan requested changes

2023-04-04 09:03 UTC, Meewan commented on api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
> +        # test que l'offre n'est pas bloqué par la fraud ( champs validation)
il y a les commentaires mais il manque les tests ;)

2023-04-05 07:50 UTC, dbaty requested changes

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/core/educational/models.py
> +    def duplicate(self) -> "CollectiveOffer":
On essaie d'éviter d'ajouter des fonctions avec trop de logique (validation, etc.) au niveau du modèle. Cette fonctiondevrait être définie hors du modèle, dans une fonction `core.educational.api.offer.duplicate_offer()`.

Idem pour la fonction de duplication d'un stock.

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/core/educational/models.py
> +        if self.validation == offer_mixin.OfferValidationStatus.DRAFT:
Je comprends qu'on ne peut pas dupliquer une offre brouillon. Peut-on dupliquer une offre rejetée ?

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/core/educational/models.py
> +            dateModified=self.dateModified,
Les dates de création et de modification du stock duplicat ne devrait pas être les mêmes que les date de création/modification de l'original, non ?

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"validation": ["offer don't pass the validation"]}, status_code=403)
Pourquoi l'erreur est-elle en anglais ici, alors qu'elle est en français quelques lignes plus haut ?

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"Offerer": ["offerer not allowed to duplicate the collective offer"]}, status_code=403)
Idem, pourquoi l'erreur est-elle en anglais ?

De plus, la clé d'erreur est ici "Offerer" avec un "O" majuscule, alors que la clé est "offerer" avec une minuscule quelques lignes plus haut.

2023-04-05 07:50 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +    dehumanized_id = dehumanize_or_raise(offer_id)
On essaie d'arrêtr d'utiliser des identifiants humanisés sur les routes existantes. On devrait pouvoir facilement les éviter aussi sur les nouvelles routes, non ? cc @mageoffray

2023-04-05 07:50 UTC, dbaty commented on api/tests/routes/pro/post_duplicate_collective_offer_and_stock_test.py
> +# @freeze_time("2022-05-01 15:00:00")
code commenté à supprimer.

2023-04-05 08:13 UTC, Meewan commented on api/src/pcapi/core/educational/models.py
> +        if self.validation == offer_mixin.OfferValidationStatus.DRAFT:
non car elle n'est pas visible ni modifiable

2023-04-05 12:26 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +    offer.collectiveStock = stock
cette ligne ne sert pas, elle est redondante avec la ligne 703

2023-04-05 12:26 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +        raise exceptions.ValidationFailedOnCollectiveOffer
[mode relou] tu pourrais instancier l'exception plz ?

2023-04-05 12:26 UTC, Meewan commented on api/src/pcapi/core/educational/api/offer.py
> +        raise exceptions.OffererNotAllowedToDuplicate
[mode relou] tu pourrais instancier l'exception plz ?

2023-04-05 14:19 UTC, mageoffray commented on api/src/pcapi/routes/pro/collective_offers.py
> +    dehumanized_id = dehumanize_or_raise(offer_id)
Ah yes, merci damien ! 
Dans l'idée, on veut travailler avec des id non humains (des entiers) plutot qu'avec des ids en base 32
Ici tu peux mettre 
```
@private_api.route("/collective/offers/<int:offer_id>/duplicate", methods=["POST"])
...
def duplicate_collective_offer(
    offer_id: str,
) -> collective_offers_serialize.GetCollectiveOfferResponseModel:
```
et supprimer la deshumanisation ! 
Pour les fronts ils faut juste qu'ils soient au courant mais ils devraient avoir offer.nonHumanizedId qui contient l'id int

2023-04-05 15:15 UTC, Meewan approved these changes

2023-04-05 15:23 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"Offerer": ["l'offrant n'est pas autoriser à dupliquer l'offre"]}, status_code=403)
```suggestion
        raise ApiErrors({"offerer": ["la structure n'est pas autorisée à dupliquer l'offre"]}, status_code=403)
```

2023-04-05 15:23 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +        original_offer = educational_api_offer.get_collective_offer_by_id(offer_id)
On devrait vérifier que l'utilisateur est bien le propriétaire de l'offre.

2023-04-06 07:25 UTC, dbaty approved these changes

2023-04-06 07:25 UTC, dbaty commented on api/src/pcapi/routes/pro/collective_offers.py
> +        raise ApiErrors({"Offerer": ["la structure n'est pas autorisée à dupliquer l'offre"]}, status_code=403)
C'est la troisième fois que je fais remarquer qu'il faut homogénéiser la clé de l'erreur : `offerer` avec une minuscule.

(Je note aussi que cette route produit des messages d'erreur avec des phrases qui commencent par une majuscule ou non, et qui contiennent un point ou pas. Là aussi, on pourrait être plus homogène. Ça n'est pas critique, certes, mais ce genre de petites choses ne coûte pas cher à unifier.)

2023-04-06 07:53 UTC, merged