Mageoffray/pc 21448 provider pro
pass-culture/pass-culture-main pull request #6240
Opened 2023-04-20 14:11 UTC by mageoffray

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

_Ajout de fonctionnalités, Problèmes résolus, etc_

## Implémentation

- _Exemples: Ajouts de modèles, de routes, Changements significatifs_

## Informations supplémentaires

- _Exemples: nettoyage de code, utilisation de factories, Boy Scout Rule_
- _Explications sur l'utilisation d'outils peu communs (ex.: psql window function, metaclasses, yield from)_

## Modifications du schéma de la base de données

- _Exemples: suppressions de telles colonnes, migration d'une information dans une nouvelle table_
- _A destination des Data Analysts, exposer le résultat final (tables et colonnes), sans détailler l'implémentation technique_

## Checklist :

- [ ] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : `pc-XXX-whatever-describe-the-branch`
  - PR : `(PC-XXX) Description rapide de l' US`
  - Commit(s) : `(PC-XXX)[PRO|API|…] description rapide du ticket`
- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_
- [ ] J'ai mis à jour la **sandbox** afin que le développement ou la recette soient facilités
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques (ex: Admin)

2023-04-24 14:32 UTC, cepehang approved these changes

2023-04-26 07:50 UTC, antoinemrn approved these changes
Ok pour le front 👍

2023-04-26 15:04 UTC, cepehang requested changes

2023-04-26 15:22 UTC, cepehang approved these changes
il faut aussi modifier toutes les occurences à `provider.offererProviders`

```diff
diff --git a/api/src/pcapi/core/offerers/models.py b/api/src/pcapi/core/offerers/models.py
index d3019e858f..f6d27dbfe6 100644
--- a/api/src/pcapi/core/offerers/models.py
+++ b/api/src/pcapi/core/offerers/models.py
@@ -892,7 +892,7 @@ class OffererProvider(PcObject, Base, Model):
     offerer: Offerer = relationship("Offerer", foreign_keys=[offererId], back_populates="offererProviders")
     providerId: int = Column(BigInteger, ForeignKey("provider.id"), index=True, nullable=False)
     provider: sa_orm.Mapped["providers_models.Provider"] = relationship(
-        "Provider", foreign_keys=[providerId], back_populates="offererProviders"
+        "Provider", foreign_keys=[providerId], back_populates="offererProvider"
     )
 
     __table_args__ = (UniqueConstraint("offererId", "providerId", name="unique_offerer_provider"),)
diff --git a/api/src/pcapi/core/providers/models.py b/api/src/pcapi/core/providers/models.py
index 60b11dd564..c4d69e1deb 100644
--- a/api/src/pcapi/core/providers/models.py
+++ b/api/src/pcapi/core/providers/models.py
@@ -92,11 +92,11 @@ class Provider(PcObject, Base, Model, DeactivableMixin):
 
     @property
     def hasOffererProvider(self) -> bool:
-        return bool(self.offererProviders)
+        return bool(self.offererProvider)
 
     @property
     def implements_provider_api(self) -> bool:
-        return self.apiUrl != None and not self.offererProviders
+        return self.apiUrl != None and not self.offererProvider
 
     def getProviderAPI(self) -> ProviderAPI:
         return ProviderAPI(
diff --git a/api/src/pcapi/core/providers/repository.py b/api/src/pcapi/core/providers/repository.py
index cf0fde3a50..259c302c66 100644
--- a/api/src/pcapi/core/providers/repository.py
+++ b/api/src/pcapi/core/providers/repository.py
@@ -22,7 +22,7 @@ def get_venue_provider_by_id(venue_provider_id: int) -> models.VenueProvider:
 def get_venue_provider_list(venue_id: int) -> list[models.VenueProvider]:
     return (
         models.VenueProvider.query.filter_by(venueId=venue_id)
-        .options(sqla_orm.joinedload(models.VenueProvider.provider).joinedload(models.Provider.offererProviders))
+        .options(sqla_orm.joinedload(models.VenueProvider.provider).joinedload(models.Provider.offererProvider))
         .all()
     )
 
@@ -51,7 +51,7 @@ def get_available_providers(venue: Venue) -> BaseQuery:
     from pcapi.local_providers import AllocineStocks
 
     query = models.Provider.query.filter_by(isActive=True, enabledForPro=True).options(
-        sqla_orm.joinedload(models.Provider.offererProviders)
+        sqla_orm.joinedload(models.Provider.offererProvider)
     )
 
     local_classes_to_exclude = set(constants.CINEMA_PROVIDER_NAMES)
```

2023-04-27 06:53 UTC, merged