(PC-22035)[PRO] feat: CSS  de liste des offres
pass-culture/pass-culture-main pull request #6543
Opened 2023-05-16 14:23 UTC by TetyanaZhabchyk

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-22035

## But de la pull request

Mettre la font du texte sous le nom de l’offre en style caption (12/16 px) en grey dark #696A6F.

## Informations supplémentaires
<img width="986" alt="Capture d’écran 2023-05-16 à 16 11 47" src="https://github.com/pass-culture/pass-culture-main/assets/115089249/e76e0975-ac18-4798-b8fd-5a773f448fff">

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
  - Branche : PC-22035-style-caption-texte-offres
  - (PC-22035)[PRO] feat: CSS  de liste des offres
  - Commit(s) : (PC-22035)[PRO] feat: CSS  de liste des offres

2023-05-24 14:17 UTC, hugocapuano reviewed
Je pense que tu veux utiliser plutôt le style `small-caption();` existant dans le fichier `styles/mixins/_fonts.scss`.

Et donc remplacer caption par small-caption de la classe `stocks` dans le fichier `src/pages/Offers/Offers/OfferItem/OfferItem.module.scss`  + supprimer le font-size qui surcharge celui de small-caption.

2023-05-25 14:43 UTC, mariedestandau commented on pro/src/styles/global/_layout.scss
> +  color: colors.$grey-dark;
attention c'est le CSS pour tout le site pas pour la liste des offres

2023-05-25 14:44 UTC, mariedestandau commented on pro/src/styles/mixins/_fonts.scss
> +$body-font-size: rem.torem(12px);
le ticket demande juste de changer une couleur

2023-05-25 14:44 UTC, mariedestandau commented on pro/src/styles/mixins/_fonts.scss
> +  font-size: rem.torem(16px);
le ticket demande juste de changer une couleur

2023-05-25 14:45 UTC, mariedestandau requested changes
La couleur sur le texte est déjà la bonne, vérifie avec Martin à son retour, je pense que tu peux fermer cette PR

2023-05-30 07:39 UTC, closed without merging