(PC-21948)[API] feat: Individual offer api bulk create offers by ean
pass-culture/pass-culture-main pull request #6667
Opened 2023-05-29 06:56 UTC by mageoffray

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21948

2023-05-29 14:39 UTC, jeremieb-pass commented on api/src/pcapi/routes/public/individual_offers/v1/products.py
> +        offer_to_update_by_ean[offer.extraData["ean"]] = offer  # type: ignore [index]
est-ce qu'on est sûr qu'il y aura toujours un champ `ean` ?

2023-05-29 14:44 UTC, jeremieb-pass commented on api/src/pcapi/routes/public/individual_offers/v1/products.py
> +    search.async_index_offer_ids(offers_to_index)
Est-ce que ça ne vaut pas le coup de désindexer les offres dans `delete_stock` (`offers.api`) qui est la seule des trois fonctions appelées par `_upsert_product_stock` qui ne lance pas d'indexation ?

2023-05-29 15:23 UTC, cepehang requested changes

2023-05-29 15:23 UTC, cepehang commented on api/tests/routes/public/individual_offers/v1/endpoints_test.py
> +        unkown_ean = "1234567897123"
```suggestion
        unknown_ean = "1234567897123"
```

2023-05-29 15:23 UTC, cepehang commented on api/src/pcapi/routes/public/individual_offers/v1/products.py
>                  continue
il faudrait à minima un `logger.exception()` plutôt que taire l'exception, sinon ça va être compliqué de diagnostiquer si la route marche partiellement

2023-05-29 15:23 UTC, cepehang commented on api/src/pcapi/routes/public/individual_offers/v1/products.py
>              continue
il faudrait à minima un `logger.exception()` plutôt que taire l'exception, sinon ça va être compliqué de diagnostiquer si la route marche partiellement

2023-05-30 07:29 UTC, mageoffray commented on api/src/pcapi/routes/public/individual_offers/v1/products.py
> +        offer_to_update_by_ean[offer.extraData["ean"]] = offer  # type: ignore [index]
Yes. 
Cette route demande un payload qui est une liste d'ean (obligatoire), prix et quantité. On cherche ensuite les offres ou les produits liés à ces ean.

2023-05-30 15:22 UTC, cepehang approved these changes

2023-05-31 08:06 UTC, merged