PC-21550 rm is public api
pass-culture/pass-culture-main pull request #7004
Opened 2023-06-21 17:29 UTC by jeremieb-pass

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-21550

## But de la pull request

Suppression de la colonne `isPublicApi` de `collective_offer` : il faut dorénavant utiliser `provider`/`providerId` (si présent, cela correspondait au cas `isPublicApi == True` et à `isPublicApi == False` sinon).

Deux commits : un premier pour nettoyer le code, un second pour la migration.

### Mise à jour

La colonne est supprimée et transformée en propriété car le front en a encore besoin. On considère donc `isPublicApi` vaut True si l'offre (collective) a un `providerId`.

2023-06-22 08:07 UTC, dbaty requested changes

2023-06-22 08:07 UTC, dbaty commented on api/src/pcapi/alembic/versions/20230621T192232_49e118a9dd48_rm_collective_offer_ispublicapi.py
> +# pre/post deployment: pre
La suppression d'une colonne ne doit se faire qu'une fois que le code l'utilisant n'est plus exécuté. Ici, le code actuelle l'utilise, donc on ne peut pas supprimer la colonne dans une migration **pré-**déploiement. Ce doit donc être une migration **post-**déploiement.

2023-06-22 12:41 UTC, jeremieb-pass commented on api/src/pcapi/alembic/versions/20230621T192232_49e118a9dd48_rm_collective_offer_ispublicapi.py
> +Remove this FIXME and make the comment below easily readable.
![oops](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2o0ZXJ0djZlbDU2cXFreng5anhxNWo3ZWNtazBpc2UyOHBxcDYzOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wRc3lYsawNj20/giphy.gif)

2023-08-01 08:39 UTC, borisLeBonPro commented on api/src/pcapi/core/educational/api/offer.py
>      if FeatureToggle.ENABLE_PROVIDER_AUTHENTIFICATION.is_active():
vue que l'on ne se sert que de provider maintenant ( si j'ai bien compris ) et que l'on retire le feature flag, ne faudrait il pas s'occuper de la fonction
def create_collective_offer_public en ligne 439 dans core/educational/api/offer.py afin de ne pas avoir a remettre offerer_id quand on appel cette fonction? par la meme occasion une fois cela fait virer les fichiers de test qui correspondent au offerer

2023-08-01 09:14 UTC, Meewan commented on api/src/pcapi/core/educational/validation.py
> +    if offer.provider:
```suggestion
    if offer.providerId:
```
Pour eviter une requete sur provider ;)

2023-08-04 13:18 UTC, Meewan approved these changes

2023-08-04 13:59 UTC, dbaty approved these changes
Je retire mon blocage, mais j'ai juste relu la migration (qui était le point bloquant). Je n'ai pas relu le reste de la PR.

2023-08-04 14:02 UTC, merged