(PC-23127) paginate by cursor bookings route
pass-culture/pass-culture-main pull request #7184
Opened 2023-07-05 09:13 UTC by ghaliela

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

add pagination by index for get bookings api

2023-07-05 09:56 UTC, jeremieb-pass reviewed
(détail) est-ce qu'il ne serait pas plus sûr et plus simple de construire les url avec `url_for` plutôt que de tout faire à la main ?

2023-07-05 12:31 UTC, ghaliela commented
> (détail) est-ce qu'il ne serait pas plus sûr et plus simple de construire les url avec `url_for` plutôt que de tout faire à la main ?

la pagination "de base" avec les pages etc... est faites manuellement donc je suppose que non, mais si tu connais une méthode pour faire plus simplement je suis chaud :pray:

2023-07-06 14:15 UTC, mageoffray requested changes

2023-07-06 14:15 UTC, mageoffray commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> +    max_bookings_id = _get_bookings_query(query.offer_id).order_by(booking_models.Booking.id.desc()).first()
Je ne pense pas qu'on ai besoin de ça. 
On imagine qu'on ait 20 reservations en base. 
Si tu cherches tous ceux après l'id 25 tu auras une réponse vide

2023-07-06 14:15 UTC, mageoffray commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> +    if query.firstIndex > max_bookings_id:
idem, ici on s'en moque un peu. Il aura une réponse vide qui veut dire : on a rien trouvé

2023-07-06 14:15 UTC, mageoffray commented on api/tests/routes/public/individual_offers/v1/get_bookings_test.py
> +        venue, _ = create_offerer_provider_linked_to_venue()
Du coup ici je pense qu'on devrait recevoir une 200 avec une liste vide

2023-07-06 14:15 UTC, mageoffray commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> -        .order_by(booking_models.Booking.dateCreated.desc())
Normalement la base te retourne les objets par id croissant de base, dans certains cas (si il y a eu une suppression ou autre) l'odre peut ne pas être consistant. 
Je pense qu'on doit garder le booking_models.Booking.id. 
Normalement ça n'a pas de coût de performance, tu peux tester ça en regardant le EXPLAIN ANALYZE de la requête et en vérifiant qu'il n'y a pas de full table scan, juste des index scan

2023-07-06 14:15 UTC, mageoffray commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> +        .all()
le .all() est pas nécessaire. La requête sera executée lors de la boucle en dessous

2023-07-07 13:02 UTC, merged