(PC-21143)[PRO] feat: remove advices and change width of img modale
pass-culture/pass-culture-main pull request #7245
Opened 2023-07-07 12:23 UTC by Aliochka

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-21143

après : 
![image](https://github.com/pass-culture/pass-culture-main/assets/15941528/d54979d2-b904-4eae-a502-bc023027d397)

avant: 
![image](https://github.com/pass-culture/pass-culture-main/assets/15941528/04faf7be-36cc-4e06-83b0-61f6d152cf0a)

2023-07-10 08:04 UTC, AlbericTrancart requested changes

2023-07-10 08:04 UTC, AlbericTrancart commented on pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageCrop/ModalImageCrop.module.scss
> +  min-width: rem.torem(592px);
Utiliser un calc pultôt

2023-07-10 08:04 UTC, AlbericTrancart commented on pro/src/components/ImageUploader/ButtonImageEdit/ModalImageEdit/ModalImageUploadBrowser/ModalImageUploadBrowser.module.scss
> +  min-width: rem.torem(592px);
Idem utiliser un calc

2023-07-18 12:52 UTC, AmineLouveau approved these changes

2023-07-18 13:07 UTC, AlbericTrancart approved these changes

2023-07-18 13:10 UTC, hugocapuano approved these changes

2023-07-18 13:18 UTC, merged