(PC-23177)[PRO] feat: partial checkbox
pass-culture/pass-culture-main pull request #7250
Opened 2023-07-07 13:25 UTC by Aliochka

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23177

_rajouter un troisième état aux checkbox 
_ l'implémenter dans la liste des offres et la création de stocks events

![image](https://github.com/pass-culture/pass-culture-main/assets/15941528/83feb2c0-83cc-40bd-9073-0f362e99b198)

2023-07-10 08:01 UTC, AlbericTrancart requested changes

2023-07-10 08:01 UTC, AlbericTrancart commented on pro/src/icons/checkbox-partial.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
Soit on le met dans icons dans ce cas il faut que ce soit au standard de la lib soit on trouve autre chose

2023-07-10 08:01 UTC, AlbericTrancart commented on pro/src/styles/components/layout/inputs/CheckboxInput/_CheckboxInput.scss
> +        background-image: url("/icons/checkbox-partial.svg");
surtout que c'est utilisé en background image

2023-07-18 15:29 UTC, AmineLouveau approved these changes

2023-07-19 08:23 UTC, AlbericTrancart commented on pro/src/ui-kit/form/shared/BaseCheckbox/BaseCheckbox.tsx
> +          ['partial-check']: partialCheck,
tu peux dupliquer ce css pour l'avoir dans un css module/pas global

2023-07-19 09:39 UTC, merged