(PC-23127)[API] feat: return error if the offer id is not found
pass-culture/pass-culture-main pull request #7526
Opened 2023-07-28 14:59 UTC by ghaliela

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-XXXXX

## Vérifications

- [X] J'ai écrit les tests nécessaires

2023-07-31 08:45 UTC, R0ntheo requested changes

2023-07-31 08:45 UTC, R0ntheo commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> +    offer = offers_models.Offer.query.filter(offers_models.Offer.id == query.offer_id).one_or_none()
Un PT a le droit sur le lieu A qui a l'offre 1. 
Si il demande l'offre 2 qui a été créée par le lieu B sur lequel il a pas de droits il va avoir une liste de bookings vide. 
Je pense qu'on devrait pas lui dire aussi qu'on ne peut pas trouver cette offre
(ie ajouter une validation du genre)
```
.join(providers_models.VenueProvider)
.filter(providers_models.VenueProvider.providerId == current_api_key.providerId)
.filter(providers_models.VenueProvider.isActive == True)
```

2023-07-31 08:45 UTC, R0ntheo commented on api/src/pcapi/routes/public/individual_offers/v1/bookings.py
> +    offer = offers_models.Offer.query.filter(offers_models.Offer.id == query.offer_id).one_or_none()
Oups mauvais compte..

2023-08-02 13:42 UTC, mageoffray approved these changes

2023-08-02 15:15 UTC, merged