Ghaliela/pc 23302 block creating already exisiting price category
pass-culture/pass-culture-main pull request #7541
Opened 2023-07-31 12:38 UTC by ghaliela

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23302

## Vérifications

- [x] J'ai écrit les tests nécessaires

2023-08-02 08:31 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +            (price_category.label, price_category.price) for price_category in existing_price_categories
L'accès à `.label` nécessite une requête SQL de plus. Il faudrait au minimum `joinedload(PricingCategory.priceCategoryLabel)`  dans la requête plus haut.

Mais est-ce qu'on ne pourrait pas écrire cette boucle de vérification en une seule requête SQL, du genre : 

```python
new_labels_and_prices = {(p.label, p.price) for p in price_category_to_create}
existing_price_category = (
    models.PriceCategory.query
    .join(models.PriceCategory.priceCategoryLabel)
    .filter_by(offerId=offer_id)
    .filter(sqla.func.ROW(models.PriceCategoryLabel.label, models.PriceCategory.price).in_(new_labels_and_prices))
    .first()
)
if existing_price_category:
    raise ...

2023-08-02 08:31 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +            (price_category.label, price_category.price) for price_category in existing_price_categories
... d'autre part, on pourrait peut-être mettre ce bloc de code dans une fonction, qu'on pourrait réutiliser dans l'API publique, non ?

2023-08-02 09:46 UTC, ghaliela commented on api/src/pcapi/routes/pro/offers.py
> +            (price_category.label, price_category.price) for price_category in existing_price_categories
okkay, je fais ça

2023-08-03 11:58 UTC, mageoffray approved these changes
Je fusionnerais bien tous les commits, sinon ok

2023-08-03 12:24 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
Vraiment ? `PriceCategory.price` est pourtant un un `decimal`.

2023-08-03 12:25 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
... je veux dire, si on y stocke un montant en centimes d'euros, alors la colonne devrait être un `int`.

2023-08-03 12:37 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
... vu les données, j'ai la nette impression qu'on stocke dans cette colonne des euros, pas des centimes d'euros : 

```sql
> select id, price from price_category limit 3
+----+-------+
| id | price |
|----+-------|
| 8  | 4.00  |
| 9  | 5.00  |
| 16 | 6.50  |
+----+-------+
```

Il y a donc un bug ici et dans le typage de `check_for_duplicated_price_categories()`, il me semble.

2023-08-03 12:38 UTC, dbaty requested changes

2023-08-03 12:38 UTC, dbaty commented on api/src/pcapi/routes/public/individual_offers/v1/events.py
> +            )
Hmm, ça n'est pas déjà ce qu'on fait dans `check_for_duplicated_price_categories` ?

2023-08-03 13:13 UTC, ghaliela commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
en fait la méthode est utilisé dans 2 endroits, une fois dans l'api offers et une fois dans events, une considère le price Decimal et l'autre strictInt, c'est pour ça que j'ai décidé de convertir les 2 en centimes

2023-08-03 15:10 UTC, dbaty commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
Désolé, je ne comprends pas. Est-ce que `PriceCategory.price` stocke des centimes ou des euros ? Vu les valeurs non entières sur staging, on dirait que ça stocke des euros. J'ai bon, ou pas ?

D'autre part, tu appelles `to_eurocents()` ici, donc on passe des centimes à la fonction `check_for_duplicated_price_categories()`. Cette fonction compare les valeurs fournies (des centimes, donc) à `PriceCategory.price` (qui sont des euros, si j'ai bien compris). Donc il y a un problème, non ?

2023-08-03 15:59 UTC, ghaliela commented on api/src/pcapi/routes/pro/offers.py
> +    new_labels_and_prices = {(p.label, to_eurocents(p.price)) for p in price_categories_to_create}
Il y'a les 2 en bd, c'est un peu n'importe quoi en bdd, mais à termes on veut garder que des entiers en bdd donc des centimes

2023-08-07 13:17 UTC, cepehang requested changes

2023-08-07 13:17 UTC, cepehang commented on api/src/pcapi/routes/pro/offers.py
> +    # We convert the price to eurocents beucause the price has different types in different apis
commentaire qui ment, à supprimer

2023-08-07 13:17 UTC, cepehang commented on api/src/pcapi/routes/public/individual_offers/v1/events.py
> +    new_labels_and_prices = {(p.label, finance_utils.to_euros(p.price)) for p in body.price_categories}
tu voulais sans doute mettre le commentaire ici

2023-08-07 13:17 UTC, cepehang commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.json == {"priceCategories": ["The price category Already exists already exists"]}
already exists est écrit 2 fois

2023-08-07 14:31 UTC, ghaliela commented on api/tests/routes/pro/post_price_categories_test.py
> +        assert response.json == {"priceCategories": ["The price category Already exists already exists"]}
le premier c'est le label du tarif, j'ai modifié le label pour avoir une erreur plus parlante

2023-08-08 08:39 UTC, cepehang approved these changes

2023-08-08 08:41 UTC, dbaty approved these changes

2023-08-08 13:05 UTC, merged