(PC-23538)[API] feat: stock information to know if user adage have cl…
pass-culture/pass-culture-main pull request #7600
Opened 2023-08-03 08:08 UTC by borisLeBonPro

stock information to know if user adage have closed broadcast help

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23538

2023-08-17 08:54 UTC, Meewan requested changes

2023-08-17 08:54 UTC, Meewan commented on node_modules/.yarn-integrity
ce fichier ne devrait pas être add, a retirer

2023-08-22 09:28 UTC, jeremieb-pass commented on api/tests/routes/adage_iframe/get_authenticate_test.py
> +        assert response.json["preferences"] == {"broadcast_help_closed": None, "feedback_form_closed": True}
On gère déjà le cas où `broadcast_help_closed` est nul au-dessus. Ça vaut peut-être le coup de vérifier le cas où il vaut `True` ou `False` (quelque chose différent de `None`).

2023-08-22 09:30 UTC, jeremieb-pass commented on api/tests/routes/adage_iframe/redactor_test.py
> +        assert educational_redactor.preferences == {"feedback_form_closed": True, "broadcast_help_closed": None}
Ça vaut peut-être le coup de s'assurer que le choix de l'utilisateur a bien été pris en compte, non ? Par exemple en testant le cas où il enregistre deux valeurs : 

```python
response = client.post(url_for(self.endpoint), json={"feedback_form_closed": True, "broadcast_help_closed": True})
# [...]
assert educational_redactor.preferences == {"feedback_form_closed": True, "broadcast_help_closed": True}
```

2023-08-23 15:02 UTC, jeremieb-pass approved these changes

2023-08-23 15:53 UTC, Meewan approved these changes

2023-08-24 07:33 UTC, merged