(PC-23331)[BO] QA and global access roles have permissions only on st…
pass-culture/pass-culture-main pull request #7612
Opened 2023-08-03 13:35 UTC by charlesmorelpc

…aging

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23331

Appliquer les permissions des rôles QA et global access uniquement sur staging.
Ajout des permissions via le script `anonymize.sql`

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-08-03 14:45 UTC, dbaty requested changes

2023-08-03 14:45 UTC, dbaty commented on api/src/pcapi/scripts/rebuild_staging/anonymize.sql
> +INSERT INTO role_permission ("roleId", "permissionId") VALUES (1017, 1023) on conflict do nothing;
Le script `anonymize.sql` sert à anonymiser les données, d'où son nom ! ;) Ça n'est pas le bon endroit pour faire des modifications dans les données de staging.

Un meilleur endroit pourrait être une commande Flask, lancée lors de la restauration de staging, comme la commande `import_test_users`. D'ailleurs, peut-être qu'on pourrait renommer au passage cette commande en `setup_staging_users_and_back_office_profiles`, ou quelque chose d'approchant ?

2023-08-08 15:41 UTC, dbaty commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +    global_access_role = Role.query.filter(Role.name == "global-access").first()
(détail) Quand je lis ce code, je vois `.first()` et je me demande ce qu'on devrait faire s'il y a plusieurs éléments qui correspondent à ce critère. Mais en fait, ça n'est pas possible, car il y a une contrainte d'unicité sur `Role.name`. On pourrait éviter cette (petite) réflexion inutile en utilisant `one_or_none()`. Le résultat est le même, mais le code indique clairement qu'il ne peut y avoir que 0 ou 1 élément.

```suggestion
    qa_role = Role.query.filter(Role.name == "qa").one_or_none()
    global_access_role = Role.query.filter(Role.name == "global-access").one_or_none()
```

2023-08-08 15:41 UTC, dbaty commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +        logger.error('"global-access" role does not exists.')
On continue si `qa_role` ou `global_access_role` valent `None`. Or la fonction `_purge_role_permissions` tente d'accéder à l'attribut `id`. Elle va donc échouer avec un `AttributeError` assez peu évident à comprendre. Autant lever ici une exception (comme `ValueError('Cannot find "qa" role')`), ou bien logger un message d'erreur mais quitter prématurément la commande.

2023-08-08 15:41 UTC, dbaty commented on api/src/pcapi/scripts/rebuild_staging/anonymize.sql
> +    "phoneNumber" =  pg_temp.fake_phone_number_from_id(id);
hmmm, ok, c'est un peu gratuit, mais bon ;)

2023-08-09 08:35 UTC, charlesmorelpc commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +            )
Effectivement :D

2023-08-09 08:55 UTC, Meewan commented on api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
>  }
Pourquoi enleves-tu les droits dans la sandbox ? ça risque pas de poser des problemes en local/testing ?

2023-08-09 08:55 UTC, Meewan commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +        raise ValueError("This function is not supposed to be run on production")
un logger avec un return serait plus coherent avec la suite de la fonction
```suggestion
         logger.error("This function is not supposed to be run on production"')
        return
```

2023-08-09 08:55 UTC, Meewan commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +    db.session.bulk_save_objects(role_permissions_to_create)
à tester mais tu dois pouvoir te passer de cette ligne. (si ce n'est pas le cas je veux bien que tu me tiennes au courant)

2023-08-09 09:33 UTC, dbaty approved these changes

2023-08-09 09:41 UTC, charlesmorelpc commented on api/src/pcapi/sandboxes/scripts/creators/industrial/create_role_permissions.py
>  }
Euh ca c'est pas faux ^^'

2023-08-09 13:49 UTC, prouzet approved these changes

2023-08-09 15:23 UTC, Meewan commented on api/src/pcapi/scripts/backoffice_users/add_permissions_to_staging_specific_roles.py
> +    db.session.bulk_save_objects(role_permissions_to_create)
oui on en a partlé apres sur slack, c'était un mauvais conseil de ma part.

2023-08-10 07:52 UTC, merged