Pc 23287 eac add tracker for satisfaction survey
pass-culture/pass-culture-main pull request #7685
Opened 2023-08-08 13:56 UTC by antoinemrn

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23287

Logger l'information que l'utilisateur à ouvert le questionnaire de satisfaction sur Adage

FF à activer : WIP_ENABLE_SATISFACTION_SURVEY

2023-08-08 15:23 UTC, mariedestandau approved these changes

2023-08-08 15:23 UTC, mariedestandau commented on pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx
> +      queryId: queryId,
`removeParamsFromUrl` n'est pas nécessaire, `location.pathname` ne contient pas les query params,

2023-08-08 15:23 UTC, mariedestandau commented on pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx
> +      queryId: queryId,
je m'interroge sur l'utilisation de `location` vs `location = useLocation()`, j'essaie de réfléchir aux cas où `location` peut poser problème et je ne vois pas, à part que l'on ne peut pas le mocker, mais du coup justement là ça te permet de tester sans routeur ?

2023-08-08 16:46 UTC, borisLeBonPro requested changes

2023-08-09 06:21 UTC, antoinemrn commented on api/src/pcapi/routes/adage_iframe/logs.py
> -    body: serialization.ClosedSatisfactionSurvey,
En fait pour ce cas particulier le paramètre `source` ne semble pas pertinent c'est pour ça que j'ai utilisé AdageBaseModel car je n'avais pas besoin d'autres données. 
J'ai bien supprimer ClosedSatisfactionSurvey dans le dossier serialization normalement

2023-08-09 06:21 UTC, antoinemrn commented on api/src/pcapi/routes/adage_iframe/logs.py
> -            "source": body.source,
Voir au dessus

2023-08-09 06:24 UTC, antoinemrn commented on pro/src/pages/AdageIframe/app/components/SurveySatisfaction/SurveySatisfaction.tsx
> +      queryId: queryId,
Il me semble que dans les anciens tests Adage on surchargeait le window.location mais c'est peut être pas une bonne pratique. 
A l'usage ici location.pathname semble suffisant et j'ai pas eu de problème dans les tests mais je test que le cas nominal donc avec un `path = '/'`

2023-08-09 07:33 UTC, borisLeBonPro approved these changes

2023-08-09 10:19 UTC, merged