(PC-23987)[API] feat: add favorite for adage user to offer and template
pass-culture/pass-culture-main pull request #7985
Opened 2023-08-30 14:07 UTC by borisLeBonPro

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23987

recreate PR

2023-08-31 07:34 UTC, damien-ramelet commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    redactor = find_redactor_by_email(authenticated_information.email)  # type: ignore [arg-type]
Un peu dommage ces deux type ignore, est-ce qu’on pourrait pas juste mettre un `assert authenticated_information.email is not None` pour donner un coup de main à mypy si on est certain qu’à ce point ce field ne peut être null, ou si ça peut arriver peut être juste raise la même ApiError que ci-dessous puisque dans tous les cas si email vaut None `find_redactor_by_email` renverra None

2023-08-31 08:44 UTC, jeremieb-pass commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    assert authenticated_information.email is not None
L'email peut-être nul selon la définition de `AuthenticatedInformation`. 
Il faudrait sûrement vérifier explicitement qu'il ne l'est pas, et dans le cas contraire, renvoyer une erreur.

2023-08-31 08:46 UTC, jeremieb-pass commented on api/src/pcapi/core/educational/factories.py
> +    favoriteCollectiveOfferTemplates = factory.List([factory.SubFactory(CollectiveOfferTemplateFactory)])
Ces _factory_ ne sont pas nécessaires, si ? On pourrait appeler `EducationalRedactorFactory` et lui passer un paramètre `favoriteCollectiveOffers` ou `favoriteCollectiveOfferTemplates`. C'est ce qui est fait dans les tests en plus si j'ai bien compris.

2023-08-31 08:50 UTC, borisLeBonPro commented on api/src/pcapi/core/educational/factories.py
> +    favoriteCollectiveOfferTemplates = factory.List([factory.SubFactory(CollectiveOfferTemplateFactory)])
Elle le sont pour le test des offerers de raphael

2023-08-31 08:51 UTC, borisLeBonPro commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    assert authenticated_information.email is not None
Je ne suis pas sur que ce soit nécéssaire car si l'email est nul, le redactor ne sera pas trouvé et cela renverra a ce moment la une ApiError

2023-08-31 09:05 UTC, damien-ramelet commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    assert authenticated_information.email is not None
Justement, je te proposais deux solutions @borisLeBonPro: https://github.com/pass-culture/pass-culture-main/pull/7985#discussion_r1311216299

La première qui est celle-ci pour simplement guider mypy et lui dire "tkt, ici mail ne peut être null même si c’est possible d’après la définition"
En revanche, s’il est possible qu’Adage renvoi ce field vide, alors il est préférable d’appliquer ma seconde proposition, sinon on aura une belle AssertionError en prod, et une 500 renvoyée au client

2023-08-31 09:08 UTC, damien-ramelet requested changes
https://github.com/pass-culture/pass-culture-main/pull/7985#discussion_r1311329401

2023-08-31 09:20 UTC, borisLeBonPro commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    assert authenticated_information.email is not None
tu veux dire : 

```python
try:
        redactor = find_redactor_by_email(authenticated_information.email)
    except not authenticated_information.email:
        raise ApiErrors({"message": "Redactor not found"}, status_code=403)
```

Parce que mypy deteste encore plus du coup je ne suis pas sur de comprendre

2023-08-31 13:01 UTC, jeremieb-pass commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +        raise ApiErrors({"message": "email is mandatory"}, status_code=404)
Le message n'est pas juste : le token peut ne pas avoir d'email (si on se fie à sa déclaration). Le problème ici est que l'utilisateur authentifié n'est pas autorisé à effectuer cette action. Je te propose donc : 

```python
if not authenticated_information.email:
    raise ApiErrors({"global": "unauthorized"}, status_code=403)
```

2023-08-31 13:04 UTC, jeremieb-pass commented on api/src/pcapi/alembic/versions/20230830T095656_eff2f403eaac_create_table_collectiveoffereducationalredactor_and_.py
> +    # ### commands auto generated by Alembic - please adjust! ###
(détail) ces commentaires sont à supprimés (ceux avec des triples `#` comme ici)

2023-08-31 13:08 UTC, borisLeBonPro commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +        raise ApiErrors({"message": "email is mandatory"}, status_code=404)
Alors en effet, j'ai pas regardé précisement, cependant l'erreur ne devrait pas etre 403 mais 400 car un argument est manquant dans la request . Je me suis permis de corriger ainsi

2023-08-31 13:12 UTC, jeremieb-pass commented on api/src/pcapi/core/educational/factories.py
> +    favoriteCollectiveOfferTemplates = factory.List([factory.SubFactory(CollectiveOfferTemplateFactory)])
Corrige-moi si je me trompe, mais vu la manière dont est utilisée `EducationalRedactorWithFavoriteCollectiveOffer`, on pourrait avoir le même résultat en passant directement par `EducationalRedactorFactory` :

```python
educational_factories.EducationalRedactorFactory(favoriteCollectiveOffers=[offer1])
```

2023-08-31 13:17 UTC, jeremieb-pass commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +        raise ApiErrors({"message": "email is mandatory"}, status_code=404)
On ne va pas faire un débat de code http mais je maintiens que 404 n'est pas logique ici. 403 ou 401 pourquoi pas, 404 ça me semble étrange : ce n'est pas une histoire de ressource introuvable mais bien d'autorisation.

2023-08-31 13:18 UTC, jeremieb-pass commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    return serializers.FavoritesOfferResponseModel.from_orm(favorite)
A-t-on vraiment besoin de retourner quelque chose ? Surtout si ce sont exactement les mêmes données que celle envoyées par le client (via le token et le corps de la requête).

2023-08-31 13:20 UTC, jeremieb-pass commented on api/tests/routes/adage_iframe/post_favorite_template_test.py
> +        )
Est-il nécessaire de créer une offre ici ? Si l'utilisateur n'est pas authentifié, le code du contrôleur ne devrait même pas être exécuté, si ?

2023-08-31 13:28 UTC, jeremieb-pass commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +) -> serializers.FavoritesOfferResponseModel:
Attends je viens de réaliser un truc : pourquoi passer un id d'offre dans le corps de la requête ? Pourquoi ne pas aller au plus simple et le mettre dans l'URL ?

```python
@blueprint.adage_iframe.route("/collective/offers/<int:offer_id>/favorites", methods=["POST"])
@spectree_serialize(response_model=serializers.FavoritesOfferResponseModel, api=blueprint.api)
@adage_jwt_required
def post_collective_offer_favorites(
    authenticated_information: AuthenticatedInformation, offer_id: int
) -> serializers.FavoritesOfferResponseModel:
```

2023-08-31 13:29 UTC, jeremieb-pass commented on api/tests/routes/adage_iframe/post_favorite_offer_test.py
> +        }
C'est du détail mais : pourquoi appeler la variable `collective_offer_1` s'il n'y a qu'une seule offre ? `offer` suffit non ?

2023-08-31 13:33 UTC, borisLeBonPro commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +    return serializers.FavoritesOfferResponseModel.from_orm(favorite)
pour moi cela reste une preuve du fonctionnement notamment dans les tests.

2023-08-31 13:34 UTC, borisLeBonPro commented on api/tests/routes/adage_iframe/post_favorite_template_test.py
> +        )
Pour moi cela reste nécéssaire dans le sens ou l'on montre justement dans le test que ce qui plante c'est l'authentification et non le json

2023-08-31 14:09 UTC, borisLeBonPro commented on api/src/pcapi/routes/adage_iframe/favorites.py
> +        raise ApiErrors({"message": "email is mandatory"}, status_code=404)
D'apres Raphael : 
"_authenticated_information c'est adage qui vous l'envois non ?
[15 h 43](https://passcultureteam.slack.com/archives/D04574YQTCZ/p1693489418832429)
si vous avez dit que l'adresse mail est obligatoire et que ADAGE ne vous le transmet pas alors la requete est malformée -> 400_"

2023-08-31 16:13 UTC, jeremieb-pass approved these changes
J'approuve pour débloquer les autres tickets.

Pourras-tu penser à supprimer _caplog_ des paramètres d'entrée des fonctions de test si tu ne te sers pas de cette _fixture_ stp ?

2023-09-01 07:47 UTC, damien-ramelet commented on pro/src/apiClient/adage/services/DefaultService.ts
> +        422: `Unprocessable Entity`,
Est-ce qu'il ne faudrait rajouter les codes erreurs 400 et 404 qui sont maintenant susceptibles d'êtres renvoyés par le back ? même remarque ci-dessous

2023-09-01 08:04 UTC, damien-ramelet approved these changes

2023-09-01 08:04 UTC, merged