Ghaliela/pc 24128 verify number of tickets matches booking quantity
pass-culture/pass-culture-main pull request #8037
Opened 2023-09-04 09:44 UTC by ghaliela

## But de la pull request
Vérifier que le nombre de billet renvoyé par l'api charlie est le même que la quantité de réservation
(Un réservation peut être soit solo soit duo, donc la quantité maximale est 2)

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24128

## Vérifications

- [X] J'ai écrit les tests nécessaires

2023-09-20 12:19 UTC, mageoffray requested changes

2023-09-20 12:19 UTC, mageoffray commented on api/tests/routes/native/v1/bookings_test.py
> +        assert external_bookings.barcode in ["12123932898127", "12123932898117"]
Ca serait plus clair d'avoir un test avec =. J'ai l'impression qu'on testait 2 external_bookings avant de voir le `.one()`. 
J'ai l'impression qu'on supprime le 1er, on a un ordre consistant

2023-09-20 12:19 UTC, mageoffray commented on api/src/pcapi/core/external_bookings/api.py
> +        cancel_event_ticket(stock.offer.lastProvider, stock, [tickets[0].barcode], False)
Est-ce qu'on lance le cancel tout de suite ? Sachant qu'on fait un appel http (qui prends du temps) et qu'il peut y avoir des erreurs.
J'ajouterais plutot le ticker qu'on veut annuler à la queue REDIS_EXTERNAL_BOOKINGS_NAME pour qu'il soit automatiquement annulé quelques minutes après

2023-09-20 12:19 UTC, mageoffray commented on api/src/pcapi/routes/native/v1/bookings.py
> +        if providers_repository.is_event_external_ticket_applicable(stock.offer):
Je pense que tu peux factoriser les deux et ajouter le Message: %s dans le cas du cinema

2023-09-20 15:42 UTC, ghaliela commented on api/src/pcapi/routes/native/v1/bookings.py
> +        if providers_repository.is_event_external_ticket_applicable(stock.offer):
J'ai fait ça surtout parce que je sais pas si l'app mobile se base sur le code dans l'erreur, si je factorise les 2 et que j'envoie un autre code c'est un breaking change

2023-09-25 17:28 UTC, cepehang commented on api/tests/routes/native/v1/bookings_test.py
> +        assert external_bookings.barcode in ["12123932898127", "12123932898117"]
tu simules déjà l'ordre de création ligne 507

2023-09-26 08:44 UTC, ghaliela commented on api/tests/routes/native/v1/bookings_test.py
> +        assert external_bookings.barcode in ["12123932898127", "12123932898117"]
Lorsque je lance le test plusieurs fois, le comportement est aléatoire

2023-09-26 08:56 UTC, cepehang commented on api/tests/routes/native/v1/bookings_test.py
> +        assert external_bookings.barcode in ["12123932898127", "12123932898117"]
il y a des comportements bizarres avec requests_mock + pydantic, j'en ai déjà eu aussi

si tu peux au moins rajouter un commentaire, peut être que qqn plus tard aura la solution

2023-09-26 08:56 UTC, cepehang approved these changes
lgtm mais je n'ai pas tout le contexte de charlie en tête

2023-09-26 12:08 UTC, mageoffray approved these changes

2023-09-26 13:24 UTC, ghaliela commented on api/tests/routes/native/v1/bookings_test.py
> +        assert external_bookings.barcode in ["12123932898127", "12123932898117"]
Okay

2023-09-29 15:21 UTC, merged