(PC-24127) catch error if cancel ticket api returns error for already cancelled ticket
pass-culture/pass-culture-main pull request #8044
Opened 2023-09-05 09:38 UTC by ghaliela

## But de la pull request
Cette PR a pour but de catcher l'erreur si on essaie d'annuler un billet et que l'api externe renvoie une erreur parceque le billet est déjà annulé.
On log l'erreur pour avoir une trace (ça reste un comportement anormal) et on ne renvoie pas d'erreur afin de bien noter le booking cancelled en bd.

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24127

## Vérifications

- [X] J'ai écrit les tests nécessaires

2023-09-06 09:10 UTC, cepehang commented on api/tests/core/bookings/test_api.py
> +            pytest.fail("Should not raise an exception")
normalement la syntaxe pour tester des exceptions est `with pytest.raises(Exception):` mais pour tester qu'une fonction ne renvoit pas d'erreur tu peux écrire `assert api.cancel_booking_by_beneficiary(booking.user, booking) is None`

2023-09-08 08:46 UTC, cepehang requested changes

2023-09-08 08:46 UTC, cepehang commented on api/tests/core/bookings/test_api.py
> +    def test_raise_external_booking_error_if_trying_to_cancel_with_already_canceled_ticket(self, requests_mock):
le nom du test est faux, on teste l'absence d'erreur lancée

2023-09-11 08:44 UTC, mageoffray requested changes

2023-09-11 08:44 UTC, mageoffray commented on api/src/pcapi/core/bookings/api.py
> +            logger.warning("External ticket already cancelled for booking: %s. Error %s", booking.id, str(error))
Je pense qu'on peut mettre le logger au niveau info

2023-09-12 13:06 UTC, cepehang requested changes

2023-09-12 13:35 UTC, cepehang approved these changes

2023-09-13 14:22 UTC, mageoffray approved these changes

2023-09-13 14:24 UTC, merged