(PC-23622)[API] feat: Boost API use filter to get only showtimes payment method and hide full reservation showtimes
pass-culture/pass-culture-main pull request #8108
Opened 2023-09-08 14:52 UTC by yacine-pc

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23622

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-09-08 15:15 UTC, damien-ramelet requested changes

2023-09-08 15:15 UTC, damien-ramelet commented on api/src/pcapi/connectors/boost.py
> +    print("params", params)
T’as laissé des print dans le code ^^

2023-09-08 15:35 UTC, yacine-pc commented on api/src/pcapi/connectors/boost.py
> +    print("params", params)
Ah oui, bien vu je corrige

2023-09-11 06:57 UTC, damien-ramelet commented
Est-ce que c’est toujours nécessaire de faire le call `self._get_showtimes_details` dans `BoostStocks.__next__` du coup ? Si on rajoute ces filtres on aura déjà les prix dans chaque objet showtime et on s’évite un call http à chaque tour de boucle, @francois-seguin tu confirmes ?

2023-09-11 08:17 UTC, yacine-pc commented
Oui on est toujours obligé de faire l'appel `self._get_showtimes_details` pour l'instant, car avec le filtre on est sûr d'avoir que les séances qui ont un tarif PCU, par contre on connait pas le tarif de chacune des séances, les séances peuvent avoir des tarifs différents.

2023-09-13 14:06 UTC, damien-ramelet approved these changes

2023-09-13 15:54 UTC, merged