(PC-24311)[API] feat: Added dmsToken to offerer table.
pass-culture/pass-culture-main pull request #8129
Opened 2023-09-11 15:24 UTC by AmineLouveau

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24311

- Ajout de la colonne dmsToken à la table Offerer
- Ajout du script de rattrapage
- Changement de la vue pour le front.

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-09-11 16:55 UTC, damien-ramelet requested changes

2023-09-11 16:55 UTC, damien-ramelet commented on api/src/pcapi/core/offerers/models.py
> +    dmsToken: str = Column(Text, nullable=False, unique=True)
alembic ne détecte pas les contraintes d’unicité si elle ne sont pas explicitement déclarée dans le modèle, elle est manquante dans la migration

2023-09-12 14:51 UTC, dbaty commented on api/src/pcapi/core/offerers/factories.py
> +    dsmToken = "1234567890abcdef"
d**ms**Token, d**sm**Token, dsToken ? :exploding_head: Il va falloir choisir ! :)

2023-09-12 14:51 UTC, dbaty commented on api/src/pcapi/core/offerers/models.py
> +    dmsToken: str = Column(Text, nullable=True, unique=True)
(question) Souhaite-t-on vraiment cette modification ? Je ne vois rien dans la pull request qui indique que ce champ est désormais nullable. (Je suppose que ça viendra plus tard, quand on n'aura plus besoin du champ. Mais, pour l'instant, on devrait à mon avis conserver cette contrainte.)

2023-09-12 14:51 UTC, dbaty commented on api/src/pcapi/scripts/offerer/generate_dms_tokens.py
> +"""
[question / bug] Ce script remplit la colonne si elle est vide. Mais ne devrait-on pas modifier la fonction `core.offerers.api.create_offerer()` pour renseigner ce champ à la création ?

2023-09-12 14:51 UTC, dbaty commented on api/src/pcapi/core/offerers/models.py
> +    dmsToken: str = Column(Text, nullable=False, unique=True)
La contrainte NOT NULL ne pourra être appliquée qu'après le passage du script. En attendant, la colonne doit être NOT NULLable : 

```suggestion
    dmsToken: str = Column(Text, nullable=True, unique=True)
```

2023-09-12 15:12 UTC, AmineLouveau commented on api/src/pcapi/core/offerers/factories.py
> +    dsmToken = "1234567890abcdef"
Ouch, bien vu

2023-09-12 15:13 UTC, AmineLouveau commented on api/src/pcapi/core/offerers/models.py
> +    dmsToken: str = Column(Text, nullable=True, unique=True)
Non, effectivement, je n'ai pas fait attention, et changé le mauvais.

2023-09-12 15:17 UTC, AmineLouveau commented on api/src/pcapi/scripts/offerer/generate_dms_tokens.py
> +"""
Corrigé !

2023-09-13 09:06 UTC, dbaty commented on api/src/pcapi/core/offerers/api.py
> +        offerer.dsToken = generate_dms_token()
Je note que la fonction `generate_dms_token()` vérifie l'existence du token dans la table `venue` (parce que c'est là qu'on l'utilise actuellement), mais pas dans la table `offerer`. Donc, théoriquement, on a un risque de générer un token existant, mais l'insertion en base de données échouera grâce à la contrainte d'unicité. On est OK pour la cohérence des données, mais j'ai peur que l'erreur soit peu visible pour l'utilisateur (ou, pire, que ça fasse une 500).

Peut-être qu'on devrait modifier `dms_token_exists()` pour vérifier si le token généré existe dans `venue` **ou** `offerer` ?

2023-09-13 09:18 UTC, AmineLouveau commented on api/src/pcapi/core/offerers/api.py
> +        offerer.dsToken = generate_dms_token()
J'ai fait en sorte d'avoir deux fonctions différentes histoire de ne pas avoir de problème si on utilise un id qui est dans venues, mais pas offerer.

2023-09-13 13:59 UTC, dbaty approved these changes

2023-09-13 14:03 UTC, damien-ramelet approved these changes

2023-09-13 14:06 UTC, merged