(PC-23772)[API] feat: add isActivable on Offer
pass-culture/pass-culture-main pull request #8146
Opened 2023-09-12 13:37 UTC by OlivierGeber

## But de la pull request

Ajout d'une propriété `isActivable` sur les offres pour informer le front qu'une offre n'est plus activable en cas de suppression d’une synchronisation

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-23772

## Vérifications

- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-09-13 08:27 UTC, Vencespass approved these changes
Nice

2023-09-13 08:27 UTC, Vencespass commented on api/src/pcapi/core/offers/models.py
> +            return False
```suggestion
        if self.status == OfferStatus.REJECTED or not self.isBookable:
            return False
```

2023-09-13 09:33 UTC, dbaty commented on api/src/pcapi/core/offers/models.py
> +        if self.lastProvider and not self.lastProvider.isActive:
[discussion / correction] Je ne suis pas sûr de cette condition. Si le "lastProvider" est inactif, il y a peu de chance qu'on ait un VenueProvider actif. Et même, je pense que ce serait un bug.

Je verrais plutôt une condition basée sur le VenueProvider, quelque chose comme ça : 

```python
if self.lastProviderId:
    # Si le VenueProvider correspondant n'est pas actif, on ne devrait pas pouvoir activer l'offre.
    if not VenueProvider.query.filter_by(isActive=True, providerId=self.lastProvider).one_or_none():
        return False
```

Qu'en penses-tu ?

2023-09-13 16:19 UTC, OlivierGeber commented on api/src/pcapi/core/offers/models.py
> +        if self.lastProvider and not self.lastProvider.isActive:
yes merci, c'est mis à jour 👍

2023-09-14 09:46 UTC, dbaty requested changes

2023-09-14 09:46 UTC, dbaty commented on api/src/pcapi/core/offers/models.py
> +            ).one_or_none()
[bug] Il manque le filtre sur le lieu de l'offre (`VenueProvider` est une table d'association entre un lieu et un provider de synchronisation d'offres).

2023-09-14 11:54 UTC, OlivierGeber commented on api/src/pcapi/core/offers/models.py
> +            ).one_or_none()
j'ai rajouté le filtre, dis moi ce que tu en penses

2023-09-14 14:59 UTC, dbaty commented on api/src/pcapi/infrastructure/repository/pro_offers/offers_recap_domain_converter.py
> +        venue_public_name=offer.venue.publicName,  # type: ignore [arg-type]
mypy rapporte une erreur ici (que tu as essayé de masquer). mypy a raison : la signature de `OfferRecap.__init__` indique que `venue_public_name` est de type `str` (donc jamais `None`). Or, ici, on passe `Venue.publicName` qui est un champ nullable (donc la valeur peut être `None`). Il faudrait donc corriger le typage dans la signature de `OfferRecap.__init__` (et probablement aussi `OfferRecapVenue.__init__`.

2023-09-15 07:09 UTC, dbaty approved these changes

2023-09-15 07:29 UTC, merged