Ghaliela/pc 24396 notify external api on booking
pass-culture/pass-culture-main pull request #8188
Opened 2023-09-14 14:33 UTC by ghaliela

## But de la pull request
Appeler l'url de notification fournie par le provider à chaque réservation ne passant pas par l'api charlie

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24396

## Vérifications

- [ ] J'ai écrit les tests nécessaires

2023-09-19 14:33 UTC, dbaty commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +    requests.post(payload.notificationUrl, json=payload.data, headers={"Content-Type": "application/json"})
Que se passe-t-il en cas d'erreur réseau ? Que se passe-t-il si on reçoit autre chose qu'une réponse 20x ?

[détail] Préciser l'en-tête `Content-Type` est inutile quand on utilise l'argument `json` (cf. [la doc](https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests)).

2023-09-19 14:33 UTC, dbaty commented on api/src/pcapi/tasks/serialization/external_api_booking_notification_tasks.py
> +        cls, stock: offers_models.Stock, booking: bookings_models.Booking, user: User, action: BookingAction
[détail] Cette fonction pourrait ne recevoir que l'argument `booking`. Les valeurs pour `stock` et `user` pourraient en être dérivées (via `booking.stock` et `booking.user`). Idem pour ExternalEventBookingRequest.

2023-09-19 14:55 UTC, ghaliela commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +    requests.post(payload.notificationUrl, json=payload.data, headers={"Content-Type": "application/json"})
C'est une tache asynchrone qui sert à notifier l'url donnée par nos provider qu'une réservation a eu lieu ou a été annulé, ce qui n'est pas fait pour l'instant
Donc si on a autre chaose qu'une 20x on fait rien

2023-09-19 14:57 UTC, cepehang requested changes

2023-09-19 14:57 UTC, cepehang commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +from pcapi import settings
il faut importer ce fichier dans `api/src/pcapi/tasks/__init__.py` sinon tu vas te faire engueulé comme je l'ai été ajd haha

cf https://github.com/pass-culture/pass-culture-main/pull/8256/files#diff-b83c41de5ebdf402ac398bb156d86610a806b54583b864fd380687184ea951eaR30

2023-09-19 14:57 UTC, cepehang commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +    requests.post(payload.notificationUrl, json=payload.data, headers={"Content-Type": "application/json"})
Les erreurs lancées par les tâches cloud doivent être/hériter de `ExternalAPIException`

cf. https://github.com/pass-culture/pass-culture-main/blob/91b47b58adb153fbf5f7e8dfcec48c16805c18b9/api/src/pcapi/tasks/decorator.py#L81

2023-09-20 06:14 UTC, dbaty commented on api/src/pcapi/core/bookings/api.py
> +        not booking.stock.offer.withdrawalType == offers_models.WithdrawalTypeEnum.IN_APP
[détail / style] Vu la longueur de la ligne, le temps d'arriver au "==", on aura oublié le "not". ;) Autant utiliser "!=".

```suggestion
        booking.stock.offer.withdrawalType != offers_models.WithdrawalTypeEnum.IN_APP
```

2023-09-20 06:14 UTC, dbaty commented on api/src/pcapi/core/external_bookings/serialize.py
> +            offer_id=booking.stock.offer.id,
[détail] On pourrait s'éviter toutes ces modifications et, surtout, faciliter la lecture du code, en définissant des variables `stock` et `user` (voire aussi `offer`) en début de fonction.

2023-09-20 06:14 UTC, dbaty commented on api/src/pcapi/core/bookings/api.py
> +
[tests] Ce serait peut-être bien d'ajouter un test minimal, non ?

2023-09-20 10:13 UTC, ghaliela commented on api/src/pcapi/core/external_bookings/serialize.py
> +            offer_id=booking.stock.offer.id,
ici on peut pas utiliser le stock et le user du booking parce que lorsqu'on appelle le serializer on est toujours dans la transaction, donc on a que le `booking.stockId` et `booking.userId`, mais `booking.stock` et `booking.user` retournent `NoneType`

2023-09-20 10:13 UTC, ghaliela commented on api/src/pcapi/core/bookings/api.py
> +
Je sais pas comment tester une fonction asynchrone

2023-09-20 12:59 UTC, ghaliela commented on api/src/pcapi/core/bookings/api.py
> +
Done

2023-09-20 13:09 UTC, dbaty commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +    except requests.ExternalAPIException as exception:
Cette exception n'est pas levée par `post()`. Pour faire simple, tu peux `except requests.exceptionsRequestException` ([cf. doc](https://requests.readthedocs.io/en/latest/user/quickstart/?highlight=raise_for_status()#errors-and-exceptions)).

Par contre, cela ne prendra en compte que les erreurs réseau (timeout, DNS, etc.). Aucune exception n'est levée si on reçoit bien une réponse, mais que son statut HTTP n'est pas une 20x. Or on aimerait certainement logger aussi ces erreurs, j'imagine. Pour cela, tu peux appeler `response.raise_for_status()` ([cf. doc](https://requests.readthedocs.io/en/latest/user/quickstart/?highlight=raise_for_status()#response-status-codes)).

2023-09-20 15:46 UTC, cepehang approved these changes

2023-09-20 15:46 UTC, cepehang commented on api/src/pcapi/tasks/__init__.py
> +from pcapi import settings
import inutile

2023-09-20 16:00 UTC, dbaty commented on api/tests/routes/native/v1/bookings_test.py
> +        assert data["offer_ean"] == "1234567890123"
`__dict__` est un attribut privé, n'y a-t-il pas un autre moyen d'accéder aux données ? Il me semble que le code suivant fonctionne (et serait plus lisible) : 

```suggestion
        notification = mocked_task.call_args.args[0].data
        assert data.offfer_ean == "1234567890123"
```

Tu noteras aussi qu'on peut accéder directement aux attributs de `ExternalApiBookingNotificationRequest` , ce qui évite la lourdeur d'un accès via `__dict__`.

2023-09-20 16:22 UTC, dbaty commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +    except (requests.exceptions.HTTPError, requests.exceptions.RequestException) as exception:
`HTTPError` dérive de `RequestException`, donc en attrapant la seconde (la classe de base), tu attrapes aussi la première : 

```suggestion
    except requests.exceptions.RequestException as exception:
```

2023-09-20 16:29 UTC, dbaty commented on api/src/pcapi/tasks/serialization/external_api_booking_notification_tasks.py
> +    def build_external_api_notification_request(
[détail / style] Je pense qu'on pourrait l'appeler `build()` sans trop perdre en compréhension. Ça a le mérite d'être sensiblement plus court. :)

2023-09-20 16:46 UTC, dbaty approved these changes

2023-09-20 16:51 UTC, merged