(BSR)[API] refactor: Make `CineDigitalServiceAPI.get_hardcoded_setmap()` return a list, not JSON
pass-culture/pass-culture-main pull request #8322
Opened 2023-09-22 15:54 UTC by dbaty

Code (including typing annotations) is clearer that way.

2023-09-25 06:31 UTC, damien-ramelet requested changes

2023-09-25 06:31 UTC, damien-ramelet commented on api/tests/core/external_bookings/cds/test_client.py
> +        mocked_hardcoded_seatmap = [
`json.dumps` du coup ? Je pense que c’est pour ça que le test plante @dbaty

2023-09-25 07:29 UTC, damien-ramelet commented
json.dumps du coup ? Je pense que c’est pour ça que le test plante @dbaty

2023-09-25 07:29 UTC, damien-ramelet commented on api/tests/core/external_bookings/cds/test_client.py
> +        mocked_hardcoded_seatmap = [
json.dumps du coup ? Je pense que c’est pour ça que le test plante @dbaty

2023-09-25 08:45 UTC, dbaty commented on api/tests/core/external_bookings/cds/test_client.py
> +        mocked_hardcoded_seatmap = [
Pour le test en échec, cf. mon commentaire de pull request (commentaire que j'avais brillamment oublié de soumettre...)

2023-09-25 11:41 UTC, damien-ramelet commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
Non je ne pense pas que le problème soit là, le soucis est que l’on mock le retour de l'API du provider en l'hardcodant sous forme de liste de liste de strings. Hors notre connecteur attend une payload au format JSON dont le cinema_parameters sera `json.loads` dans `get_hardcoded_seatmap` (l. 136)

```
>>> cinema.cinema_parameters                                                                                                                                                      Breakpoints:
[CinemaParameterCDS(id=1, key='SEATMAP_HARDCODED_LABELS_SCREENID_30', value='[["C_17", "C_15", 0, "C_13", "C_11", "C_9"], ["B_17", "B_15", 0, "B_13", "B_11", "B_9"], ["A_19",    
"A_17", "A_15", "A_13", "A_11"]]')]                                                                                                                                               
```

@dbaty

2023-09-25 11:43 UTC, damien-ramelet commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
La seule raison pour laquelle l’autre test ne fail pas (l’autre dont tu as modifié le mock, `test_should_return_seat_available_when_seatmap_is_hardcoded`) c’est parce que l’appel à la méthode qui décode la payload est mockée, donc on passe silencieusement dessus, il faut juste json.dumps la payload dans le test (ou laisser les singles quotes)

2023-09-25 11:45 UTC, damien-ramelet commented on api/tests/core/external_bookings/cds/test_client.py
> +        ]
```suggestion
        mocked_hardcoded_seatmap = json.dumps([
            ["C_17", "C_15", 0, "C_13", "C_11", "C_9"],
            ["B_17", "B_15", 0, "B_13", "B_11", "B_9"],
            ["A_19", "A_17", "A_15", "A_13", "A_11"],
        ])
```

2023-09-25 11:54 UTC, damien-ramelet commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
`CinemaParametersCDS.value` représente la totalité de la seatmap et non chaque place individuellement, je pense que la confusion vient de là (en revanche je n’ai aucune idée pour le 0, peut-être que ce sont les places déjà achetées ?)

2023-09-27 09:31 UTC, dbaty commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
> [...] Hors notre connecteur attend une payload au format JSON [...]

Tu as raison, j'ai corrigé le test comme tu l'as suggéré. Bien vu, merci ! :)

La question sur le mélange de int et de str demeure : 
1. Soit le test est incorrect : on reçoit exclusivement des strings. Il faut remplacer 0 par "0" dans le test. On pourra aussi typer hardcoded_seatmap comme list[str].
2. Soit le test est correct : on peut recevoir des 0 (int), pas seulement des strings. Donc le typage de hardcoded_seatmap devrait être list[str | int]. Mais self.seatNumber doit bien être une str (comme actuellement), donc il faudrait écrire self.seatNumber = str(hardcoded_seatmap[self.seatRow][self.seatCol]) pour s'assurer d'y enregistre une string.
3. Idem 2, mais le typage de self.seatNumber est incorrect : il devrait être str | int (au lieu de str). Le reste du code gère déjà ça.
4. La quatrième réponse.

Je relance les Experts à ce sujet.

2023-09-27 10:28 UTC, damien-ramelet commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
@yacine-pc tu as une idée ?

2023-09-27 12:27 UTC, yacine-pc commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
Je choisis la réponse 4, plus sérieusement on peut recevoir des 0 (int) et pas seulement des strings. Oui le typage de `hardcoded_seatmap` devrait être `list[str | int]`. Par contre `self.seatNumber` **théoriquement** ne peut être qu'un string (Si notre algorithme de choix de places fonctionne correctement) car c'est numéro de siège et les 0 (int) dans `hardcoded_seatmap` correspondent à des espaces vides (Pas de siège) donc ces places ne seront pas sélectionnées par l'algorithme de choix de places car il n'y a pas de siège.

2023-09-27 15:47 UTC, damien-ramelet approved these changes

2023-09-28 08:15 UTC, dbaty commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
@yacine-pc : merci pour ces infos. J'ai modifié le typage dans un commit dédié : https://github.com/pass-culture/pass-culture-main/pull/8322/commits/ffe43c32f6774a9e9a6805f82188fc38fad4392e. Est-ce que ça te paraît OK ?

2023-09-28 15:20 UTC, yacine-pc approved these changes

2023-09-28 15:21 UTC, yacine-pc commented on api/src/pcapi/connectors/serialization/cine_digital_service_serializers.py
>              self.seatNumber: str = hardcoded_seatmap[self.seatRow][self.seatCol]
Oui ça me parait OK comme ça, merci pour cette refacto et correction de typos :scream:

2023-09-29 08:15 UTC, merged