(PC-24612)[PRO] feat: ajout label et direction d'affichage ON_SITE
pass-culture/pass-culture-main pull request #8430
Opened 2023-09-28 14:52 UTC by TetyanaZhabchyk

https://passculture.atlassian.net/browse/PC-24612

Modifier l'intitulé de la 4ème option de modalité de retrait:

<img width="801" alt="Capture d’écran 2023-09-28 à 16 48 28" src="https://github.com/pass-culture/pass-culture-main/assets/115089249/0bae9284-e3ac-4a8e-866b-1f50f82e9435">

Branche: PC-24612-style-retrait

2023-09-28 14:58 UTC, AmineLouveau approved these changes

2023-09-28 15:11 UTC, Aliochka requested changes

2023-09-28 15:11 UTC, Aliochka commented on pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/constants.ts
> +  },
tu peux enlever cet ajout !
```suggestion
```

2023-09-29 07:31 UTC, TetyanaZhabchyk commented on pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/constants.ts
> +  },
Merci, j'ai mit cars quand je le supprime, label n'affiche plus ou c'est doit être invisible?
<img width="511" alt="Capture d’écran 2023-09-29 à 09 27 07" src="https://github.com/pass-culture/pass-culture-main/assets/115089249/3a83c765-b126-4a18-992c-8349d526e558">

2023-09-29 08:07 UTC, Aliochka commented on pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/constants.ts
> +  },
pour comprendre tu peux regarder son usage :

```
        {/*
          IN_APP withdrawal type is only selectable by offers created by the event API
          Theses offers are not editable by the user
        */}
        <RadioGroup
          group={
            withdrawalType === WithdrawalTypeEnum.IN_APP
              ? providedTicketWithdrawalTypeRadios
              : ticketWithdrawalTypeRadios
          }
          legend="Précisez la façon dont vous distribuerez les billets :"
          name="withdrawalType"
          // when withdrawal Type is IN_APP the field should also be readOnly.
          // I find it better to be explicit about it
          disabled={
            readOnlyFields.includes('withdrawalType') ||
            withdrawalType === WithdrawalTypeEnum.IN_APP
          }
        />
```

regarde le commentaire au début IN_APP est disponible seulement pour les offres créées via l'event API et dans ce cas le champ ne sera pas éditable
`readOnlyFields.includes('withdrawalType') ||
            withdrawalType === WithdrawalTypeEnum.IN_APP`

et seulement dans ce cas on l'affiche : 
`group={
            withdrawalType === WithdrawalTypeEnum.IN_APP
              ? providedTicketWithdrawalTypeRadios
              : ticketWithdrawalTypeRadios
          }`

2023-09-29 08:08 UTC, Aliochka approved these changes

2023-09-29 08:18 UTC, TetyanaZhabchyk commented on pro/src/components/IndividualOfferForm/UsefulInformations/TicketWithdrawal/constants.ts
> +  },
J'ai tout compris. Merci beaucoup.

2023-09-29 08:18 UTC, merged