Ghaliela/pc 24718 add hmac signature to charlie request in header
pass-culture/pass-culture-main pull request #8456
Opened 2023-09-29 14:46 UTC by ghaliela

## But de la pull request
Add hmac signature in http header for charlie api

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24718

2023-10-02 07:42 UTC, mageoffray requested changes
Je m'attendais aussi à avoir des tests. Je pense qu'il manque au moins 3 tests, un pour chaque cas d'appel.

2023-10-02 07:42 UTC, mageoffray commented on api/src/pcapi/core/bookings/api.py
> +    signature = hmac.new(
Tu peux créer une fonction generate_hmac_signature qui prends la clé et la payload dans pcapi.utils.requests.

2023-10-02 07:42 UTC, mageoffray commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +        response = requests.post(
Comme conseil damien, tu devrais pouvoir ajouter à notre implémentation du post de request pour ajouter un paramètre hmac.

2023-10-02 07:42 UTC, mageoffray commented on api/src/pcapi/tasks/external_api_booking_notification_tasks.py
> +            headers={"Content-Type": "application/json", "X-Hmac-Signature": payload.signature},
La convention qui veut qu'on nomme les headers custom avec [un préfix X a été drop en 2012](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers). Il est recommandé maintenant de ne pas avoir ce suffixe ! 
Je nommerais bien ce header "PassCulture-Signature"

2023-10-02 07:42 UTC, mageoffray commented on api/src/pcapi/core/bookings/api.py
> +    signature = hmac.new(
Ca permet d'assurer que tous les appels sont fait avec le même format, sur le même encodage.. Et que si un jour ça change, ça change partout

2023-10-03 14:08 UTC, ghaliela commented
> Je m'attendais aussi à avoir des tests. Je pense qu'il manque au moins 3 tests, un pour chaque cas d'appel.

Je pense que c'est inutile parcequ'on ajoute un header à la requête, ça ne change rien de notre côté

2023-10-05 12:00 UTC, mageoffray approved these changes

2023-10-05 12:02 UTC, merged