(PC-24658)[API] feat: add order by several fields for stocks route
pass-culture/pass-culture-main pull request #8462
Opened 2023-09-29 15:37 UTC by OlivierGeber

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24658

## Vérifications

- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-10-02 12:02 UTC, damien-ramelet commented on api/src/pcapi/core/offers/repository.py
> +    match order_by:
```suggestion
 -> flask_sqlalchemy.BaseQuery:
     column: sa_orm.Mapped[int] | sa.cast[sa.Date | sa.Time, sa_orm.Mapped[datetime.datetime | None]]
     match order_by:

```

Tu n’as plus besoin des deux type: ignore avec ceci

2023-10-02 12:08 UTC, damien-ramelet approved these changes

2023-10-02 12:08 UTC, damien-ramelet commented on api/src/pcapi/core/offers/repository.py
> +    match order_by:
sinon ok pour moi

2023-10-02 12:21 UTC, mageoffray requested changes

2023-10-03 09:31 UTC, mageoffray approved these changes

2023-10-03 09:42 UTC, merged