(PC-24356)[BO] fix: Collective offer price editing
pass-culture/pass-culture-main pull request #8648
Opened 2023-10-12 09:34 UTC by charlesmorelpc

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-24356

Fix d'une première solution à ce ticket, permettant de mettre à jour le prix/nombre de tickets d'une offre collective à partir du moment où celle-ci n'a pas de pricing.

## Vérifications

- [x] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-10-17 12:52 UTC, dbaty commented on api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
>          finance_api.cancel_pricing(booking=collective_booking, reason=finance_models.PricingLogReason.CHANGE_AMOUNT)
2 problèmes, ici : 

1. `collective_booking` peut être nul. Dans ce cas, on ne devrait pas tenter d'appeler `cancel_pricing()`, car cette fonction requiert une réservation.
2. `cancel_pricing()` sera bientôt du passé. :) Il faudrait plutôt manipuler des FinanceEvent : annuler le FinanceEvent existant (s'il y en a un) et, ajouter un nouveau FinanceEvent. Quelque chose comme ce bloc : https://github.com/pass-culture/pass-culture-main/blob/04f261a68a1a95d90f9023889d235bfd2e2c41db/api/src/pcapi/core/bookings/api.py#L458-L466

2023-10-23 13:08 UTC, Meewan requested changes

2023-10-23 13:08 UTC, Meewan commented on api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
> +        if not is_pending and number_of_tickets > collective_offer.collectiveStock.numberOfTickets:
Attention il me semble qu'on peut aussi modifier librement l'offre quand on est en "Booked"

2023-10-23 13:08 UTC, Meewan commented on api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
> +        if not is_pending and price > collective_offer.collectiveStock.price:
Attention il me semble qu'on peut aussi modifier librement l'offre quand on est en "Booked"

2023-10-23 13:08 UTC, Meewan commented on api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
> +            flash("Impossible d'augmenter le prix")
```suggestion
            flash("Impossible d'augmenter le prix d'une réservation confirmée.")
```

2023-10-23 13:08 UTC, Meewan commented on api/src/pcapi/routes/backoffice/collective_offers/collective_offers_blueprint.py
> +            flash("Impossible d'augmenter le nombre de participants", "warning")
```suggestion
            flash("Impossible d'augmenter le nombre de participants d'une offre confirmée.", "warning")
```

2023-10-26 06:38 UTC, antoinemrn approved these changes
Ok pour la partie fonctionnel 👌

2023-10-26 07:59 UTC, Meewan approved these changes

2023-10-26 09:04 UTC, merged

2023-10-26 10:08 UTC, dbaty reviewed
J'avais oublié d'envoyer mon commentaire...