(PC-25032) Allow more categories offer creation on individual api
pass-culture/pass-culture-main pull request #8748
Opened 2023-10-19 15:11 UTC by ghaliela

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25032

## Vérifications

- [X] J'ai écrit les tests nécessaires

2023-10-24 13:43 UTC, OlivierGeber commented on api/src/pcapi/routes/public/individual_offers/v1/serialization.py
> +    subcategories.TELECHARGEMENT_MUSIQUE,
J'ai envie de trier ça par ordre alphabétique mais c'est peut-être inutile ? 

```suggestion
    subcategories.ABO_BIBLIOTHEQUE,
    subcategories.ABO_CONCERT,
    subcategories.ABO_LIVRE_NUMERIQUE,
    subcategories.ABO_MEDIATHEQUE,
    subcategories.ABO_MUSEE,
    subcategories.ABO_PLATEFORME_MUSIQUE,
    subcategories.ABO_PLATEFORME_VIDEO,
    subcategories.ABO_PRATIQUE_ART,
    subcategories.ABO_PRESSE_EN_LIGNE,
    subcategories.ABO_SPECTACLE,
    subcategories.ACHAT_INSTRUMENT,
    subcategories.APP_CULTURELLE,
    subcategories.AUTRE_SUPPORT_NUMERIQUE,
    subcategories.CAPTATION_MUSIQUE,
    subcategories.CARTE_JEUNES,
    subcategories.CARTE_MUSEE,
    subcategories.LIVRE_AUDIO_PHYSIQUE,
    subcategories.LIVRE_NUMERIQUE,
    subcategories.LOCATION_INSTRUMENT,
    subcategories.PARTITION,
    subcategories.PLATEFORME_PRATIQUE_ARTISTIQUE,
    subcategories.PODCAST,
    subcategories.PRATIQUE_ART_VENTE_DISTANCE,
    subcategories.SPECTACLE_ENREGISTRE,
    subcategories.SUPPORT_PHYSIQUE_FILM,
    subcategories.TELECHARGEMENT_LIVRE_AUDIO,
    subcategories.TELECHARGEMENT_MUSIQUE,
    subcategories.VISITE_VIRTUELLE,
    subcategories.VOD,
```

2023-10-24 13:43 UTC, OlivierGeber commented on api/tests/routes/public/individual_offers/v1/patch_product_test.py
> -            },
Du coup si on enlève les extraData, ce test n'a plus vraiment d'intérêt ?

2023-10-24 13:43 UTC, OlivierGeber commented on api/tests/routes/public/individual_offers/v1/post_product_test.py
>                              "musicType": "ROCK-LO_FI",
ligne à supprimer

2023-10-24 14:40 UTC, OlivierGeber approved these changes

2023-10-24 14:56 UTC, OlivierGeber requested changes

2023-10-24 14:56 UTC, OlivierGeber commented on api/tests/routes/public/individual_offers/v1/patch_product_test.py
> +                "TELECHARGEMENT_MUSIQUE products can be edited"
du coup faut aussi modifier ça ici

2023-10-24 15:19 UTC, ghaliela commented on api/tests/routes/public/individual_offers/v1/patch_product_test.py
> +                "TELECHARGEMENT_MUSIQUE products can be edited"
Ah yess

2023-10-25 08:24 UTC, OlivierGeber approved these changes

2023-10-25 12:06 UTC, merged