(PC-12112) feat:email_update: add validate button
pass-culture/pass-culture-main pull request #895
Opened 2021-12-30 20:05 UTC by jeremieb-pass

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12112

## But de la pull request

Permettre à un admin (FA) de valider manuellement une demande de modification d'un email à deux endroits : 

1. sur la page d'index des demandes de modifications ;
2. sur la vue détaillée d'un bénéficiaire, dans la section des modifications d'email.

A chaque fois, le bouton n'apparaît que sur les lignes qui correspondent à un événement `UPDATE_REQUEST`.

On pourrait filtrer encore mieux et ne l'afficher que sur les lignes qui n'ont pas d’événements `VALIDATION` ou `ADMIN_VALIDATION` associés (même utilisateur, mêmes ancienne et nouvelle adresse) mais je n'ai pas trouvé comment passer du SQL à SQLAlchemy / FlaskAdmin 😭

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture requested changes
seul les super admins devraient avoir le droit de faire des changements

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/users/factories.py
> +class UserEmailHistoryFactory(BaseFactory):
il est possible d'appeler cette factory, alors qu'elle contient un état impossible (il manque l'`eventType`)

est-ce qu'en python, il y a un moyen d'indiqué qu'une classe est "privée" / "protected" ?

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/users/email/repository.py
> +        user=entry.user,
est-ce qu'en faisant `user=entry.user`, l'ORM est suffisament intelligent pour ne pas faire une requete sur la table `user` alors qu'on a juste beosin de l'`userId`dans ce cas ?

si non, est-ce qu'on pourrait changer la requete pour quelque chose ressemblant à `userId=entry.userId` ?

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                    action={{ url_for("/user_email_history.validate_user_email", entry_id=email_history.id, next="support_beneficiary.details_view", id=model.id) }}
en plus, la méthode `validate_user_email` semble n'utiliser que `entry_id`

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/admin/custom_views/user_email_history_view.py
> +                f"L'adresse email {entry.newEmail} de l'utilisateur {entry.userId} avait déjà été validée",
est-ce que les chaines sont échappées ou est-ce qu'il y a un risque d'XSS ?

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/admin/custom_views/user_email_history_view.py
> +                flash(f"L'utilisateur avec l'adresse email {entry.oldEmail} n'a pas été trouvé", category="error")
je ne comprends pas comment ce cas peut arriver ?

comment `entry = UserEmailHistory.query.get(entry_id)` pourrait retourner quelque chose, mais `users_api.change_user_email`ne trouverais pas l'user ?

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/testing.py
> +def assert_evolution(model, delta):
je ne suis pas 100% certain de comprendre ce que fait cette fonction

est-ce qu'elle vérifie le nombre de changement d'adresse email ?

si oui, est-ce qu'on pourrait la nommer avec quelque chose comme `assert_count_new_entry_email_history` ?

2021-12-31 09:25 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/templates/admin/list_user_email_history.html
> +    {% if row.eventType.value == 'UPDATE_REQUEST' %}
ici aussi, est-ce qu'il serait possible d'utiliser l'`enum` plutot qu'une string ayant la meme valeur ?

2021-12-31 09:38 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                    <button title="Approve">
je propose d'ajouter `class="btn btn-warning"` ou `class="btn btn-secondary"` pour que ça soit ~~moins moche~~ **visuellement plus sympathique**

2021-12-31 09:42 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/templates/admin/list_user_email_history.html
> +            <button title="Approve">Valider</button>
pour éviter les miss-clicks, je propose d'ajouter une modale de confirmation

par exemple : ` onclick="return confirm('Êtes-vous certain de vouloir valider l\'adresse email {{row.newEmail}}')"`

2021-12-31 15:13 UTC, jeremieb-pass commented on api/src/pcapi/templates/admin/support_beneficiary_details.html
> +                    action={{ url_for("/user_email_history.validate_user_email", entry_id=email_history.id, next="support_beneficiary.details_view", id=model.id) }}
Pas sûr de bien comprendre tes remarques =/
Ici `next` et `id` seront utilisés pour construire l'url de redirection : 

```python
try:
    extra = {param: value for param, value in request.args.items() if param != "next"}
    next_url = url_for(request.args["next"], **extra)
except (BadRequestKeyError, BuildError):
    next_url = url_for(".index_view")
```

2021-12-31 15:41 UTC, jeremieb-pass commented on api/src/pcapi/admin/custom_views/user_email_history_view.py
> +                f"L'adresse email {entry.newEmail} de l'utilisateur {entry.userId} avait déjà été validée",
Flask active l'option _autoescape_ de Jinja.

2021-12-31 15:44 UTC, jeremieb-pass commented on api/src/pcapi/admin/custom_views/user_email_history_view.py
> +                flash(f"L'utilisateur avec l'adresse email {entry.oldEmail} n'a pas été trouvé", category="error")
Si une validation a lieu entre le moment où la page est affichée et le moment où le super admin décide de valider la nouvelle adresse, on ne retrouvera pas l'ancienne adresse. Ou autre cas de figure très peu probable dans le genre.

2021-12-31 16:04 UTC, jeremieb-pass commented on api/src/pcapi/core/users/email/repository.py
> +        user=entry.user,
Normalement ça ne devrait pas poser de soucis (user=entry.user).

2021-12-31 16:58 UTC, jeremieb-pass commented on api/src/pcapi/core/testing.py
> +def assert_evolution(model, delta):
`assert_model_objects_evolution` ?

2021-12-31 17:22 UTC, bruno-ebstein-pass-culture commented on api/src/pcapi/core/users/models.py
> +            return cls._build(user, new_email, device_id, event_type=EmailHistoryEventTypeEnum.ADMIN_VALIDATION)
c'est un peu détourner le `deviceId` mais c'était ce qu'il y avait de plus facile à faire

2021-12-31 17:25 UTC, bruno-ebstein-pass-culture approved these changes

2022-01-03 10:47 UTC, bruno-ebstein-pass-culture approved these changes

2022-01-04 12:41 UTC, dbaty commented on api/src/pcapi/core/testing.py
> +def assert_model_objects_evolution(model, delta):
Avis non sollicité : est-ce que le nom `assert_model_count_delta` ne serait pas plus parlant ?

2022-01-04 14:49 UTC, merged