Pc 12398 archive beneficiaries id pictures
pass-culture/pass-culture-main pull request #907
Opened 2022-01-03 14:20 UTC by dupush

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-XXXXX

## But de la pull request

Obtenir les urls auprès d'Ubble des images de pièce d'identité des bénéficiaires, soumises dans le contexte de vérification d'identité.

##  Implémentation

- Ajout d'un champ `idPicturesStored` dans `BeneficiaryFraudCheck` qui va permettre d'identifier les bénéficiaires pour lesquels la PID aura été récupérée.
- Ajout d'un endpoint dédié qui devra être appelé par Google Cloud Task pour lancer la récupération en asynchrone de l'image.
​
##  Informations supplémentaires

​
## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [x] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket
- [X] J'ai écrit les tests nécessaires
- [ ] J'ai vérifié les migrations (upgrade / downgrade ; locks ; édition de `alembic_version_conflict_detection.txt`)
- [ ] J'ai tenté d'améliorer la dette technique (BSR, déplacement de modèles dans `pcapi.core`, etc)
- [ ] J'ai ajouté un / des screenshots pour d'éventuels changements graphiques (ex: Admin)

2022-01-03 16:22 UTC, dbaty commented on api/src/pcapi/alembic/versions/20211222T152126_c8ced1e097ac_add_id_pictures_stored_column.py
> +"""add_id_pictures_stored_column
(détail)

```suggestion
"""Add beneficiary_fraud_check.idPicturesStored
```

Ainsi, quand on fait un `alembic history`, cette description s'affiche et on sait exactement ce que fait cette migration.

2022-01-03 16:22 UTC, dbaty commented on api/src/pcapi/routes/external/users_subscription.py
> +@public_api.route("/webhooks/store_ubble_id_pictures", methods=["POST"])
(détail / nommage)

Je propose de suivre le nommage des autres endpoints de type webhook : 

```suggestion
@public_api.route("/webhooks/ubble/store_id_pictures", methods=["POST"])
```

2022-01-12 13:29 UTC, dbaty approved these changes
Ok sur le fond (à part quelques interrogations de ma part, cf. Slack), principalement des détails sur la forme.

2022-01-13 09:07 UTC, dupush commented on api/src/pcapi/core/subscription/ubble/api.py
> +        del response
Copie de bout de code.
Effectivement, pas de but précis.
J'enlève

2022-01-13 09:09 UTC, dupush commented on api/src/pcapi/core/subscription/ubble/api.py
> +    if response.status_code == 200:
D'accord avec toi, c'est plus propre avec ta suggestion.

2022-02-18 11:55 UTC, xordoquy requested changes

2022-02-18 11:55 UTC, xordoquy commented on api/src/pcapi/alembic/versions/20220103T162513_60b61de718ac_add_id_pictures_stored_column.py
> +branch_labels = None
Il faudra penser à rebaser et régénérer les migrations suite à l'introduction des pre/post deploy

2022-03-02 10:57 UTC, dbaty approved these changes

2022-03-02 11:17 UTC, dupush commented on api/src/pcapi/settings.py
> +OSC_ENDPOINT_URL = os.environ.get("OSC_ENDPOINT_URL", "https://oos.cloudgouv-eu-west-1.outscale.com")
Effectivement, j'ai hésité entre concision et expressivité.
Je remplace par Outscale.

2022-03-04 08:49 UTC, dbaty commented on api/.env.development
> +OUTSCALE_SECNUM_BUCKET_NAME=passculture-metier-ehp-development-idpictures
ça n'est pas dans l'ordre alphabétique (cf. aussi les autres fichiers .env)

2022-03-04 08:49 UTC, dbaty commented on api/src/pcapi/core/subscription/ubble/api.py
> +    # update fraud_models.BeneficiaryFraudCheck.storedIdPict
Je ne comprends pas ce commentaire. Il n'y a pas de champ `storedIdPict`. S'il s'agit du champ `idPicturesStored`, on peut sûrement supprimer le commentaire, le code est assez clair.

2022-03-04 08:49 UTC, dbaty commented
Détail : je pense qu'on pourrait fusionner les 2 premiers commits : le 1er ajoute une var d'environnement et 2-3 bidules qui sont supprimés ou modifiés dans le 2ème. Fusionner ces 2 premiers commits rendrait l'historique plus clair, à mon avis.

2022-03-04 11:31 UTC, dupush commented on api/src/pcapi/core/subscription/ubble/api.py
> +    # update fraud_models.BeneficiaryFraudCheck.storedIdPict
oui, il s'agissait bien du champ `idPicturesStored` et donc je supprime le commentaire.

2022-03-08 12:48 UTC, merged