(PC-25521)[PRO] feat: Wording de quantité, ajout d'espace
pass-culture/pass-culture-main pull request #9220
Opened 2023-11-20 11:05 UTC by TetyanaZhabchyk

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-XXXXX

## Vérifications

- [ ] J'ai écrit les tests nécessaires
- [ ] J'ai relu attentivement les migrations, en particulier pour éviter les _locks_, et je préviens les équipes Shérif et Data
- [ ] J'ai ajouté des screenshots pour d'éventuels changements graphiques

2023-11-20 13:18 UTC, mariedestandau commented on pro/src/pages/Offers/Offers/OfferItem/Cells/OfferRemainingStockCell/OfferRemainingStockCell.tsx
> +    return formattedStock.replace(/\B(?=(\d{3})+(?!\d))/g, ' ')
`return new Intl.NumberFormat('fr-FR').format( totalRemainingStock)`
ça ne suffit pas comme ça ? d'après la doc si l'environnement est en français l'espace sera ajouté https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#utilisation_simple

2023-11-21 13:09 UTC, AlbericTrancart commented on pro/src/pages/Offers/Offers/OfferItem/Cells/OfferNameCell/OfferNameCell.tsx
> +      : new Intl.NumberFormat('fr-FR').format(stockSize) +
Plutôt que le faire uniquement dans ce cas ce qui te force à remplacer `pluralize` par `pluralizeString`, est-ce que tu peux modifier la fonction `pluralize` pour que ça affecte tous les endroits où elle est utilisée d'un coup ?

2023-11-22 08:39 UTC, AlbericTrancart approved these changes

2023-11-29 12:36 UTC, Aliochka approved these changes

2023-11-29 15:12 UTC, mariedestandau approved these changes

2023-11-29 16:17 UTC, mariedestandau commented on pro/src/components/StocksEventList/StocksEventList.tsx
> -          )} occurrences ont été supprimées`
j'ai l'impression que cette suppression n'était pas voulue

2023-11-29 16:19 UTC, mariedestandau requested changes
https://github.com/pass-culture/pass-culture-main/pull/9371

2023-11-29 16:19 UTC, mariedestandau commented on pro/src/components/StocksEventList/StocksEventList.tsx
> -          )} occurrences ont été supprimées`
j'ai l’impression que cette suppression n'était pas voulue

2023-12-04 13:51 UTC, merged