PC 25882 adage add venue ids offerer name
pass-culture/pass-culture-main pull request #9469
Opened 2023-12-04 16:39 UTC by jeremieb-pass

## But de la pull request

Ticket Jira (ou description si BSR) : https://passculture.atlassian.net/browse/PC-25882 

api adage (v1)

ajout de deux informations aux réponses des routes concernant les pré-réservations : 1. identifiant du lieu et 2. nom de la structure.

## Au passage

Amélioration et factorisations de fonctions qui vont chercher des réservations en base de données.
Factorisation de code de test : ajout (principalement) de fonctions qui permettent de générer le `dict` attendu dans la réponse. Cela évite d'avoir plein de fois le même objet dans plein de fichier de tests différents. Cela permettra à l'avenir de n'avoir à mettre à jour qu'un fonction de test, au lieu d'aller chercher toutes les fonctions de tests qui vérifient en détail le JSON de la réponse.

2023-12-12 08:34 UTC, xordoquy commented on api/src/pcapi/routes/adage/v1/serialization/prebooking.py
> +    id: int | None
Je ne comprends pas pourquoi est-ce que les champs deviennent nullable.

2023-12-12 08:34 UTC, xordoquy commented on api/src/pcapi/core/educational/api/booking.py
> +    collective_booking = educational_repository.find_collective_booking_by_id(educational_booking_id)
C'est bien vu. Par contre, est-ce que ce ne serait pas pertinent et le bon moment pour ajouter une vérification sur le nombre de requêtes dans un test quelque part ?

2023-12-21 10:16 UTC, xordoquy requested changes

2023-12-21 10:16 UTC, xordoquy commented on api/src/pcapi/core/educational/api/booking.py
> +        [collective_booking.collectiveStock.collectiveOffer.id],
L'avantage de la version précédente est de ne pas traverser une jointure supplémentaire.
Qu'est-ce que la modification apporte ?

2023-12-21 15:07 UTC, jeremieb-pass commented on api/src/pcapi/core/educational/api/booking.py
> +        [collective_booking.collectiveStock.collectiveOffer.id],
Ce doit être un oubli : j'ai fait plusieurs petites modifications en local pour voir d'où venait les requêtes supplémentaires et j'ai dû oublier de remettre cette ligne comme avant.

2024-01-08 07:50 UTC, xordoquy approved these changes

2024-01-08 14:44 UTC, merged