(PC-12493) api: delete old webapp endpoints
pass-culture/pass-culture-main pull request #966
Opened 2022-01-07 14:28 UTC by antoinewg

Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-12493

## But de la pull request

Suppression des endpoints de l'ancienne webapp.

## Checklist :

- [x] La branche est bien nommée et les commits réfèrent le ticket Jira
    - [ ] Branche : pc-XXX-whatever-describe-the-branch
    - [ ] PR : (PC-XXX) Description rapide de l' US
    - [ ] Commit(s) : [PC-XXX] description rapide du ticket

2022-01-07 15:47 UTC, antoinewg commented on api/src/pcapi/routes/webapp/mailing_contacts.py
> -def save_mailing_contact(body: MailingContactBodyModel) -> MailingContactResponseModel:
pas sûr de la suppresion de cette endpoint. Mais vu qu'il était dans webapp je l'ai supprimé.

2022-01-12 14:03 UTC, xordoquy approved these changes
Un peu conséquent pour que je repasse route par route pour vérifier le détail.
L'ensemble m'a l'air bon, je suis d'avis que l'on merge ça juste après le prochain tag et que l'on observe en testing.

2022-01-12 14:03 UTC, xordoquy commented on api/src/pcapi/routes/serialization/beneficiaries.py
>  class SendPhoneValidationRequest(BaseModel):
On a encore besoin de cette classe ? Coté app native, il y a déjà https://github.com/pass-culture/pass-culture-main/blob/d771529fbed73849b2d945e7117c477434c7fdd6/api/src/pcapi/routes/native/v1/serialization/account.py#L309

2022-01-12 14:07 UTC, xordoquy requested changes
oh, par contre `api/tests/core/fraud/test_api.py` ne devrait probablement pas être supprimé

2022-01-12 15:44 UTC, antoinewg commented on api/src/pcapi/routes/serialization/beneficiaries.py
>  class SendPhoneValidationRequest(BaseModel):
en effet non,  je supprime

2022-01-12 17:28 UTC, dzen commented
heu non non, surtout pas ! 

le nettoyage de ce qu'il était nécessaire de supprimer de Jouve est deja Mergé  :)

Attention de ne pas aller trop loin dans cette PR : supprimez les endpoints mais vérifiez bien que les méthodes dans les modules API ne soient utilisés :)

2022-01-13 14:34 UTC, antoinewg commented
Je ferme cette PR. Migré dans celle ci https://github.com/pass-culture/pass-culture-main/pull/1016 (commit par commit)

2022-01-13 14:34 UTC, closed without merging